// Three pastel themes for Spaniel. Each theme = a set of CSS vars + a
// service-color palette. Components consume `theme.css` (string of CSS vars)
// applied to the artboard root, plus `theme.svc` for service swatches.

const THEMES = {
  // ─── Field — terminal printout. Paper-cream, deep ink, mono everywhere,
  // ASCII box-drawing chrome.  No drop shadows, sharp edges, single accent.
  field: {
    name: 'Field',
    tag: 'terminal · printout · mono',
    kind: 'field',
    css: {
      '--bg':        '#efe9d3',
      '--surface':   '#f7f1da',
      '--surface2':  '#ebe3c2',
      '--surface3':  '#ddd2a8',
      '--ink':       '#1b1d17',
      '--ink2':      '#4b4d42',
      '--ink3':      '#8c8c75',
      '--line':      '#bdb189',
      '--line2':     '#d2c79e',
      '--accent':    '#3a5a3d',
      '--accent2':   '#5d7a4f',
      '--accentInk': '#1f3320',
      '--warn':      '#b8923a',
      '--warnInk':   '#5e4a14',
      '--danger':    '#a4422c',
      '--dangerInk': '#6a2810',
      '--ok':        '#557a3d',
      '--chipBg':    '#e4daba',
      '--chipInk':   '#3a3a28',
      '--shadow':    'none',
      '--mono':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--sans':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--serif':     '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
    },
    svc: {
      'api-gateway':       { fg:'#3a5a3d', bg:'#d6e0bc' },
      'cart-service':      { fg:'#7a5d1e', bg:'#ecdba6' },
      'pricing-service':   { fg:'#7a3a23', bg:'#ecc9b3' },
      'inventory-service': { fg:'#4a4e6a', bg:'#cdd0e3' },
      'payment-service':   { fg:'#5a3f6e', bg:'#dccdec' },
      'redis':             { fg:'#7a3a23', bg:'#f0c9bd' },
      'postgres':          { fg:'#3a5a6e', bg:'#c8dde6' },
      'stripe':            { fg:'#5a3f6e', bg:'#e0d2ec' },
    },
  },

  // ─── Cartograph — editorial atlas. Warm tan paper, sepia ink, terracotta
  // accent, serif numerals, hairline dashed rules.
  cartograph: {
    name: 'Cartograph',
    tag: 'atlas · serif · marginalia',
    kind: 'cartograph',
    css: {
      '--bg':        '#f0e7d1',
      '--surface':   '#f8efd8',
      '--surface2':  '#ebe0c2',
      '--surface3':  '#dfd2ad',
      '--ink':       '#2a2418',
      '--ink2':      '#5d4f3a',
      '--ink3':      '#968360',
      '--line':      '#c8b88c',
      '--line2':     '#dcce9e',
      '--accent':    '#9a4f3b',
      '--accent2':   '#b07159',
      '--accentInk': '#5a2a18',
      '--warn':      '#c89858',
      '--warnInk':   '#6a4f0e',
      '--danger':    '#9a3b3b',
      '--dangerInk': '#5a1818',
      '--ok':        '#6a7a3d',
      '--chipBg':    '#ebd9b3',
      '--chipInk':   '#5a4a28',
      '--shadow':    '0 1px 0 #ddc99a, 0 8px 18px -12px rgba(80,50,20,.18)',
      '--mono':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--sans':      '"Inter Tight", "Inter", -apple-system, system-ui, sans-serif',
      '--serif':     '"Fraunces", "Iowan Old Style", Georgia, serif',
    },
    svc: {
      'api-gateway':       { fg:'#5a2a18', bg:'#ecccb9' },
      'cart-service':      { fg:'#6a4f0e', bg:'#ecdba6' },
      'pricing-service':   { fg:'#7a3a23', bg:'#ecc8b3' },
      'inventory-service': { fg:'#3d4a30', bg:'#cfd9b6' },
      'payment-service':   { fg:'#3a4a6a', bg:'#c4cde0' },
      'redis':             { fg:'#7a3a23', bg:'#ecc6ba' },
      'postgres':          { fg:'#3a5a6e', bg:'#c4d8e0' },
      'stripe':            { fg:'#3a4a6a', bg:'#c4cde0' },
    },
  },

  meadow: {
    name: 'Meadow',
    tag: 'sage · butter · cream',
    css: {
      '--bg':        '#efeadc',
      '--surface':   '#faf6ea',
      '--surface2':  '#f3eedf',
      '--surface3':  '#ebe5d2',
      '--ink':       '#2b3027',
      '--ink2':      '#5d6256',
      '--ink3':      '#8a8d7e',
      '--line':      '#dcd5be',
      '--line2':     '#ebe5d0',
      '--accent':    '#7fa17a',
      '--accent2':   '#a7c39c',
      '--accentInk': '#3d5538',
      '--warn':      '#d9b860',
      '--warnInk':   '#7a5d1e',
      '--danger':    '#c97a5b',
      '--dangerInk': '#7a3a23',
      '--ok':        '#8cb38a',
      '--chipBg':    '#e8e4d0',
      '--chipInk':   '#48503f',
      '--shadow':    '0 1px 0 #e3dcc4, 0 12px 24px -16px rgba(60,70,40,.18)',
      '--mono':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--sans':      '"Inter Tight", "Inter", -apple-system, system-ui, sans-serif',
      '--serif':     '"Fraunces", "Iowan Old Style", Georgia, serif',
    },
    svc: {
      'api-gateway':       { fg: '#3d5538', bg: '#cfe0c2' },
      'cart-service':      { fg: '#7a5d1e', bg: '#ecdba6' },
      'pricing-service':   { fg: '#7a3a23', bg: '#ecc9b3' },
      'inventory-service': { fg: '#4a4e6a', bg: '#cdd0e3' },
      'payment-service':   { fg: '#5a3f6e', bg: '#dccdec' },
      'redis':             { fg: '#7a3a23', bg: '#f0c9bd' },
      'postgres':          { fg: '#3a5a6e', bg: '#c8dde6' },
      'stripe':            { fg: '#5a3f6e', bg: '#e0d2ec' },
    },
  },
  petal: {
    name: 'Petal',
    tag: 'lavender · apricot · plum',
    css: {
      '--bg':        '#ece5ec',
      '--surface':   '#faf3f6',
      '--surface2':  '#f3ecf1',
      '--surface3':  '#ebe1ea',
      '--ink':       '#2e2733',
      '--ink2':      '#615769',
      '--ink3':      '#938898',
      '--line':      '#dbcfd9',
      '--line2':     '#ebe0e8',
      '--accent':    '#a692c4',
      '--accent2':   '#c7b7e0',
      '--accentInk': '#4b3a6e',
      '--warn':      '#e0a06e',
      '--warnInk':   '#7a4a23',
      '--danger':    '#d77a8e',
      '--dangerInk': '#7a2d44',
      '--ok':        '#9bbd9a',
      '--chipBg':    '#ebdfe8',
      '--chipInk':   '#4d3f54',
      '--shadow':    '0 1px 0 #ead6e3, 0 12px 24px -16px rgba(80,40,90,.16)',
      '--mono':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--sans':      '"Inter Tight", "Inter", -apple-system, system-ui, sans-serif',
      '--serif':     '"Fraunces", "Iowan Old Style", Georgia, serif',
    },
    svc: {
      'api-gateway':       { fg: '#4b3a6e', bg: '#dccdec' },
      'cart-service':      { fg: '#7a4a23', bg: '#f2d6bc' },
      'pricing-service':   { fg: '#7a2d44', bg: '#f0c8d2' },
      'inventory-service': { fg: '#3a5a6e', bg: '#c8dde6' },
      'payment-service':   { fg: '#3d5538', bg: '#cfe0c2' },
      'redis':             { fg: '#7a2d44', bg: '#f3c4ce' },
      'postgres':          { fg: '#3a5a6e', bg: '#c8dde6' },
      'stripe':            { fg: '#4b3a6e', bg: '#d6c4e7' },
    },
  },
  drift: {
    name: 'Drift',
    tag: 'sky · sand · slate',
    css: {
      '--bg':        '#e4eaf0',
      '--surface':   '#f5f9fc',
      '--surface2':  '#eaeff5',
      '--surface3':  '#dfe6ed',
      '--ink':       '#1f2937',
      '--ink2':      '#54616e',
      '--ink3':      '#8693a1',
      '--line':      '#cdd6df',
      '--line2':     '#dde4ec',
      '--accent':    '#7aa3c4',
      '--accent2':   '#a8c4dc',
      '--accentInk': '#284a6a',
      '--warn':      '#d6b46a',
      '--warnInk':   '#6a4f1e',
      '--danger':    '#d68a7a',
      '--dangerInk': '#7a3a2a',
      '--ok':        '#88b29a',
      '--chipBg':    '#dde6ee',
      '--chipInk':   '#3d4a58',
      '--shadow':    '0 1px 0 #d6dee6, 0 12px 24px -16px rgba(30,50,80,.18)',
      '--mono':      '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
      '--sans':      '"Inter Tight", "Inter", -apple-system, system-ui, sans-serif',
      '--serif':     '"Fraunces", "Iowan Old Style", Georgia, serif',
    },
    svc: {
      'api-gateway':       { fg: '#284a6a', bg: '#c4d8e8' },
      'cart-service':      { fg: '#6a4f1e', bg: '#ecdcb4' },
      'pricing-service':   { fg: '#7a3a2a', bg: '#ecc8bc' },
      'inventory-service': { fg: '#3d5538', bg: '#cfe0c2' },
      'payment-service':   { fg: '#4b3a6e', bg: '#d6c8e6' },
      'redis':             { fg: '#7a3a2a', bg: '#ecc6ba' },
      'postgres':          { fg: '#284a6a', bg: '#c4d8e8' },
      'stripe':            { fg: '#4b3a6e', bg: '#d6c8e6' },
    },
  },
};

// CSS string from a theme's css var map
function themeCssString(t) {
  return Object.entries(t.css).map(([k, v]) => `${k}:${v}`).join(';');
}

window.THEMES = THEMES;
window.themeCssString = themeCssString;
