// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newAlertSilence(db *gorm.DB, opts ...gen.DOOption) alertSilence {
	_alertSilence := alertSilence{}

	_alertSilence.alertSilenceDo.UseDB(db, opts...)
	_alertSilence.alertSilenceDo.UseModel(&model.AlertSilence{})

	tableName := _alertSilence.alertSilenceDo.TableName()
	_alertSilence.ALL = field.NewAsterisk(tableName)
	_alertSilence.ID = field.NewString(tableName, "id")
	_alertSilence.RuleID = field.NewString(tableName, "rule_id")
	_alertSilence.GroupKey = field.NewString(tableName, "group_key")
	_alertSilence.Comment = field.NewString(tableName, "comment")
	_alertSilence.StartsAt = field.NewInt64(tableName, "starts_at")
	_alertSilence.EndsAt = field.NewInt64(tableName, "ends_at")
	_alertSilence.CreatedAt = field.NewInt64(tableName, "created_at")

	_alertSilence.fillFieldMap()

	return _alertSilence
}

type alertSilence struct {
	alertSilenceDo

	ALL       field.Asterisk
	ID        field.String
	RuleID    field.String
	GroupKey  field.String
	Comment   field.String
	StartsAt  field.Int64
	EndsAt    field.Int64
	CreatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (a alertSilence) Table(newTableName string) *alertSilence {
	a.alertSilenceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertSilence) As(alias string) *alertSilence {
	a.alertSilenceDo.DO = *(a.alertSilenceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertSilence) updateTableName(table string) *alertSilence {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RuleID = field.NewString(table, "rule_id")
	a.GroupKey = field.NewString(table, "group_key")
	a.Comment = field.NewString(table, "comment")
	a.StartsAt = field.NewInt64(table, "starts_at")
	a.EndsAt = field.NewInt64(table, "ends_at")
	a.CreatedAt = field.NewInt64(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *alertSilence) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertSilence) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["group_key"] = a.GroupKey
	a.fieldMap["comment"] = a.Comment
	a.fieldMap["starts_at"] = a.StartsAt
	a.fieldMap["ends_at"] = a.EndsAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a alertSilence) clone(db *gorm.DB) alertSilence {
	a.alertSilenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertSilence) replaceDB(db *gorm.DB) alertSilence {
	a.alertSilenceDo.ReplaceDB(db)
	return a
}

type alertSilenceDo struct{ gen.DO }

type IAlertSilenceDo interface {
	gen.SubQuery
	Debug() IAlertSilenceDo
	WithContext(ctx context.Context) IAlertSilenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertSilenceDo
	WriteDB() IAlertSilenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertSilenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertSilenceDo
	Not(conds ...gen.Condition) IAlertSilenceDo
	Or(conds ...gen.Condition) IAlertSilenceDo
	Select(conds ...field.Expr) IAlertSilenceDo
	Where(conds ...gen.Condition) IAlertSilenceDo
	Order(conds ...field.Expr) IAlertSilenceDo
	Distinct(cols ...field.Expr) IAlertSilenceDo
	Omit(cols ...field.Expr) IAlertSilenceDo
	Join(table schema.Tabler, on ...field.Expr) IAlertSilenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertSilenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertSilenceDo
	Group(cols ...field.Expr) IAlertSilenceDo
	Having(conds ...gen.Condition) IAlertSilenceDo
	Limit(limit int) IAlertSilenceDo
	Offset(offset int) IAlertSilenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertSilenceDo
	Unscoped() IAlertSilenceDo
	Create(values ...*model.AlertSilence) error
	CreateInBatches(values []*model.AlertSilence, batchSize int) error
	Save(values ...*model.AlertSilence) error
	First() (*model.AlertSilence, error)
	Take() (*model.AlertSilence, error)
	Last() (*model.AlertSilence, error)
	Find() ([]*model.AlertSilence, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertSilence, err error)
	FindInBatches(result *[]*model.AlertSilence, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertSilence) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertSilenceDo
	Assign(attrs ...field.AssignExpr) IAlertSilenceDo
	Joins(fields ...field.RelationField) IAlertSilenceDo
	Preload(fields ...field.RelationField) IAlertSilenceDo
	FirstOrInit() (*model.AlertSilence, error)
	FirstOrCreate() (*model.AlertSilence, error)
	FindByPage(offset int, limit int) (result []*model.AlertSilence, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertSilenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertSilenceDo) Debug() IAlertSilenceDo {
	return a.withDO(a.DO.Debug())
}

func (a alertSilenceDo) WithContext(ctx context.Context) IAlertSilenceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertSilenceDo) ReadDB() IAlertSilenceDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertSilenceDo) WriteDB() IAlertSilenceDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertSilenceDo) Session(config *gorm.Session) IAlertSilenceDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertSilenceDo) Clauses(conds ...clause.Expression) IAlertSilenceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertSilenceDo) Returning(value interface{}, columns ...string) IAlertSilenceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertSilenceDo) Not(conds ...gen.Condition) IAlertSilenceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertSilenceDo) Or(conds ...gen.Condition) IAlertSilenceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertSilenceDo) Select(conds ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertSilenceDo) Where(conds ...gen.Condition) IAlertSilenceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertSilenceDo) Order(conds ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertSilenceDo) Distinct(cols ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertSilenceDo) Omit(cols ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertSilenceDo) Join(table schema.Tabler, on ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertSilenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertSilenceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertSilenceDo) Group(cols ...field.Expr) IAlertSilenceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertSilenceDo) Having(conds ...gen.Condition) IAlertSilenceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertSilenceDo) Limit(limit int) IAlertSilenceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertSilenceDo) Offset(offset int) IAlertSilenceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertSilenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertSilenceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertSilenceDo) Unscoped() IAlertSilenceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertSilenceDo) Create(values ...*model.AlertSilence) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertSilenceDo) CreateInBatches(values []*model.AlertSilence, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertSilenceDo) Save(values ...*model.AlertSilence) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertSilenceDo) First() (*model.AlertSilence, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSilence), nil
	}
}

func (a alertSilenceDo) Take() (*model.AlertSilence, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSilence), nil
	}
}

func (a alertSilenceDo) Last() (*model.AlertSilence, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSilence), nil
	}
}

func (a alertSilenceDo) Find() ([]*model.AlertSilence, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertSilence), err
}

func (a alertSilenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertSilence, err error) {
	buf := make([]*model.AlertSilence, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertSilenceDo) FindInBatches(result *[]*model.AlertSilence, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertSilenceDo) Attrs(attrs ...field.AssignExpr) IAlertSilenceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertSilenceDo) Assign(attrs ...field.AssignExpr) IAlertSilenceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertSilenceDo) Joins(fields ...field.RelationField) IAlertSilenceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertSilenceDo) Preload(fields ...field.RelationField) IAlertSilenceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertSilenceDo) FirstOrInit() (*model.AlertSilence, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSilence), nil
	}
}

func (a alertSilenceDo) FirstOrCreate() (*model.AlertSilence, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertSilence), nil
	}
}

func (a alertSilenceDo) FindByPage(offset int, limit int) (result []*model.AlertSilence, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertSilenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertSilenceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertSilenceDo) Delete(models ...*model.AlertSilence) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertSilenceDo) withDO(do gen.Dao) *alertSilenceDo {
	a.DO = *do.(*gen.DO)
	return a
}
