// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newAlertEvent(db *gorm.DB, opts ...gen.DOOption) alertEvent {
	_alertEvent := alertEvent{}

	_alertEvent.alertEventDo.UseDB(db, opts...)
	_alertEvent.alertEventDo.UseModel(&model.AlertEvent{})

	tableName := _alertEvent.alertEventDo.TableName()
	_alertEvent.ALL = field.NewAsterisk(tableName)
	_alertEvent.ID = field.NewString(tableName, "id")
	_alertEvent.RuleID = field.NewString(tableName, "rule_id")
	_alertEvent.GroupKey = field.NewString(tableName, "group_key")
	_alertEvent.Kind = field.NewString(tableName, "kind")
	_alertEvent.State = field.NewString(tableName, "state")
	_alertEvent.Value = field.NewFloat64(tableName, "value")
	_alertEvent.Detail = field.NewString(tableName, "detail")
	_alertEvent.CreatedAt = field.NewInt64(tableName, "created_at")

	_alertEvent.fillFieldMap()

	return _alertEvent
}

type alertEvent struct {
	alertEventDo

	ALL       field.Asterisk
	ID        field.String
	RuleID    field.String
	GroupKey  field.String
	Kind      field.String
	State     field.String
	Value     field.Float64
	Detail    field.String
	CreatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (a alertEvent) Table(newTableName string) *alertEvent {
	a.alertEventDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertEvent) As(alias string) *alertEvent {
	a.alertEventDo.DO = *(a.alertEventDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertEvent) updateTableName(table string) *alertEvent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.RuleID = field.NewString(table, "rule_id")
	a.GroupKey = field.NewString(table, "group_key")
	a.Kind = field.NewString(table, "kind")
	a.State = field.NewString(table, "state")
	a.Value = field.NewFloat64(table, "value")
	a.Detail = field.NewString(table, "detail")
	a.CreatedAt = field.NewInt64(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *alertEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertEvent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["group_key"] = a.GroupKey
	a.fieldMap["kind"] = a.Kind
	a.fieldMap["state"] = a.State
	a.fieldMap["value"] = a.Value
	a.fieldMap["detail"] = a.Detail
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a alertEvent) clone(db *gorm.DB) alertEvent {
	a.alertEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertEvent) replaceDB(db *gorm.DB) alertEvent {
	a.alertEventDo.ReplaceDB(db)
	return a
}

type alertEventDo struct{ gen.DO }

type IAlertEventDo interface {
	gen.SubQuery
	Debug() IAlertEventDo
	WithContext(ctx context.Context) IAlertEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertEventDo
	WriteDB() IAlertEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertEventDo
	Not(conds ...gen.Condition) IAlertEventDo
	Or(conds ...gen.Condition) IAlertEventDo
	Select(conds ...field.Expr) IAlertEventDo
	Where(conds ...gen.Condition) IAlertEventDo
	Order(conds ...field.Expr) IAlertEventDo
	Distinct(cols ...field.Expr) IAlertEventDo
	Omit(cols ...field.Expr) IAlertEventDo
	Join(table schema.Tabler, on ...field.Expr) IAlertEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertEventDo
	Group(cols ...field.Expr) IAlertEventDo
	Having(conds ...gen.Condition) IAlertEventDo
	Limit(limit int) IAlertEventDo
	Offset(offset int) IAlertEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertEventDo
	Unscoped() IAlertEventDo
	Create(values ...*model.AlertEvent) error
	CreateInBatches(values []*model.AlertEvent, batchSize int) error
	Save(values ...*model.AlertEvent) error
	First() (*model.AlertEvent, error)
	Take() (*model.AlertEvent, error)
	Last() (*model.AlertEvent, error)
	Find() ([]*model.AlertEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertEvent, err error)
	FindInBatches(result *[]*model.AlertEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertEventDo
	Assign(attrs ...field.AssignExpr) IAlertEventDo
	Joins(fields ...field.RelationField) IAlertEventDo
	Preload(fields ...field.RelationField) IAlertEventDo
	FirstOrInit() (*model.AlertEvent, error)
	FirstOrCreate() (*model.AlertEvent, error)
	FindByPage(offset int, limit int) (result []*model.AlertEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertEventDo) Debug() IAlertEventDo {
	return a.withDO(a.DO.Debug())
}

func (a alertEventDo) WithContext(ctx context.Context) IAlertEventDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertEventDo) ReadDB() IAlertEventDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertEventDo) WriteDB() IAlertEventDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertEventDo) Session(config *gorm.Session) IAlertEventDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertEventDo) Clauses(conds ...clause.Expression) IAlertEventDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertEventDo) Returning(value interface{}, columns ...string) IAlertEventDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertEventDo) Not(conds ...gen.Condition) IAlertEventDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertEventDo) Or(conds ...gen.Condition) IAlertEventDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertEventDo) Select(conds ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertEventDo) Where(conds ...gen.Condition) IAlertEventDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertEventDo) Order(conds ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertEventDo) Distinct(cols ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertEventDo) Omit(cols ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertEventDo) Join(table schema.Tabler, on ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertEventDo) Group(cols ...field.Expr) IAlertEventDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertEventDo) Having(conds ...gen.Condition) IAlertEventDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertEventDo) Limit(limit int) IAlertEventDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertEventDo) Offset(offset int) IAlertEventDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertEventDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertEventDo) Unscoped() IAlertEventDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertEventDo) Create(values ...*model.AlertEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertEventDo) CreateInBatches(values []*model.AlertEvent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertEventDo) Save(values ...*model.AlertEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertEventDo) First() (*model.AlertEvent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertEvent), nil
	}
}

func (a alertEventDo) Take() (*model.AlertEvent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertEvent), nil
	}
}

func (a alertEventDo) Last() (*model.AlertEvent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertEvent), nil
	}
}

func (a alertEventDo) Find() ([]*model.AlertEvent, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertEvent), err
}

func (a alertEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertEvent, err error) {
	buf := make([]*model.AlertEvent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertEventDo) FindInBatches(result *[]*model.AlertEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertEventDo) Attrs(attrs ...field.AssignExpr) IAlertEventDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertEventDo) Assign(attrs ...field.AssignExpr) IAlertEventDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertEventDo) Joins(fields ...field.RelationField) IAlertEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertEventDo) Preload(fields ...field.RelationField) IAlertEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertEventDo) FirstOrInit() (*model.AlertEvent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertEvent), nil
	}
}

func (a alertEventDo) FirstOrCreate() (*model.AlertEvent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertEvent), nil
	}
}

func (a alertEventDo) FindByPage(offset int, limit int) (result []*model.AlertEvent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertEventDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertEventDo) Delete(models ...*model.AlertEvent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertEventDo) withDO(do gen.Dao) *alertEventDo {
	a.DO = *do.(*gen.DO)
	return a
}
