// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newAlertInstanceTarget(db *gorm.DB, opts ...gen.DOOption) alertInstanceTarget {
	_alertInstanceTarget := alertInstanceTarget{}

	_alertInstanceTarget.alertInstanceTargetDo.UseDB(db, opts...)
	_alertInstanceTarget.alertInstanceTargetDo.UseModel(&model.AlertInstanceTarget{})

	tableName := _alertInstanceTarget.alertInstanceTargetDo.TableName()
	_alertInstanceTarget.ALL = field.NewAsterisk(tableName)
	_alertInstanceTarget.RuleID = field.NewString(tableName, "rule_id")
	_alertInstanceTarget.GroupKey = field.NewString(tableName, "group_key")
	_alertInstanceTarget.LabelsJSON = field.NewString(tableName, "labels_json")
	_alertInstanceTarget.DiscoveredAt = field.NewInt64(tableName, "discovered_at")
	_alertInstanceTarget.LastSeenAt = field.NewInt64(tableName, "last_seen_at")

	_alertInstanceTarget.fillFieldMap()

	return _alertInstanceTarget
}

type alertInstanceTarget struct {
	alertInstanceTargetDo

	ALL          field.Asterisk
	RuleID       field.String
	GroupKey     field.String
	LabelsJSON   field.String
	DiscoveredAt field.Int64
	LastSeenAt   field.Int64

	fieldMap map[string]field.Expr
}

func (a alertInstanceTarget) Table(newTableName string) *alertInstanceTarget {
	a.alertInstanceTargetDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertInstanceTarget) As(alias string) *alertInstanceTarget {
	a.alertInstanceTargetDo.DO = *(a.alertInstanceTargetDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertInstanceTarget) updateTableName(table string) *alertInstanceTarget {
	a.ALL = field.NewAsterisk(table)
	a.RuleID = field.NewString(table, "rule_id")
	a.GroupKey = field.NewString(table, "group_key")
	a.LabelsJSON = field.NewString(table, "labels_json")
	a.DiscoveredAt = field.NewInt64(table, "discovered_at")
	a.LastSeenAt = field.NewInt64(table, "last_seen_at")

	a.fillFieldMap()

	return a
}

func (a *alertInstanceTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertInstanceTarget) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["group_key"] = a.GroupKey
	a.fieldMap["labels_json"] = a.LabelsJSON
	a.fieldMap["discovered_at"] = a.DiscoveredAt
	a.fieldMap["last_seen_at"] = a.LastSeenAt
}

func (a alertInstanceTarget) clone(db *gorm.DB) alertInstanceTarget {
	a.alertInstanceTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertInstanceTarget) replaceDB(db *gorm.DB) alertInstanceTarget {
	a.alertInstanceTargetDo.ReplaceDB(db)
	return a
}

type alertInstanceTargetDo struct{ gen.DO }

type IAlertInstanceTargetDo interface {
	gen.SubQuery
	Debug() IAlertInstanceTargetDo
	WithContext(ctx context.Context) IAlertInstanceTargetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertInstanceTargetDo
	WriteDB() IAlertInstanceTargetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertInstanceTargetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertInstanceTargetDo
	Not(conds ...gen.Condition) IAlertInstanceTargetDo
	Or(conds ...gen.Condition) IAlertInstanceTargetDo
	Select(conds ...field.Expr) IAlertInstanceTargetDo
	Where(conds ...gen.Condition) IAlertInstanceTargetDo
	Order(conds ...field.Expr) IAlertInstanceTargetDo
	Distinct(cols ...field.Expr) IAlertInstanceTargetDo
	Omit(cols ...field.Expr) IAlertInstanceTargetDo
	Join(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo
	Group(cols ...field.Expr) IAlertInstanceTargetDo
	Having(conds ...gen.Condition) IAlertInstanceTargetDo
	Limit(limit int) IAlertInstanceTargetDo
	Offset(offset int) IAlertInstanceTargetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertInstanceTargetDo
	Unscoped() IAlertInstanceTargetDo
	Create(values ...*model.AlertInstanceTarget) error
	CreateInBatches(values []*model.AlertInstanceTarget, batchSize int) error
	Save(values ...*model.AlertInstanceTarget) error
	First() (*model.AlertInstanceTarget, error)
	Take() (*model.AlertInstanceTarget, error)
	Last() (*model.AlertInstanceTarget, error)
	Find() ([]*model.AlertInstanceTarget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertInstanceTarget, err error)
	FindInBatches(result *[]*model.AlertInstanceTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertInstanceTarget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertInstanceTargetDo
	Assign(attrs ...field.AssignExpr) IAlertInstanceTargetDo
	Joins(fields ...field.RelationField) IAlertInstanceTargetDo
	Preload(fields ...field.RelationField) IAlertInstanceTargetDo
	FirstOrInit() (*model.AlertInstanceTarget, error)
	FirstOrCreate() (*model.AlertInstanceTarget, error)
	FindByPage(offset int, limit int) (result []*model.AlertInstanceTarget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertInstanceTargetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertInstanceTargetDo) Debug() IAlertInstanceTargetDo {
	return a.withDO(a.DO.Debug())
}

func (a alertInstanceTargetDo) WithContext(ctx context.Context) IAlertInstanceTargetDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertInstanceTargetDo) ReadDB() IAlertInstanceTargetDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertInstanceTargetDo) WriteDB() IAlertInstanceTargetDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertInstanceTargetDo) Session(config *gorm.Session) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertInstanceTargetDo) Clauses(conds ...clause.Expression) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertInstanceTargetDo) Returning(value interface{}, columns ...string) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertInstanceTargetDo) Not(conds ...gen.Condition) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertInstanceTargetDo) Or(conds ...gen.Condition) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertInstanceTargetDo) Select(conds ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertInstanceTargetDo) Where(conds ...gen.Condition) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertInstanceTargetDo) Order(conds ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertInstanceTargetDo) Distinct(cols ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertInstanceTargetDo) Omit(cols ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertInstanceTargetDo) Join(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertInstanceTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertInstanceTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertInstanceTargetDo) Group(cols ...field.Expr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertInstanceTargetDo) Having(conds ...gen.Condition) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertInstanceTargetDo) Limit(limit int) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertInstanceTargetDo) Offset(offset int) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertInstanceTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertInstanceTargetDo) Unscoped() IAlertInstanceTargetDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertInstanceTargetDo) Create(values ...*model.AlertInstanceTarget) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertInstanceTargetDo) CreateInBatches(values []*model.AlertInstanceTarget, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertInstanceTargetDo) Save(values ...*model.AlertInstanceTarget) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertInstanceTargetDo) First() (*model.AlertInstanceTarget, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstanceTarget), nil
	}
}

func (a alertInstanceTargetDo) Take() (*model.AlertInstanceTarget, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstanceTarget), nil
	}
}

func (a alertInstanceTargetDo) Last() (*model.AlertInstanceTarget, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstanceTarget), nil
	}
}

func (a alertInstanceTargetDo) Find() ([]*model.AlertInstanceTarget, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertInstanceTarget), err
}

func (a alertInstanceTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertInstanceTarget, err error) {
	buf := make([]*model.AlertInstanceTarget, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertInstanceTargetDo) FindInBatches(result *[]*model.AlertInstanceTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertInstanceTargetDo) Attrs(attrs ...field.AssignExpr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertInstanceTargetDo) Assign(attrs ...field.AssignExpr) IAlertInstanceTargetDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertInstanceTargetDo) Joins(fields ...field.RelationField) IAlertInstanceTargetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertInstanceTargetDo) Preload(fields ...field.RelationField) IAlertInstanceTargetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertInstanceTargetDo) FirstOrInit() (*model.AlertInstanceTarget, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstanceTarget), nil
	}
}

func (a alertInstanceTargetDo) FirstOrCreate() (*model.AlertInstanceTarget, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstanceTarget), nil
	}
}

func (a alertInstanceTargetDo) FindByPage(offset int, limit int) (result []*model.AlertInstanceTarget, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertInstanceTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertInstanceTargetDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertInstanceTargetDo) Delete(models ...*model.AlertInstanceTarget) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertInstanceTargetDo) withDO(do gen.Dao) *alertInstanceTargetDo {
	a.DO = *do.(*gen.DO)
	return a
}
