// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newAlertRule(db *gorm.DB, opts ...gen.DOOption) alertRule {
	_alertRule := alertRule{}

	_alertRule.alertRuleDo.UseDB(db, opts...)
	_alertRule.alertRuleDo.UseModel(&model.AlertRule{})

	tableName := _alertRule.alertRuleDo.TableName()
	_alertRule.ALL = field.NewAsterisk(tableName)
	_alertRule.ID = field.NewString(tableName, "id")
	_alertRule.Name = field.NewString(tableName, "name")
	_alertRule.QuerySQL = field.NewString(tableName, "query_sql")
	_alertRule.QueryVersion = field.NewInt(tableName, "query_version")
	_alertRule.ConditionJSON = field.NewString(tableName, "condition_json")
	_alertRule.GroupByJSON = field.NewString(tableName, "group_by_json")
	_alertRule.PendingForNs = field.NewInt64(tableName, "pending_for_ns")
	_alertRule.CooldownNs = field.NewInt64(tableName, "cooldown_ns")
	_alertRule.RepeatIntervalNs = field.NewInt64(tableName, "repeat_interval_ns")
	_alertRule.Owner = field.NewString(tableName, "owner")
	_alertRule.Team = field.NewString(tableName, "team")
	_alertRule.Severity = field.NewString(tableName, "severity")
	_alertRule.AnnotationsJSON = field.NewString(tableName, "annotations_json")
	_alertRule.Enabled = field.NewBool(tableName, "enabled")
	_alertRule.BrowserEnabled = field.NewBool(tableName, "browser_enabled")
	_alertRule.PushoverEnabled = field.NewBool(tableName, "pushover_enabled")
	_alertRule.InstanceDiscoverySQL = field.NewString(tableName, "instance_discovery_sql")
	_alertRule.InstanceDiscoveryIntervalNs = field.NewInt64(tableName, "instance_discovery_interval_ns")
	_alertRule.InstanceDiscoveryStaleAfterNs = field.NewInt64(tableName, "instance_discovery_stale_after_ns")
	_alertRule.InstanceDiscoveryLastRunAt = field.NewInt64(tableName, "instance_discovery_last_run_at")
	_alertRule.LastEvaluatedAt = field.NewInt64(tableName, "last_evaluated_at")
	_alertRule.LastSuccessAt = field.NewInt64(tableName, "last_success_at")
	_alertRule.LastDurationNs = field.NewInt64(tableName, "last_duration_ns")
	_alertRule.NextEvaluationAt = field.NewInt64(tableName, "next_evaluation_at")
	_alertRule.LastError = field.NewString(tableName, "last_error")
	_alertRule.SourceFile = field.NewString(tableName, "source_file")
	_alertRule.SourceHash = field.NewString(tableName, "source_hash")
	_alertRule.CreatedAt = field.NewInt64(tableName, "created_at")
	_alertRule.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_alertRule.fillFieldMap()

	return _alertRule
}

type alertRule struct {
	alertRuleDo

	ALL                           field.Asterisk
	ID                            field.String
	Name                          field.String
	QuerySQL                      field.String
	QueryVersion                  field.Int
	ConditionJSON                 field.String
	GroupByJSON                   field.String
	PendingForNs                  field.Int64
	CooldownNs                    field.Int64
	RepeatIntervalNs              field.Int64
	Owner                         field.String
	Team                          field.String
	Severity                      field.String
	AnnotationsJSON               field.String
	Enabled                       field.Bool
	BrowserEnabled                field.Bool
	PushoverEnabled               field.Bool
	InstanceDiscoverySQL          field.String
	InstanceDiscoveryIntervalNs   field.Int64
	InstanceDiscoveryStaleAfterNs field.Int64
	InstanceDiscoveryLastRunAt    field.Int64
	LastEvaluatedAt               field.Int64
	LastSuccessAt                 field.Int64
	LastDurationNs                field.Int64
	NextEvaluationAt              field.Int64
	LastError                     field.String
	SourceFile                    field.String
	SourceHash                    field.String
	CreatedAt                     field.Int64
	UpdatedAt                     field.Int64

	fieldMap map[string]field.Expr
}

func (a alertRule) Table(newTableName string) *alertRule {
	a.alertRuleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertRule) As(alias string) *alertRule {
	a.alertRuleDo.DO = *(a.alertRuleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertRule) updateTableName(table string) *alertRule {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.Name = field.NewString(table, "name")
	a.QuerySQL = field.NewString(table, "query_sql")
	a.QueryVersion = field.NewInt(table, "query_version")
	a.ConditionJSON = field.NewString(table, "condition_json")
	a.GroupByJSON = field.NewString(table, "group_by_json")
	a.PendingForNs = field.NewInt64(table, "pending_for_ns")
	a.CooldownNs = field.NewInt64(table, "cooldown_ns")
	a.RepeatIntervalNs = field.NewInt64(table, "repeat_interval_ns")
	a.Owner = field.NewString(table, "owner")
	a.Team = field.NewString(table, "team")
	a.Severity = field.NewString(table, "severity")
	a.AnnotationsJSON = field.NewString(table, "annotations_json")
	a.Enabled = field.NewBool(table, "enabled")
	a.BrowserEnabled = field.NewBool(table, "browser_enabled")
	a.PushoverEnabled = field.NewBool(table, "pushover_enabled")
	a.InstanceDiscoverySQL = field.NewString(table, "instance_discovery_sql")
	a.InstanceDiscoveryIntervalNs = field.NewInt64(table, "instance_discovery_interval_ns")
	a.InstanceDiscoveryStaleAfterNs = field.NewInt64(table, "instance_discovery_stale_after_ns")
	a.InstanceDiscoveryLastRunAt = field.NewInt64(table, "instance_discovery_last_run_at")
	a.LastEvaluatedAt = field.NewInt64(table, "last_evaluated_at")
	a.LastSuccessAt = field.NewInt64(table, "last_success_at")
	a.LastDurationNs = field.NewInt64(table, "last_duration_ns")
	a.NextEvaluationAt = field.NewInt64(table, "next_evaluation_at")
	a.LastError = field.NewString(table, "last_error")
	a.SourceFile = field.NewString(table, "source_file")
	a.SourceHash = field.NewString(table, "source_hash")
	a.CreatedAt = field.NewInt64(table, "created_at")
	a.UpdatedAt = field.NewInt64(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *alertRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertRule) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 29)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["query_sql"] = a.QuerySQL
	a.fieldMap["query_version"] = a.QueryVersion
	a.fieldMap["condition_json"] = a.ConditionJSON
	a.fieldMap["group_by_json"] = a.GroupByJSON
	a.fieldMap["pending_for_ns"] = a.PendingForNs
	a.fieldMap["cooldown_ns"] = a.CooldownNs
	a.fieldMap["repeat_interval_ns"] = a.RepeatIntervalNs
	a.fieldMap["owner"] = a.Owner
	a.fieldMap["team"] = a.Team
	a.fieldMap["severity"] = a.Severity
	a.fieldMap["annotations_json"] = a.AnnotationsJSON
	a.fieldMap["enabled"] = a.Enabled
	a.fieldMap["browser_enabled"] = a.BrowserEnabled
	a.fieldMap["pushover_enabled"] = a.PushoverEnabled
	a.fieldMap["instance_discovery_sql"] = a.InstanceDiscoverySQL
	a.fieldMap["instance_discovery_interval_ns"] = a.InstanceDiscoveryIntervalNs
	a.fieldMap["instance_discovery_stale_after_ns"] = a.InstanceDiscoveryStaleAfterNs
	a.fieldMap["instance_discovery_last_run_at"] = a.InstanceDiscoveryLastRunAt
	a.fieldMap["last_evaluated_at"] = a.LastEvaluatedAt
	a.fieldMap["last_success_at"] = a.LastSuccessAt
	a.fieldMap["last_duration_ns"] = a.LastDurationNs
	a.fieldMap["next_evaluation_at"] = a.NextEvaluationAt
	a.fieldMap["last_error"] = a.LastError
	a.fieldMap["source_file"] = a.SourceFile
	a.fieldMap["source_hash"] = a.SourceHash
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a alertRule) clone(db *gorm.DB) alertRule {
	a.alertRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertRule) replaceDB(db *gorm.DB) alertRule {
	a.alertRuleDo.ReplaceDB(db)
	return a
}

type alertRuleDo struct{ gen.DO }

type IAlertRuleDo interface {
	gen.SubQuery
	Debug() IAlertRuleDo
	WithContext(ctx context.Context) IAlertRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertRuleDo
	WriteDB() IAlertRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertRuleDo
	Not(conds ...gen.Condition) IAlertRuleDo
	Or(conds ...gen.Condition) IAlertRuleDo
	Select(conds ...field.Expr) IAlertRuleDo
	Where(conds ...gen.Condition) IAlertRuleDo
	Order(conds ...field.Expr) IAlertRuleDo
	Distinct(cols ...field.Expr) IAlertRuleDo
	Omit(cols ...field.Expr) IAlertRuleDo
	Join(table schema.Tabler, on ...field.Expr) IAlertRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertRuleDo
	Group(cols ...field.Expr) IAlertRuleDo
	Having(conds ...gen.Condition) IAlertRuleDo
	Limit(limit int) IAlertRuleDo
	Offset(offset int) IAlertRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertRuleDo
	Unscoped() IAlertRuleDo
	Create(values ...*model.AlertRule) error
	CreateInBatches(values []*model.AlertRule, batchSize int) error
	Save(values ...*model.AlertRule) error
	First() (*model.AlertRule, error)
	Take() (*model.AlertRule, error)
	Last() (*model.AlertRule, error)
	Find() ([]*model.AlertRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertRule, err error)
	FindInBatches(result *[]*model.AlertRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertRuleDo
	Assign(attrs ...field.AssignExpr) IAlertRuleDo
	Joins(fields ...field.RelationField) IAlertRuleDo
	Preload(fields ...field.RelationField) IAlertRuleDo
	FirstOrInit() (*model.AlertRule, error)
	FirstOrCreate() (*model.AlertRule, error)
	FindByPage(offset int, limit int) (result []*model.AlertRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertRuleDo) Debug() IAlertRuleDo {
	return a.withDO(a.DO.Debug())
}

func (a alertRuleDo) WithContext(ctx context.Context) IAlertRuleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertRuleDo) ReadDB() IAlertRuleDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertRuleDo) WriteDB() IAlertRuleDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertRuleDo) Session(config *gorm.Session) IAlertRuleDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertRuleDo) Clauses(conds ...clause.Expression) IAlertRuleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertRuleDo) Returning(value interface{}, columns ...string) IAlertRuleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertRuleDo) Not(conds ...gen.Condition) IAlertRuleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertRuleDo) Or(conds ...gen.Condition) IAlertRuleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertRuleDo) Select(conds ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertRuleDo) Where(conds ...gen.Condition) IAlertRuleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertRuleDo) Order(conds ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertRuleDo) Distinct(cols ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertRuleDo) Omit(cols ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertRuleDo) Join(table schema.Tabler, on ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertRuleDo) Group(cols ...field.Expr) IAlertRuleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertRuleDo) Having(conds ...gen.Condition) IAlertRuleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertRuleDo) Limit(limit int) IAlertRuleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertRuleDo) Offset(offset int) IAlertRuleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertRuleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertRuleDo) Unscoped() IAlertRuleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertRuleDo) Create(values ...*model.AlertRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertRuleDo) CreateInBatches(values []*model.AlertRule, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertRuleDo) Save(values ...*model.AlertRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertRuleDo) First() (*model.AlertRule, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertRule), nil
	}
}

func (a alertRuleDo) Take() (*model.AlertRule, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertRule), nil
	}
}

func (a alertRuleDo) Last() (*model.AlertRule, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertRule), nil
	}
}

func (a alertRuleDo) Find() ([]*model.AlertRule, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertRule), err
}

func (a alertRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertRule, err error) {
	buf := make([]*model.AlertRule, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertRuleDo) FindInBatches(result *[]*model.AlertRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertRuleDo) Attrs(attrs ...field.AssignExpr) IAlertRuleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertRuleDo) Assign(attrs ...field.AssignExpr) IAlertRuleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertRuleDo) Joins(fields ...field.RelationField) IAlertRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertRuleDo) Preload(fields ...field.RelationField) IAlertRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertRuleDo) FirstOrInit() (*model.AlertRule, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertRule), nil
	}
}

func (a alertRuleDo) FirstOrCreate() (*model.AlertRule, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertRule), nil
	}
}

func (a alertRuleDo) FindByPage(offset int, limit int) (result []*model.AlertRule, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertRuleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertRuleDo) Delete(models ...*model.AlertRule) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertRuleDo) withDO(do gen.Dao) *alertRuleDo {
	a.DO = *do.(*gen.DO)
	return a
}
