// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newAlertInstance(db *gorm.DB, opts ...gen.DOOption) alertInstance {
	_alertInstance := alertInstance{}

	_alertInstance.alertInstanceDo.UseDB(db, opts...)
	_alertInstance.alertInstanceDo.UseModel(&model.AlertInstance{})

	tableName := _alertInstance.alertInstanceDo.TableName()
	_alertInstance.ALL = field.NewAsterisk(tableName)
	_alertInstance.RuleID = field.NewString(tableName, "rule_id")
	_alertInstance.GroupKey = field.NewString(tableName, "group_key")
	_alertInstance.LabelsJSON = field.NewString(tableName, "labels_json")
	_alertInstance.State = field.NewString(tableName, "state")
	_alertInstance.Value = field.NewFloat64(tableName, "value")
	_alertInstance.FirstPendingAt = field.NewInt64(tableName, "first_pending_at")
	_alertInstance.FiredAt = field.NewInt64(tableName, "fired_at")
	_alertInstance.ResolvedAt = field.NewInt64(tableName, "resolved_at")
	_alertInstance.AcknowledgedAt = field.NewInt64(tableName, "acknowledged_at")
	_alertInstance.AcknowledgementNote = field.NewString(tableName, "acknowledgement_note")
	_alertInstance.LastEvaluatedAt = field.NewInt64(tableName, "last_evaluated_at")
	_alertInstance.LastError = field.NewString(tableName, "last_error")
	_alertInstance.LastNotifiedAt = field.NewInt64(tableName, "last_notified_at")
	_alertInstance.LastBrowserNotifiedAt = field.NewInt64(tableName, "last_browser_notified_at")
	_alertInstance.LastPushoverNotifiedAt = field.NewInt64(tableName, "last_pushover_notified_at")

	_alertInstance.fillFieldMap()

	return _alertInstance
}

type alertInstance struct {
	alertInstanceDo

	ALL                    field.Asterisk
	RuleID                 field.String
	GroupKey               field.String
	LabelsJSON             field.String
	State                  field.String
	Value                  field.Float64
	FirstPendingAt         field.Int64
	FiredAt                field.Int64
	ResolvedAt             field.Int64
	AcknowledgedAt         field.Int64
	AcknowledgementNote    field.String
	LastEvaluatedAt        field.Int64
	LastError              field.String
	LastNotifiedAt         field.Int64
	LastBrowserNotifiedAt  field.Int64
	LastPushoverNotifiedAt field.Int64

	fieldMap map[string]field.Expr
}

func (a alertInstance) Table(newTableName string) *alertInstance {
	a.alertInstanceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertInstance) As(alias string) *alertInstance {
	a.alertInstanceDo.DO = *(a.alertInstanceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertInstance) updateTableName(table string) *alertInstance {
	a.ALL = field.NewAsterisk(table)
	a.RuleID = field.NewString(table, "rule_id")
	a.GroupKey = field.NewString(table, "group_key")
	a.LabelsJSON = field.NewString(table, "labels_json")
	a.State = field.NewString(table, "state")
	a.Value = field.NewFloat64(table, "value")
	a.FirstPendingAt = field.NewInt64(table, "first_pending_at")
	a.FiredAt = field.NewInt64(table, "fired_at")
	a.ResolvedAt = field.NewInt64(table, "resolved_at")
	a.AcknowledgedAt = field.NewInt64(table, "acknowledged_at")
	a.AcknowledgementNote = field.NewString(table, "acknowledgement_note")
	a.LastEvaluatedAt = field.NewInt64(table, "last_evaluated_at")
	a.LastError = field.NewString(table, "last_error")
	a.LastNotifiedAt = field.NewInt64(table, "last_notified_at")
	a.LastBrowserNotifiedAt = field.NewInt64(table, "last_browser_notified_at")
	a.LastPushoverNotifiedAt = field.NewInt64(table, "last_pushover_notified_at")

	a.fillFieldMap()

	return a
}

func (a *alertInstance) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertInstance) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 15)
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["group_key"] = a.GroupKey
	a.fieldMap["labels_json"] = a.LabelsJSON
	a.fieldMap["state"] = a.State
	a.fieldMap["value"] = a.Value
	a.fieldMap["first_pending_at"] = a.FirstPendingAt
	a.fieldMap["fired_at"] = a.FiredAt
	a.fieldMap["resolved_at"] = a.ResolvedAt
	a.fieldMap["acknowledged_at"] = a.AcknowledgedAt
	a.fieldMap["acknowledgement_note"] = a.AcknowledgementNote
	a.fieldMap["last_evaluated_at"] = a.LastEvaluatedAt
	a.fieldMap["last_error"] = a.LastError
	a.fieldMap["last_notified_at"] = a.LastNotifiedAt
	a.fieldMap["last_browser_notified_at"] = a.LastBrowserNotifiedAt
	a.fieldMap["last_pushover_notified_at"] = a.LastPushoverNotifiedAt
}

func (a alertInstance) clone(db *gorm.DB) alertInstance {
	a.alertInstanceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertInstance) replaceDB(db *gorm.DB) alertInstance {
	a.alertInstanceDo.ReplaceDB(db)
	return a
}

type alertInstanceDo struct{ gen.DO }

type IAlertInstanceDo interface {
	gen.SubQuery
	Debug() IAlertInstanceDo
	WithContext(ctx context.Context) IAlertInstanceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAlertInstanceDo
	WriteDB() IAlertInstanceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAlertInstanceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAlertInstanceDo
	Not(conds ...gen.Condition) IAlertInstanceDo
	Or(conds ...gen.Condition) IAlertInstanceDo
	Select(conds ...field.Expr) IAlertInstanceDo
	Where(conds ...gen.Condition) IAlertInstanceDo
	Order(conds ...field.Expr) IAlertInstanceDo
	Distinct(cols ...field.Expr) IAlertInstanceDo
	Omit(cols ...field.Expr) IAlertInstanceDo
	Join(table schema.Tabler, on ...field.Expr) IAlertInstanceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceDo
	Group(cols ...field.Expr) IAlertInstanceDo
	Having(conds ...gen.Condition) IAlertInstanceDo
	Limit(limit int) IAlertInstanceDo
	Offset(offset int) IAlertInstanceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertInstanceDo
	Unscoped() IAlertInstanceDo
	Create(values ...*model.AlertInstance) error
	CreateInBatches(values []*model.AlertInstance, batchSize int) error
	Save(values ...*model.AlertInstance) error
	First() (*model.AlertInstance, error)
	Take() (*model.AlertInstance, error)
	Last() (*model.AlertInstance, error)
	Find() ([]*model.AlertInstance, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertInstance, err error)
	FindInBatches(result *[]*model.AlertInstance, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AlertInstance) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAlertInstanceDo
	Assign(attrs ...field.AssignExpr) IAlertInstanceDo
	Joins(fields ...field.RelationField) IAlertInstanceDo
	Preload(fields ...field.RelationField) IAlertInstanceDo
	FirstOrInit() (*model.AlertInstance, error)
	FirstOrCreate() (*model.AlertInstance, error)
	FindByPage(offset int, limit int) (result []*model.AlertInstance, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAlertInstanceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a alertInstanceDo) Debug() IAlertInstanceDo {
	return a.withDO(a.DO.Debug())
}

func (a alertInstanceDo) WithContext(ctx context.Context) IAlertInstanceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertInstanceDo) ReadDB() IAlertInstanceDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertInstanceDo) WriteDB() IAlertInstanceDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertInstanceDo) Session(config *gorm.Session) IAlertInstanceDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertInstanceDo) Clauses(conds ...clause.Expression) IAlertInstanceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertInstanceDo) Returning(value interface{}, columns ...string) IAlertInstanceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertInstanceDo) Not(conds ...gen.Condition) IAlertInstanceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertInstanceDo) Or(conds ...gen.Condition) IAlertInstanceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertInstanceDo) Select(conds ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertInstanceDo) Where(conds ...gen.Condition) IAlertInstanceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertInstanceDo) Order(conds ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertInstanceDo) Distinct(cols ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertInstanceDo) Omit(cols ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertInstanceDo) Join(table schema.Tabler, on ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertInstanceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertInstanceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertInstanceDo) Group(cols ...field.Expr) IAlertInstanceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertInstanceDo) Having(conds ...gen.Condition) IAlertInstanceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertInstanceDo) Limit(limit int) IAlertInstanceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertInstanceDo) Offset(offset int) IAlertInstanceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertInstanceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAlertInstanceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertInstanceDo) Unscoped() IAlertInstanceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertInstanceDo) Create(values ...*model.AlertInstance) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertInstanceDo) CreateInBatches(values []*model.AlertInstance, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertInstanceDo) Save(values ...*model.AlertInstance) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertInstanceDo) First() (*model.AlertInstance, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstance), nil
	}
}

func (a alertInstanceDo) Take() (*model.AlertInstance, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstance), nil
	}
}

func (a alertInstanceDo) Last() (*model.AlertInstance, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstance), nil
	}
}

func (a alertInstanceDo) Find() ([]*model.AlertInstance, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertInstance), err
}

func (a alertInstanceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertInstance, err error) {
	buf := make([]*model.AlertInstance, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertInstanceDo) FindInBatches(result *[]*model.AlertInstance, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertInstanceDo) Attrs(attrs ...field.AssignExpr) IAlertInstanceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertInstanceDo) Assign(attrs ...field.AssignExpr) IAlertInstanceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertInstanceDo) Joins(fields ...field.RelationField) IAlertInstanceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertInstanceDo) Preload(fields ...field.RelationField) IAlertInstanceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertInstanceDo) FirstOrInit() (*model.AlertInstance, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstance), nil
	}
}

func (a alertInstanceDo) FirstOrCreate() (*model.AlertInstance, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertInstance), nil
	}
}

func (a alertInstanceDo) FindByPage(offset int, limit int) (result []*model.AlertInstance, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertInstanceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertInstanceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertInstanceDo) Delete(models ...*model.AlertInstance) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertInstanceDo) withDO(do gen.Dao) *alertInstanceDo {
	a.DO = *do.(*gen.DO)
	return a
}
