// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newCoverageSpec(db *gorm.DB, opts ...gen.DOOption) coverageSpec {
	_coverageSpec := coverageSpec{}

	_coverageSpec.coverageSpecDo.UseDB(db, opts...)
	_coverageSpec.coverageSpecDo.UseModel(&model.CoverageSpec{})

	tableName := _coverageSpec.coverageSpecDo.TableName()
	_coverageSpec.ALL = field.NewAsterisk(tableName)
	_coverageSpec.ID = field.NewString(tableName, "id")
	_coverageSpec.Name = field.NewString(tableName, "name")
	_coverageSpec.ServiceName = field.NewString(tableName, "service_name")
	_coverageSpec.Format = field.NewString(tableName, "format")
	_coverageSpec.SourceURL = field.NewString(tableName, "source_url")
	_coverageSpec.Content = field.NewString(tableName, "content")
	_coverageSpec.Digest = field.NewString(tableName, "digest")
	_coverageSpec.RouteCount = field.NewInt(tableName, "route_count")
	_coverageSpec.Enabled = field.NewBool(tableName, "enabled")
	_coverageSpec.CreatedAt = field.NewInt64(tableName, "created_at")
	_coverageSpec.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_coverageSpec.fillFieldMap()

	return _coverageSpec
}

type coverageSpec struct {
	coverageSpecDo

	ALL         field.Asterisk
	ID          field.String
	Name        field.String
	ServiceName field.String
	Format      field.String
	SourceURL   field.String
	Content     field.String
	Digest      field.String
	RouteCount  field.Int
	Enabled     field.Bool
	CreatedAt   field.Int64
	UpdatedAt   field.Int64

	fieldMap map[string]field.Expr
}

func (c coverageSpec) Table(newTableName string) *coverageSpec {
	c.coverageSpecDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coverageSpec) As(alias string) *coverageSpec {
	c.coverageSpecDo.DO = *(c.coverageSpecDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coverageSpec) updateTableName(table string) *coverageSpec {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Name = field.NewString(table, "name")
	c.ServiceName = field.NewString(table, "service_name")
	c.Format = field.NewString(table, "format")
	c.SourceURL = field.NewString(table, "source_url")
	c.Content = field.NewString(table, "content")
	c.Digest = field.NewString(table, "digest")
	c.RouteCount = field.NewInt(table, "route_count")
	c.Enabled = field.NewBool(table, "enabled")
	c.CreatedAt = field.NewInt64(table, "created_at")
	c.UpdatedAt = field.NewInt64(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *coverageSpec) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coverageSpec) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["service_name"] = c.ServiceName
	c.fieldMap["format"] = c.Format
	c.fieldMap["source_url"] = c.SourceURL
	c.fieldMap["content"] = c.Content
	c.fieldMap["digest"] = c.Digest
	c.fieldMap["route_count"] = c.RouteCount
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c coverageSpec) clone(db *gorm.DB) coverageSpec {
	c.coverageSpecDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c coverageSpec) replaceDB(db *gorm.DB) coverageSpec {
	c.coverageSpecDo.ReplaceDB(db)
	return c
}

type coverageSpecDo struct{ gen.DO }

type ICoverageSpecDo interface {
	gen.SubQuery
	Debug() ICoverageSpecDo
	WithContext(ctx context.Context) ICoverageSpecDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICoverageSpecDo
	WriteDB() ICoverageSpecDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICoverageSpecDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICoverageSpecDo
	Not(conds ...gen.Condition) ICoverageSpecDo
	Or(conds ...gen.Condition) ICoverageSpecDo
	Select(conds ...field.Expr) ICoverageSpecDo
	Where(conds ...gen.Condition) ICoverageSpecDo
	Order(conds ...field.Expr) ICoverageSpecDo
	Distinct(cols ...field.Expr) ICoverageSpecDo
	Omit(cols ...field.Expr) ICoverageSpecDo
	Join(table schema.Tabler, on ...field.Expr) ICoverageSpecDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICoverageSpecDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICoverageSpecDo
	Group(cols ...field.Expr) ICoverageSpecDo
	Having(conds ...gen.Condition) ICoverageSpecDo
	Limit(limit int) ICoverageSpecDo
	Offset(offset int) ICoverageSpecDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICoverageSpecDo
	Unscoped() ICoverageSpecDo
	Create(values ...*model.CoverageSpec) error
	CreateInBatches(values []*model.CoverageSpec, batchSize int) error
	Save(values ...*model.CoverageSpec) error
	First() (*model.CoverageSpec, error)
	Take() (*model.CoverageSpec, error)
	Last() (*model.CoverageSpec, error)
	Find() ([]*model.CoverageSpec, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CoverageSpec, err error)
	FindInBatches(result *[]*model.CoverageSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CoverageSpec) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICoverageSpecDo
	Assign(attrs ...field.AssignExpr) ICoverageSpecDo
	Joins(fields ...field.RelationField) ICoverageSpecDo
	Preload(fields ...field.RelationField) ICoverageSpecDo
	FirstOrInit() (*model.CoverageSpec, error)
	FirstOrCreate() (*model.CoverageSpec, error)
	FindByPage(offset int, limit int) (result []*model.CoverageSpec, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICoverageSpecDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c coverageSpecDo) Debug() ICoverageSpecDo {
	return c.withDO(c.DO.Debug())
}

func (c coverageSpecDo) WithContext(ctx context.Context) ICoverageSpecDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coverageSpecDo) ReadDB() ICoverageSpecDo {
	return c.Clauses(dbresolver.Read)
}

func (c coverageSpecDo) WriteDB() ICoverageSpecDo {
	return c.Clauses(dbresolver.Write)
}

func (c coverageSpecDo) Session(config *gorm.Session) ICoverageSpecDo {
	return c.withDO(c.DO.Session(config))
}

func (c coverageSpecDo) Clauses(conds ...clause.Expression) ICoverageSpecDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coverageSpecDo) Returning(value interface{}, columns ...string) ICoverageSpecDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coverageSpecDo) Not(conds ...gen.Condition) ICoverageSpecDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coverageSpecDo) Or(conds ...gen.Condition) ICoverageSpecDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coverageSpecDo) Select(conds ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coverageSpecDo) Where(conds ...gen.Condition) ICoverageSpecDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coverageSpecDo) Order(conds ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coverageSpecDo) Distinct(cols ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coverageSpecDo) Omit(cols ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coverageSpecDo) Join(table schema.Tabler, on ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coverageSpecDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coverageSpecDo) RightJoin(table schema.Tabler, on ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coverageSpecDo) Group(cols ...field.Expr) ICoverageSpecDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coverageSpecDo) Having(conds ...gen.Condition) ICoverageSpecDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coverageSpecDo) Limit(limit int) ICoverageSpecDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coverageSpecDo) Offset(offset int) ICoverageSpecDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coverageSpecDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICoverageSpecDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coverageSpecDo) Unscoped() ICoverageSpecDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coverageSpecDo) Create(values ...*model.CoverageSpec) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coverageSpecDo) CreateInBatches(values []*model.CoverageSpec, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coverageSpecDo) Save(values ...*model.CoverageSpec) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coverageSpecDo) First() (*model.CoverageSpec, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverageSpec), nil
	}
}

func (c coverageSpecDo) Take() (*model.CoverageSpec, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverageSpec), nil
	}
}

func (c coverageSpecDo) Last() (*model.CoverageSpec, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverageSpec), nil
	}
}

func (c coverageSpecDo) Find() ([]*model.CoverageSpec, error) {
	result, err := c.DO.Find()
	return result.([]*model.CoverageSpec), err
}

func (c coverageSpecDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CoverageSpec, err error) {
	buf := make([]*model.CoverageSpec, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coverageSpecDo) FindInBatches(result *[]*model.CoverageSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coverageSpecDo) Attrs(attrs ...field.AssignExpr) ICoverageSpecDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coverageSpecDo) Assign(attrs ...field.AssignExpr) ICoverageSpecDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coverageSpecDo) Joins(fields ...field.RelationField) ICoverageSpecDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coverageSpecDo) Preload(fields ...field.RelationField) ICoverageSpecDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coverageSpecDo) FirstOrInit() (*model.CoverageSpec, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverageSpec), nil
	}
}

func (c coverageSpecDo) FirstOrCreate() (*model.CoverageSpec, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverageSpec), nil
	}
}

func (c coverageSpecDo) FindByPage(offset int, limit int) (result []*model.CoverageSpec, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coverageSpecDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coverageSpecDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coverageSpecDo) Delete(models ...*model.CoverageSpec) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coverageSpecDo) withDO(do gen.Dao) *coverageSpecDo {
	c.DO = *do.(*gen.DO)
	return c
}
