// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newDashboardVariable(db *gorm.DB, opts ...gen.DOOption) dashboardVariable {
	_dashboardVariable := dashboardVariable{}

	_dashboardVariable.dashboardVariableDo.UseDB(db, opts...)
	_dashboardVariable.dashboardVariableDo.UseModel(&model.DashboardVariable{})

	tableName := _dashboardVariable.dashboardVariableDo.TableName()
	_dashboardVariable.ALL = field.NewAsterisk(tableName)
	_dashboardVariable.DashboardID = field.NewString(tableName, "dashboard_id")
	_dashboardVariable.Name = field.NewString(tableName, "name")
	_dashboardVariable.Kind = field.NewString(tableName, "kind")
	_dashboardVariable.Source = field.NewString(tableName, "source")
	_dashboardVariable.OptionsJSON = field.NewString(tableName, "options_json")
	_dashboardVariable.DefaultValue = field.NewString(tableName, "default_value")

	_dashboardVariable.fillFieldMap()

	return _dashboardVariable
}

type dashboardVariable struct {
	dashboardVariableDo

	ALL          field.Asterisk
	DashboardID  field.String
	Name         field.String
	Kind         field.String
	Source       field.String
	OptionsJSON  field.String
	DefaultValue field.String

	fieldMap map[string]field.Expr
}

func (d dashboardVariable) Table(newTableName string) *dashboardVariable {
	d.dashboardVariableDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dashboardVariable) As(alias string) *dashboardVariable {
	d.dashboardVariableDo.DO = *(d.dashboardVariableDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dashboardVariable) updateTableName(table string) *dashboardVariable {
	d.ALL = field.NewAsterisk(table)
	d.DashboardID = field.NewString(table, "dashboard_id")
	d.Name = field.NewString(table, "name")
	d.Kind = field.NewString(table, "kind")
	d.Source = field.NewString(table, "source")
	d.OptionsJSON = field.NewString(table, "options_json")
	d.DefaultValue = field.NewString(table, "default_value")

	d.fillFieldMap()

	return d
}

func (d *dashboardVariable) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dashboardVariable) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 6)
	d.fieldMap["dashboard_id"] = d.DashboardID
	d.fieldMap["name"] = d.Name
	d.fieldMap["kind"] = d.Kind
	d.fieldMap["source"] = d.Source
	d.fieldMap["options_json"] = d.OptionsJSON
	d.fieldMap["default_value"] = d.DefaultValue
}

func (d dashboardVariable) clone(db *gorm.DB) dashboardVariable {
	d.dashboardVariableDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dashboardVariable) replaceDB(db *gorm.DB) dashboardVariable {
	d.dashboardVariableDo.ReplaceDB(db)
	return d
}

type dashboardVariableDo struct{ gen.DO }

type IDashboardVariableDo interface {
	gen.SubQuery
	Debug() IDashboardVariableDo
	WithContext(ctx context.Context) IDashboardVariableDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDashboardVariableDo
	WriteDB() IDashboardVariableDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDashboardVariableDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDashboardVariableDo
	Not(conds ...gen.Condition) IDashboardVariableDo
	Or(conds ...gen.Condition) IDashboardVariableDo
	Select(conds ...field.Expr) IDashboardVariableDo
	Where(conds ...gen.Condition) IDashboardVariableDo
	Order(conds ...field.Expr) IDashboardVariableDo
	Distinct(cols ...field.Expr) IDashboardVariableDo
	Omit(cols ...field.Expr) IDashboardVariableDo
	Join(table schema.Tabler, on ...field.Expr) IDashboardVariableDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDashboardVariableDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDashboardVariableDo
	Group(cols ...field.Expr) IDashboardVariableDo
	Having(conds ...gen.Condition) IDashboardVariableDo
	Limit(limit int) IDashboardVariableDo
	Offset(offset int) IDashboardVariableDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDashboardVariableDo
	Unscoped() IDashboardVariableDo
	Create(values ...*model.DashboardVariable) error
	CreateInBatches(values []*model.DashboardVariable, batchSize int) error
	Save(values ...*model.DashboardVariable) error
	First() (*model.DashboardVariable, error)
	Take() (*model.DashboardVariable, error)
	Last() (*model.DashboardVariable, error)
	Find() ([]*model.DashboardVariable, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DashboardVariable, err error)
	FindInBatches(result *[]*model.DashboardVariable, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DashboardVariable) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDashboardVariableDo
	Assign(attrs ...field.AssignExpr) IDashboardVariableDo
	Joins(fields ...field.RelationField) IDashboardVariableDo
	Preload(fields ...field.RelationField) IDashboardVariableDo
	FirstOrInit() (*model.DashboardVariable, error)
	FirstOrCreate() (*model.DashboardVariable, error)
	FindByPage(offset int, limit int) (result []*model.DashboardVariable, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDashboardVariableDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dashboardVariableDo) Debug() IDashboardVariableDo {
	return d.withDO(d.DO.Debug())
}

func (d dashboardVariableDo) WithContext(ctx context.Context) IDashboardVariableDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dashboardVariableDo) ReadDB() IDashboardVariableDo {
	return d.Clauses(dbresolver.Read)
}

func (d dashboardVariableDo) WriteDB() IDashboardVariableDo {
	return d.Clauses(dbresolver.Write)
}

func (d dashboardVariableDo) Session(config *gorm.Session) IDashboardVariableDo {
	return d.withDO(d.DO.Session(config))
}

func (d dashboardVariableDo) Clauses(conds ...clause.Expression) IDashboardVariableDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dashboardVariableDo) Returning(value interface{}, columns ...string) IDashboardVariableDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dashboardVariableDo) Not(conds ...gen.Condition) IDashboardVariableDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dashboardVariableDo) Or(conds ...gen.Condition) IDashboardVariableDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dashboardVariableDo) Select(conds ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dashboardVariableDo) Where(conds ...gen.Condition) IDashboardVariableDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dashboardVariableDo) Order(conds ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dashboardVariableDo) Distinct(cols ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dashboardVariableDo) Omit(cols ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dashboardVariableDo) Join(table schema.Tabler, on ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dashboardVariableDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dashboardVariableDo) RightJoin(table schema.Tabler, on ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dashboardVariableDo) Group(cols ...field.Expr) IDashboardVariableDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dashboardVariableDo) Having(conds ...gen.Condition) IDashboardVariableDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dashboardVariableDo) Limit(limit int) IDashboardVariableDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dashboardVariableDo) Offset(offset int) IDashboardVariableDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dashboardVariableDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDashboardVariableDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dashboardVariableDo) Unscoped() IDashboardVariableDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dashboardVariableDo) Create(values ...*model.DashboardVariable) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dashboardVariableDo) CreateInBatches(values []*model.DashboardVariable, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dashboardVariableDo) Save(values ...*model.DashboardVariable) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dashboardVariableDo) First() (*model.DashboardVariable, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardVariable), nil
	}
}

func (d dashboardVariableDo) Take() (*model.DashboardVariable, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardVariable), nil
	}
}

func (d dashboardVariableDo) Last() (*model.DashboardVariable, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardVariable), nil
	}
}

func (d dashboardVariableDo) Find() ([]*model.DashboardVariable, error) {
	result, err := d.DO.Find()
	return result.([]*model.DashboardVariable), err
}

func (d dashboardVariableDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DashboardVariable, err error) {
	buf := make([]*model.DashboardVariable, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dashboardVariableDo) FindInBatches(result *[]*model.DashboardVariable, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dashboardVariableDo) Attrs(attrs ...field.AssignExpr) IDashboardVariableDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dashboardVariableDo) Assign(attrs ...field.AssignExpr) IDashboardVariableDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dashboardVariableDo) Joins(fields ...field.RelationField) IDashboardVariableDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dashboardVariableDo) Preload(fields ...field.RelationField) IDashboardVariableDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dashboardVariableDo) FirstOrInit() (*model.DashboardVariable, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardVariable), nil
	}
}

func (d dashboardVariableDo) FirstOrCreate() (*model.DashboardVariable, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardVariable), nil
	}
}

func (d dashboardVariableDo) FindByPage(offset int, limit int) (result []*model.DashboardVariable, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dashboardVariableDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dashboardVariableDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dashboardVariableDo) Delete(models ...*model.DashboardVariable) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dashboardVariableDo) withDO(do gen.Dao) *dashboardVariableDo {
	d.DO = *do.(*gen.DO)
	return d
}
