// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newDashboardPanel(db *gorm.DB, opts ...gen.DOOption) dashboardPanel {
	_dashboardPanel := dashboardPanel{}

	_dashboardPanel.dashboardPanelDo.UseDB(db, opts...)
	_dashboardPanel.dashboardPanelDo.UseModel(&model.DashboardPanel{})

	tableName := _dashboardPanel.dashboardPanelDo.TableName()
	_dashboardPanel.ALL = field.NewAsterisk(tableName)
	_dashboardPanel.ID = field.NewString(tableName, "id")
	_dashboardPanel.DashboardID = field.NewString(tableName, "dashboard_id")
	_dashboardPanel.Title = field.NewString(tableName, "title")
	_dashboardPanel.DisplayType = field.NewString(tableName, "display_type")
	_dashboardPanel.QuerySQL = field.NewString(tableName, "query_sql")
	_dashboardPanel.QueryVersion = field.NewInt(tableName, "query_version")
	_dashboardPanel.SettingsJSON = field.NewString(tableName, "settings_json")
	_dashboardPanel.LayoutJSON = field.NewString(tableName, "layout_json")
	_dashboardPanel.Position = field.NewInt(tableName, "position")
	_dashboardPanel.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_dashboardPanel.fillFieldMap()

	return _dashboardPanel
}

type dashboardPanel struct {
	dashboardPanelDo

	ALL          field.Asterisk
	ID           field.String
	DashboardID  field.String
	Title        field.String
	DisplayType  field.String
	QuerySQL     field.String
	QueryVersion field.Int
	SettingsJSON field.String
	LayoutJSON   field.String
	Position     field.Int
	UpdatedAt    field.Int64

	fieldMap map[string]field.Expr
}

func (d dashboardPanel) Table(newTableName string) *dashboardPanel {
	d.dashboardPanelDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dashboardPanel) As(alias string) *dashboardPanel {
	d.dashboardPanelDo.DO = *(d.dashboardPanelDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dashboardPanel) updateTableName(table string) *dashboardPanel {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.DashboardID = field.NewString(table, "dashboard_id")
	d.Title = field.NewString(table, "title")
	d.DisplayType = field.NewString(table, "display_type")
	d.QuerySQL = field.NewString(table, "query_sql")
	d.QueryVersion = field.NewInt(table, "query_version")
	d.SettingsJSON = field.NewString(table, "settings_json")
	d.LayoutJSON = field.NewString(table, "layout_json")
	d.Position = field.NewInt(table, "position")
	d.UpdatedAt = field.NewInt64(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dashboardPanel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dashboardPanel) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["dashboard_id"] = d.DashboardID
	d.fieldMap["title"] = d.Title
	d.fieldMap["display_type"] = d.DisplayType
	d.fieldMap["query_sql"] = d.QuerySQL
	d.fieldMap["query_version"] = d.QueryVersion
	d.fieldMap["settings_json"] = d.SettingsJSON
	d.fieldMap["layout_json"] = d.LayoutJSON
	d.fieldMap["position"] = d.Position
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dashboardPanel) clone(db *gorm.DB) dashboardPanel {
	d.dashboardPanelDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dashboardPanel) replaceDB(db *gorm.DB) dashboardPanel {
	d.dashboardPanelDo.ReplaceDB(db)
	return d
}

type dashboardPanelDo struct{ gen.DO }

type IDashboardPanelDo interface {
	gen.SubQuery
	Debug() IDashboardPanelDo
	WithContext(ctx context.Context) IDashboardPanelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDashboardPanelDo
	WriteDB() IDashboardPanelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDashboardPanelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDashboardPanelDo
	Not(conds ...gen.Condition) IDashboardPanelDo
	Or(conds ...gen.Condition) IDashboardPanelDo
	Select(conds ...field.Expr) IDashboardPanelDo
	Where(conds ...gen.Condition) IDashboardPanelDo
	Order(conds ...field.Expr) IDashboardPanelDo
	Distinct(cols ...field.Expr) IDashboardPanelDo
	Omit(cols ...field.Expr) IDashboardPanelDo
	Join(table schema.Tabler, on ...field.Expr) IDashboardPanelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDashboardPanelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDashboardPanelDo
	Group(cols ...field.Expr) IDashboardPanelDo
	Having(conds ...gen.Condition) IDashboardPanelDo
	Limit(limit int) IDashboardPanelDo
	Offset(offset int) IDashboardPanelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDashboardPanelDo
	Unscoped() IDashboardPanelDo
	Create(values ...*model.DashboardPanel) error
	CreateInBatches(values []*model.DashboardPanel, batchSize int) error
	Save(values ...*model.DashboardPanel) error
	First() (*model.DashboardPanel, error)
	Take() (*model.DashboardPanel, error)
	Last() (*model.DashboardPanel, error)
	Find() ([]*model.DashboardPanel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DashboardPanel, err error)
	FindInBatches(result *[]*model.DashboardPanel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DashboardPanel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDashboardPanelDo
	Assign(attrs ...field.AssignExpr) IDashboardPanelDo
	Joins(fields ...field.RelationField) IDashboardPanelDo
	Preload(fields ...field.RelationField) IDashboardPanelDo
	FirstOrInit() (*model.DashboardPanel, error)
	FirstOrCreate() (*model.DashboardPanel, error)
	FindByPage(offset int, limit int) (result []*model.DashboardPanel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDashboardPanelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dashboardPanelDo) Debug() IDashboardPanelDo {
	return d.withDO(d.DO.Debug())
}

func (d dashboardPanelDo) WithContext(ctx context.Context) IDashboardPanelDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dashboardPanelDo) ReadDB() IDashboardPanelDo {
	return d.Clauses(dbresolver.Read)
}

func (d dashboardPanelDo) WriteDB() IDashboardPanelDo {
	return d.Clauses(dbresolver.Write)
}

func (d dashboardPanelDo) Session(config *gorm.Session) IDashboardPanelDo {
	return d.withDO(d.DO.Session(config))
}

func (d dashboardPanelDo) Clauses(conds ...clause.Expression) IDashboardPanelDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dashboardPanelDo) Returning(value interface{}, columns ...string) IDashboardPanelDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dashboardPanelDo) Not(conds ...gen.Condition) IDashboardPanelDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dashboardPanelDo) Or(conds ...gen.Condition) IDashboardPanelDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dashboardPanelDo) Select(conds ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dashboardPanelDo) Where(conds ...gen.Condition) IDashboardPanelDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dashboardPanelDo) Order(conds ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dashboardPanelDo) Distinct(cols ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dashboardPanelDo) Omit(cols ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dashboardPanelDo) Join(table schema.Tabler, on ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dashboardPanelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dashboardPanelDo) RightJoin(table schema.Tabler, on ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dashboardPanelDo) Group(cols ...field.Expr) IDashboardPanelDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dashboardPanelDo) Having(conds ...gen.Condition) IDashboardPanelDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dashboardPanelDo) Limit(limit int) IDashboardPanelDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dashboardPanelDo) Offset(offset int) IDashboardPanelDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dashboardPanelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDashboardPanelDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dashboardPanelDo) Unscoped() IDashboardPanelDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dashboardPanelDo) Create(values ...*model.DashboardPanel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dashboardPanelDo) CreateInBatches(values []*model.DashboardPanel, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dashboardPanelDo) Save(values ...*model.DashboardPanel) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dashboardPanelDo) First() (*model.DashboardPanel, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardPanel), nil
	}
}

func (d dashboardPanelDo) Take() (*model.DashboardPanel, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardPanel), nil
	}
}

func (d dashboardPanelDo) Last() (*model.DashboardPanel, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardPanel), nil
	}
}

func (d dashboardPanelDo) Find() ([]*model.DashboardPanel, error) {
	result, err := d.DO.Find()
	return result.([]*model.DashboardPanel), err
}

func (d dashboardPanelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DashboardPanel, err error) {
	buf := make([]*model.DashboardPanel, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dashboardPanelDo) FindInBatches(result *[]*model.DashboardPanel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dashboardPanelDo) Attrs(attrs ...field.AssignExpr) IDashboardPanelDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dashboardPanelDo) Assign(attrs ...field.AssignExpr) IDashboardPanelDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dashboardPanelDo) Joins(fields ...field.RelationField) IDashboardPanelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dashboardPanelDo) Preload(fields ...field.RelationField) IDashboardPanelDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dashboardPanelDo) FirstOrInit() (*model.DashboardPanel, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardPanel), nil
	}
}

func (d dashboardPanelDo) FirstOrCreate() (*model.DashboardPanel, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardPanel), nil
	}
}

func (d dashboardPanelDo) FindByPage(offset int, limit int) (result []*model.DashboardPanel, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dashboardPanelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dashboardPanelDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dashboardPanelDo) Delete(models ...*model.DashboardPanel) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dashboardPanelDo) withDO(do gen.Dao) *dashboardPanelDo {
	d.DO = *do.(*gen.DO)
	return d
}
