// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	AlertInstance     *alertInstance
	AlertRule         *alertRule
	Dashboard         *dashboard
	DashboardPanel    *dashboardPanel
	DashboardVariable *dashboardVariable
	LintWarning       *lintWarning
	Log               *log
	Meta              *meta
	Metric            *metric
	Session           *session
	Span              *span
	SpanEvent         *spanEvent
	SpanLink          *spanLink
	TraceIssue        *traceIssue
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AlertInstance = &Q.AlertInstance
	AlertRule = &Q.AlertRule
	Dashboard = &Q.Dashboard
	DashboardPanel = &Q.DashboardPanel
	DashboardVariable = &Q.DashboardVariable
	LintWarning = &Q.LintWarning
	Log = &Q.Log
	Meta = &Q.Meta
	Metric = &Q.Metric
	Session = &Q.Session
	Span = &Q.Span
	SpanEvent = &Q.SpanEvent
	SpanLink = &Q.SpanLink
	TraceIssue = &Q.TraceIssue
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		AlertInstance:     newAlertInstance(db, opts...),
		AlertRule:         newAlertRule(db, opts...),
		Dashboard:         newDashboard(db, opts...),
		DashboardPanel:    newDashboardPanel(db, opts...),
		DashboardVariable: newDashboardVariable(db, opts...),
		LintWarning:       newLintWarning(db, opts...),
		Log:               newLog(db, opts...),
		Meta:              newMeta(db, opts...),
		Metric:            newMetric(db, opts...),
		Session:           newSession(db, opts...),
		Span:              newSpan(db, opts...),
		SpanEvent:         newSpanEvent(db, opts...),
		SpanLink:          newSpanLink(db, opts...),
		TraceIssue:        newTraceIssue(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AlertInstance     alertInstance
	AlertRule         alertRule
	Dashboard         dashboard
	DashboardPanel    dashboardPanel
	DashboardVariable dashboardVariable
	LintWarning       lintWarning
	Log               log
	Meta              meta
	Metric            metric
	Session           session
	Span              span
	SpanEvent         spanEvent
	SpanLink          spanLink
	TraceIssue        traceIssue
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AlertInstance:     q.AlertInstance.clone(db),
		AlertRule:         q.AlertRule.clone(db),
		Dashboard:         q.Dashboard.clone(db),
		DashboardPanel:    q.DashboardPanel.clone(db),
		DashboardVariable: q.DashboardVariable.clone(db),
		LintWarning:       q.LintWarning.clone(db),
		Log:               q.Log.clone(db),
		Meta:              q.Meta.clone(db),
		Metric:            q.Metric.clone(db),
		Session:           q.Session.clone(db),
		Span:              q.Span.clone(db),
		SpanEvent:         q.SpanEvent.clone(db),
		SpanLink:          q.SpanLink.clone(db),
		TraceIssue:        q.TraceIssue.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AlertInstance:     q.AlertInstance.replaceDB(db),
		AlertRule:         q.AlertRule.replaceDB(db),
		Dashboard:         q.Dashboard.replaceDB(db),
		DashboardPanel:    q.DashboardPanel.replaceDB(db),
		DashboardVariable: q.DashboardVariable.replaceDB(db),
		LintWarning:       q.LintWarning.replaceDB(db),
		Log:               q.Log.replaceDB(db),
		Meta:              q.Meta.replaceDB(db),
		Metric:            q.Metric.replaceDB(db),
		Session:           q.Session.replaceDB(db),
		Span:              q.Span.replaceDB(db),
		SpanEvent:         q.SpanEvent.replaceDB(db),
		SpanLink:          q.SpanLink.replaceDB(db),
		TraceIssue:        q.TraceIssue.replaceDB(db),
	}
}

type queryCtx struct {
	AlertInstance     IAlertInstanceDo
	AlertRule         IAlertRuleDo
	Dashboard         IDashboardDo
	DashboardPanel    IDashboardPanelDo
	DashboardVariable IDashboardVariableDo
	LintWarning       ILintWarningDo
	Log               ILogDo
	Meta              IMetaDo
	Metric            IMetricDo
	Session           ISessionDo
	Span              ISpanDo
	SpanEvent         ISpanEventDo
	SpanLink          ISpanLinkDo
	TraceIssue        ITraceIssueDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AlertInstance:     q.AlertInstance.WithContext(ctx),
		AlertRule:         q.AlertRule.WithContext(ctx),
		Dashboard:         q.Dashboard.WithContext(ctx),
		DashboardPanel:    q.DashboardPanel.WithContext(ctx),
		DashboardVariable: q.DashboardVariable.WithContext(ctx),
		LintWarning:       q.LintWarning.WithContext(ctx),
		Log:               q.Log.WithContext(ctx),
		Meta:              q.Meta.WithContext(ctx),
		Metric:            q.Metric.WithContext(ctx),
		Session:           q.Session.WithContext(ctx),
		Span:              q.Span.WithContext(ctx),
		SpanEvent:         q.SpanEvent.WithContext(ctx),
		SpanLink:          q.SpanLink.WithContext(ctx),
		TraceIssue:        q.TraceIssue.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
