// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newLintWarning(db *gorm.DB, opts ...gen.DOOption) lintWarning {
	_lintWarning := lintWarning{}

	_lintWarning.lintWarningDo.UseDB(db, opts...)
	_lintWarning.lintWarningDo.UseModel(&model.LintWarning{})

	tableName := _lintWarning.lintWarningDo.TableName()
	_lintWarning.ALL = field.NewAsterisk(tableName)
	_lintWarning.SpanID = field.NewString(tableName, "span_id")
	_lintWarning.TraceID = field.NewString(tableName, "trace_id")
	_lintWarning.SessionID = field.NewString(tableName, "session_id")
	_lintWarning.RuleID = field.NewString(tableName, "rule_id")
	_lintWarning.Message = field.NewString(tableName, "message")
	_lintWarning.Severity = field.NewString(tableName, "severity")
	_lintWarning.CreatedAt = field.NewInt64(tableName, "created_at")

	_lintWarning.fillFieldMap()

	return _lintWarning
}

type lintWarning struct {
	lintWarningDo

	ALL       field.Asterisk
	SpanID    field.String
	TraceID   field.String
	SessionID field.String
	RuleID    field.String
	Message   field.String
	Severity  field.String
	CreatedAt field.Int64

	fieldMap map[string]field.Expr
}

func (l lintWarning) Table(newTableName string) *lintWarning {
	l.lintWarningDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lintWarning) As(alias string) *lintWarning {
	l.lintWarningDo.DO = *(l.lintWarningDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lintWarning) updateTableName(table string) *lintWarning {
	l.ALL = field.NewAsterisk(table)
	l.SpanID = field.NewString(table, "span_id")
	l.TraceID = field.NewString(table, "trace_id")
	l.SessionID = field.NewString(table, "session_id")
	l.RuleID = field.NewString(table, "rule_id")
	l.Message = field.NewString(table, "message")
	l.Severity = field.NewString(table, "severity")
	l.CreatedAt = field.NewInt64(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *lintWarning) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lintWarning) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["span_id"] = l.SpanID
	l.fieldMap["trace_id"] = l.TraceID
	l.fieldMap["session_id"] = l.SessionID
	l.fieldMap["rule_id"] = l.RuleID
	l.fieldMap["message"] = l.Message
	l.fieldMap["severity"] = l.Severity
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l lintWarning) clone(db *gorm.DB) lintWarning {
	l.lintWarningDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lintWarning) replaceDB(db *gorm.DB) lintWarning {
	l.lintWarningDo.ReplaceDB(db)
	return l
}

type lintWarningDo struct{ gen.DO }

type ILintWarningDo interface {
	gen.SubQuery
	Debug() ILintWarningDo
	WithContext(ctx context.Context) ILintWarningDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILintWarningDo
	WriteDB() ILintWarningDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILintWarningDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILintWarningDo
	Not(conds ...gen.Condition) ILintWarningDo
	Or(conds ...gen.Condition) ILintWarningDo
	Select(conds ...field.Expr) ILintWarningDo
	Where(conds ...gen.Condition) ILintWarningDo
	Order(conds ...field.Expr) ILintWarningDo
	Distinct(cols ...field.Expr) ILintWarningDo
	Omit(cols ...field.Expr) ILintWarningDo
	Join(table schema.Tabler, on ...field.Expr) ILintWarningDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILintWarningDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILintWarningDo
	Group(cols ...field.Expr) ILintWarningDo
	Having(conds ...gen.Condition) ILintWarningDo
	Limit(limit int) ILintWarningDo
	Offset(offset int) ILintWarningDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILintWarningDo
	Unscoped() ILintWarningDo
	Create(values ...*model.LintWarning) error
	CreateInBatches(values []*model.LintWarning, batchSize int) error
	Save(values ...*model.LintWarning) error
	First() (*model.LintWarning, error)
	Take() (*model.LintWarning, error)
	Last() (*model.LintWarning, error)
	Find() ([]*model.LintWarning, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LintWarning, err error)
	FindInBatches(result *[]*model.LintWarning, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LintWarning) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILintWarningDo
	Assign(attrs ...field.AssignExpr) ILintWarningDo
	Joins(fields ...field.RelationField) ILintWarningDo
	Preload(fields ...field.RelationField) ILintWarningDo
	FirstOrInit() (*model.LintWarning, error)
	FirstOrCreate() (*model.LintWarning, error)
	FindByPage(offset int, limit int) (result []*model.LintWarning, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILintWarningDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	SearchByRule(sessionID string, pattern string, limit int) (result []model.LintSearchResult, err error)
	ListWithTraceIssues(sessionID string) (result []model.LintWarning, err error)
}

// SearchByRule
//
// SELECT lw.trace_id, COALESCE(MIN(s.name), '(trace)') AS title, MIN(lw.rule_id) AS rule_id, MIN(lw.session_id) AS session_id FROM @@table lw LEFT JOIN spans s ON s.span_id = lw.span_id WHERE lw.rule_id ILIKE @pattern AND (@sessionID = ” OR lw.session_id = @sessionID) AND lw.trace_id != ” GROUP BY lw.trace_id LIMIT @limit
func (l lintWarningDo) SearchByRule(sessionID string, pattern string, limit int) (result []model.LintSearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, pattern)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, limit)
	generateSQL.WriteString("SELECT lw.trace_id, COALESCE(MIN(s.name), '(trace)') AS title, MIN(lw.rule_id) AS rule_id, MIN(lw.session_id) AS session_id FROM lint_warnings lw LEFT JOIN spans s ON s.span_id = lw.span_id WHERE lw.rule_id ILIKE ? AND (? = '' OR lw.session_id = ?) AND lw.trace_id != '' GROUP BY lw.trace_id LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = l.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListWithTraceIssues
//
// SELECT span_id, trace_id, session_id, rule_id, message, severity, created_at FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) UNION ALL SELECT example_span_id AS span_id, trace_id, session_id, kind AS rule_id, CASE kind WHEN 'n_plus_one' THEN 'N+1 query: ' || CAST(count AS VARCHAR) || ' repeated executions wasting ' || CAST(ROUND(wasted_ns / 1e6, 1) AS VARCHAR) || 'ms — ' || fingerprint ELSE kind || ': ' || CAST(count AS VARCHAR) || ' occurrences — ' || fingerprint END AS message, 'warning' AS severity, created_at FROM trace_issues WHERE (@sessionID = ” OR session_id = @sessionID) ORDER BY created_at DESC LIMIT 500
func (l lintWarningDo) ListWithTraceIssues(sessionID string) (result []model.LintWarning, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT span_id, trace_id, session_id, rule_id, message, severity, created_at FROM lint_warnings WHERE (? = '' OR session_id = ?) UNION ALL SELECT example_span_id AS span_id, trace_id, session_id, kind AS rule_id, CASE kind WHEN 'n_plus_one' THEN 'N+1 query: ' || CAST(count AS VARCHAR) || ' repeated executions wasting ' || CAST(ROUND(wasted_ns / 1e6, 1) AS VARCHAR) || 'ms — ' || fingerprint ELSE kind || ': ' || CAST(count AS VARCHAR) || ' occurrences — ' || fingerprint END AS message, 'warning' AS severity, created_at FROM trace_issues WHERE (? = '' OR session_id = ?) ORDER BY created_at DESC LIMIT 500 ")

	var executeSQL *gorm.DB
	executeSQL = l.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (l lintWarningDo) Debug() ILintWarningDo {
	return l.withDO(l.DO.Debug())
}

func (l lintWarningDo) WithContext(ctx context.Context) ILintWarningDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lintWarningDo) ReadDB() ILintWarningDo {
	return l.Clauses(dbresolver.Read)
}

func (l lintWarningDo) WriteDB() ILintWarningDo {
	return l.Clauses(dbresolver.Write)
}

func (l lintWarningDo) Session(config *gorm.Session) ILintWarningDo {
	return l.withDO(l.DO.Session(config))
}

func (l lintWarningDo) Clauses(conds ...clause.Expression) ILintWarningDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lintWarningDo) Returning(value interface{}, columns ...string) ILintWarningDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lintWarningDo) Not(conds ...gen.Condition) ILintWarningDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lintWarningDo) Or(conds ...gen.Condition) ILintWarningDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lintWarningDo) Select(conds ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lintWarningDo) Where(conds ...gen.Condition) ILintWarningDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lintWarningDo) Order(conds ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lintWarningDo) Distinct(cols ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lintWarningDo) Omit(cols ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lintWarningDo) Join(table schema.Tabler, on ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lintWarningDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lintWarningDo) RightJoin(table schema.Tabler, on ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lintWarningDo) Group(cols ...field.Expr) ILintWarningDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lintWarningDo) Having(conds ...gen.Condition) ILintWarningDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lintWarningDo) Limit(limit int) ILintWarningDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lintWarningDo) Offset(offset int) ILintWarningDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lintWarningDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILintWarningDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lintWarningDo) Unscoped() ILintWarningDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lintWarningDo) Create(values ...*model.LintWarning) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lintWarningDo) CreateInBatches(values []*model.LintWarning, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lintWarningDo) Save(values ...*model.LintWarning) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lintWarningDo) First() (*model.LintWarning, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LintWarning), nil
	}
}

func (l lintWarningDo) Take() (*model.LintWarning, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LintWarning), nil
	}
}

func (l lintWarningDo) Last() (*model.LintWarning, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LintWarning), nil
	}
}

func (l lintWarningDo) Find() ([]*model.LintWarning, error) {
	result, err := l.DO.Find()
	return result.([]*model.LintWarning), err
}

func (l lintWarningDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LintWarning, err error) {
	buf := make([]*model.LintWarning, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lintWarningDo) FindInBatches(result *[]*model.LintWarning, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lintWarningDo) Attrs(attrs ...field.AssignExpr) ILintWarningDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lintWarningDo) Assign(attrs ...field.AssignExpr) ILintWarningDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lintWarningDo) Joins(fields ...field.RelationField) ILintWarningDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lintWarningDo) Preload(fields ...field.RelationField) ILintWarningDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lintWarningDo) FirstOrInit() (*model.LintWarning, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LintWarning), nil
	}
}

func (l lintWarningDo) FirstOrCreate() (*model.LintWarning, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LintWarning), nil
	}
}

func (l lintWarningDo) FindByPage(offset int, limit int) (result []*model.LintWarning, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lintWarningDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lintWarningDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lintWarningDo) Delete(models ...*model.LintWarning) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lintWarningDo) withDO(do gen.Dao) *lintWarningDo {
	l.DO = *do.(*gen.DO)
	return l
}
