// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newMeta(db *gorm.DB, opts ...gen.DOOption) meta {
	_meta := meta{}

	_meta.metaDo.UseDB(db, opts...)
	_meta.metaDo.UseModel(&model.Meta{})

	tableName := _meta.metaDo.TableName()
	_meta.ALL = field.NewAsterisk(tableName)
	_meta.Key = field.NewString(tableName, "meta_key")
	_meta.Value = field.NewString(tableName, "meta_value")

	_meta.fillFieldMap()

	return _meta
}

type meta struct {
	metaDo

	ALL   field.Asterisk
	Key   field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (m meta) Table(newTableName string) *meta {
	m.metaDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meta) As(alias string) *meta {
	m.metaDo.DO = *(m.metaDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meta) updateTableName(table string) *meta {
	m.ALL = field.NewAsterisk(table)
	m.Key = field.NewString(table, "meta_key")
	m.Value = field.NewString(table, "meta_value")

	m.fillFieldMap()

	return m
}

func (m *meta) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meta) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 2)
	m.fieldMap["meta_key"] = m.Key
	m.fieldMap["meta_value"] = m.Value
}

func (m meta) clone(db *gorm.DB) meta {
	m.metaDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meta) replaceDB(db *gorm.DB) meta {
	m.metaDo.ReplaceDB(db)
	return m
}

type metaDo struct{ gen.DO }

type IMetaDo interface {
	gen.SubQuery
	Debug() IMetaDo
	WithContext(ctx context.Context) IMetaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMetaDo
	WriteDB() IMetaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMetaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMetaDo
	Not(conds ...gen.Condition) IMetaDo
	Or(conds ...gen.Condition) IMetaDo
	Select(conds ...field.Expr) IMetaDo
	Where(conds ...gen.Condition) IMetaDo
	Order(conds ...field.Expr) IMetaDo
	Distinct(cols ...field.Expr) IMetaDo
	Omit(cols ...field.Expr) IMetaDo
	Join(table schema.Tabler, on ...field.Expr) IMetaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMetaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMetaDo
	Group(cols ...field.Expr) IMetaDo
	Having(conds ...gen.Condition) IMetaDo
	Limit(limit int) IMetaDo
	Offset(offset int) IMetaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMetaDo
	Unscoped() IMetaDo
	Create(values ...*model.Meta) error
	CreateInBatches(values []*model.Meta, batchSize int) error
	Save(values ...*model.Meta) error
	First() (*model.Meta, error)
	Take() (*model.Meta, error)
	Last() (*model.Meta, error)
	Find() ([]*model.Meta, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Meta, err error)
	FindInBatches(result *[]*model.Meta, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Meta) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMetaDo
	Assign(attrs ...field.AssignExpr) IMetaDo
	Joins(fields ...field.RelationField) IMetaDo
	Preload(fields ...field.RelationField) IMetaDo
	FirstOrInit() (*model.Meta, error)
	FirstOrCreate() (*model.Meta, error)
	FindByPage(offset int, limit int) (result []*model.Meta, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMetaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	DatabaseSize() (result []model.DatabaseSize, err error)
	UpsertValue(key string, value string) (err error)
}

// DatabaseSize
//
// SELECT block_size, used_blocks FROM pragma_database_size() LIMIT 1
func (m metaDo) DatabaseSize() (result []model.DatabaseSize, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT block_size, used_blocks FROM pragma_database_size() LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// UpsertValue
//
// INSERT INTO @@table (meta_key, meta_value) VALUES (@key, @value) ON CONFLICT (meta_key) DO UPDATE SET meta_value = excluded.meta_value
func (m metaDo) UpsertValue(key string, value string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, key)
	params = append(params, value)
	generateSQL.WriteString("INSERT INTO meta (meta_key, meta_value) VALUES (?, ?) ON CONFLICT (meta_key) DO UPDATE SET meta_value = excluded.meta_value ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (m metaDo) Debug() IMetaDo {
	return m.withDO(m.DO.Debug())
}

func (m metaDo) WithContext(ctx context.Context) IMetaDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m metaDo) ReadDB() IMetaDo {
	return m.Clauses(dbresolver.Read)
}

func (m metaDo) WriteDB() IMetaDo {
	return m.Clauses(dbresolver.Write)
}

func (m metaDo) Session(config *gorm.Session) IMetaDo {
	return m.withDO(m.DO.Session(config))
}

func (m metaDo) Clauses(conds ...clause.Expression) IMetaDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m metaDo) Returning(value interface{}, columns ...string) IMetaDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m metaDo) Not(conds ...gen.Condition) IMetaDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m metaDo) Or(conds ...gen.Condition) IMetaDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m metaDo) Select(conds ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m metaDo) Where(conds ...gen.Condition) IMetaDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m metaDo) Order(conds ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m metaDo) Distinct(cols ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m metaDo) Omit(cols ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m metaDo) Join(table schema.Tabler, on ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m metaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMetaDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m metaDo) RightJoin(table schema.Tabler, on ...field.Expr) IMetaDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m metaDo) Group(cols ...field.Expr) IMetaDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m metaDo) Having(conds ...gen.Condition) IMetaDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m metaDo) Limit(limit int) IMetaDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m metaDo) Offset(offset int) IMetaDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m metaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMetaDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m metaDo) Unscoped() IMetaDo {
	return m.withDO(m.DO.Unscoped())
}

func (m metaDo) Create(values ...*model.Meta) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m metaDo) CreateInBatches(values []*model.Meta, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m metaDo) Save(values ...*model.Meta) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m metaDo) First() (*model.Meta, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Meta), nil
	}
}

func (m metaDo) Take() (*model.Meta, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Meta), nil
	}
}

func (m metaDo) Last() (*model.Meta, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Meta), nil
	}
}

func (m metaDo) Find() ([]*model.Meta, error) {
	result, err := m.DO.Find()
	return result.([]*model.Meta), err
}

func (m metaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Meta, err error) {
	buf := make([]*model.Meta, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m metaDo) FindInBatches(result *[]*model.Meta, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m metaDo) Attrs(attrs ...field.AssignExpr) IMetaDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m metaDo) Assign(attrs ...field.AssignExpr) IMetaDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m metaDo) Joins(fields ...field.RelationField) IMetaDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m metaDo) Preload(fields ...field.RelationField) IMetaDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m metaDo) FirstOrInit() (*model.Meta, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Meta), nil
	}
}

func (m metaDo) FirstOrCreate() (*model.Meta, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Meta), nil
	}
}

func (m metaDo) FindByPage(offset int, limit int) (result []*model.Meta, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m metaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m metaDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m metaDo) Delete(models ...*model.Meta) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *metaDo) withDO(do gen.Dao) *metaDo {
	m.DO = *do.(*gen.DO)
	return m
}
