// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newMetricSeriesCatalog(db *gorm.DB, opts ...gen.DOOption) metricSeriesCatalog {
	_metricSeriesCatalog := metricSeriesCatalog{}

	_metricSeriesCatalog.metricSeriesCatalogDo.UseDB(db, opts...)
	_metricSeriesCatalog.metricSeriesCatalogDo.UseModel(&model.MetricSeriesCatalog{})

	tableName := _metricSeriesCatalog.metricSeriesCatalogDo.TableName()
	_metricSeriesCatalog.ALL = field.NewAsterisk(tableName)
	_metricSeriesCatalog.SessionID = field.NewString(tableName, "session_id")
	_metricSeriesCatalog.ServiceName = field.NewString(tableName, "service_name")
	_metricSeriesCatalog.Name = field.NewString(tableName, "name")
	_metricSeriesCatalog.SeriesKey = field.NewString(tableName, "series_key")
	_metricSeriesCatalog.SeriesAttributes = field.NewString(tableName, "series_attributes")
	_metricSeriesCatalog.FirstTimestampNs = field.NewInt64(tableName, "first_timestamp_ns")
	_metricSeriesCatalog.LastTimestampNs = field.NewInt64(tableName, "last_timestamp_ns")
	_metricSeriesCatalog.PointCount = field.NewInt64(tableName, "point_count")

	_metricSeriesCatalog.fillFieldMap()

	return _metricSeriesCatalog
}

type metricSeriesCatalog struct {
	metricSeriesCatalogDo

	ALL              field.Asterisk
	SessionID        field.String
	ServiceName      field.String
	Name             field.String
	SeriesKey        field.String
	SeriesAttributes field.String
	FirstTimestampNs field.Int64
	LastTimestampNs  field.Int64
	PointCount       field.Int64

	fieldMap map[string]field.Expr
}

func (m metricSeriesCatalog) Table(newTableName string) *metricSeriesCatalog {
	m.metricSeriesCatalogDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m metricSeriesCatalog) As(alias string) *metricSeriesCatalog {
	m.metricSeriesCatalogDo.DO = *(m.metricSeriesCatalogDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *metricSeriesCatalog) updateTableName(table string) *metricSeriesCatalog {
	m.ALL = field.NewAsterisk(table)
	m.SessionID = field.NewString(table, "session_id")
	m.ServiceName = field.NewString(table, "service_name")
	m.Name = field.NewString(table, "name")
	m.SeriesKey = field.NewString(table, "series_key")
	m.SeriesAttributes = field.NewString(table, "series_attributes")
	m.FirstTimestampNs = field.NewInt64(table, "first_timestamp_ns")
	m.LastTimestampNs = field.NewInt64(table, "last_timestamp_ns")
	m.PointCount = field.NewInt64(table, "point_count")

	m.fillFieldMap()

	return m
}

func (m *metricSeriesCatalog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *metricSeriesCatalog) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["session_id"] = m.SessionID
	m.fieldMap["service_name"] = m.ServiceName
	m.fieldMap["name"] = m.Name
	m.fieldMap["series_key"] = m.SeriesKey
	m.fieldMap["series_attributes"] = m.SeriesAttributes
	m.fieldMap["first_timestamp_ns"] = m.FirstTimestampNs
	m.fieldMap["last_timestamp_ns"] = m.LastTimestampNs
	m.fieldMap["point_count"] = m.PointCount
}

func (m metricSeriesCatalog) clone(db *gorm.DB) metricSeriesCatalog {
	m.metricSeriesCatalogDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m metricSeriesCatalog) replaceDB(db *gorm.DB) metricSeriesCatalog {
	m.metricSeriesCatalogDo.ReplaceDB(db)
	return m
}

type metricSeriesCatalogDo struct{ gen.DO }

type IMetricSeriesCatalogDo interface {
	gen.SubQuery
	Debug() IMetricSeriesCatalogDo
	WithContext(ctx context.Context) IMetricSeriesCatalogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMetricSeriesCatalogDo
	WriteDB() IMetricSeriesCatalogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMetricSeriesCatalogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMetricSeriesCatalogDo
	Not(conds ...gen.Condition) IMetricSeriesCatalogDo
	Or(conds ...gen.Condition) IMetricSeriesCatalogDo
	Select(conds ...field.Expr) IMetricSeriesCatalogDo
	Where(conds ...gen.Condition) IMetricSeriesCatalogDo
	Order(conds ...field.Expr) IMetricSeriesCatalogDo
	Distinct(cols ...field.Expr) IMetricSeriesCatalogDo
	Omit(cols ...field.Expr) IMetricSeriesCatalogDo
	Join(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo
	Group(cols ...field.Expr) IMetricSeriesCatalogDo
	Having(conds ...gen.Condition) IMetricSeriesCatalogDo
	Limit(limit int) IMetricSeriesCatalogDo
	Offset(offset int) IMetricSeriesCatalogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMetricSeriesCatalogDo
	Unscoped() IMetricSeriesCatalogDo
	Create(values ...*model.MetricSeriesCatalog) error
	CreateInBatches(values []*model.MetricSeriesCatalog, batchSize int) error
	Save(values ...*model.MetricSeriesCatalog) error
	First() (*model.MetricSeriesCatalog, error)
	Take() (*model.MetricSeriesCatalog, error)
	Last() (*model.MetricSeriesCatalog, error)
	Find() ([]*model.MetricSeriesCatalog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MetricSeriesCatalog, err error)
	FindInBatches(result *[]*model.MetricSeriesCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MetricSeriesCatalog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMetricSeriesCatalogDo
	Assign(attrs ...field.AssignExpr) IMetricSeriesCatalogDo
	Joins(fields ...field.RelationField) IMetricSeriesCatalogDo
	Preload(fields ...field.RelationField) IMetricSeriesCatalogDo
	FirstOrInit() (*model.MetricSeriesCatalog, error)
	FirstOrCreate() (*model.MetricSeriesCatalog, error)
	FindByPage(offset int, limit int) (result []*model.MetricSeriesCatalog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMetricSeriesCatalogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m metricSeriesCatalogDo) Debug() IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Debug())
}

func (m metricSeriesCatalogDo) WithContext(ctx context.Context) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m metricSeriesCatalogDo) ReadDB() IMetricSeriesCatalogDo {
	return m.Clauses(dbresolver.Read)
}

func (m metricSeriesCatalogDo) WriteDB() IMetricSeriesCatalogDo {
	return m.Clauses(dbresolver.Write)
}

func (m metricSeriesCatalogDo) Session(config *gorm.Session) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Session(config))
}

func (m metricSeriesCatalogDo) Clauses(conds ...clause.Expression) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m metricSeriesCatalogDo) Returning(value interface{}, columns ...string) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m metricSeriesCatalogDo) Not(conds ...gen.Condition) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m metricSeriesCatalogDo) Or(conds ...gen.Condition) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m metricSeriesCatalogDo) Select(conds ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m metricSeriesCatalogDo) Where(conds ...gen.Condition) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m metricSeriesCatalogDo) Order(conds ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m metricSeriesCatalogDo) Distinct(cols ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m metricSeriesCatalogDo) Omit(cols ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m metricSeriesCatalogDo) Join(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m metricSeriesCatalogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m metricSeriesCatalogDo) RightJoin(table schema.Tabler, on ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m metricSeriesCatalogDo) Group(cols ...field.Expr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m metricSeriesCatalogDo) Having(conds ...gen.Condition) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m metricSeriesCatalogDo) Limit(limit int) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m metricSeriesCatalogDo) Offset(offset int) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m metricSeriesCatalogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m metricSeriesCatalogDo) Unscoped() IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Unscoped())
}

func (m metricSeriesCatalogDo) Create(values ...*model.MetricSeriesCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m metricSeriesCatalogDo) CreateInBatches(values []*model.MetricSeriesCatalog, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m metricSeriesCatalogDo) Save(values ...*model.MetricSeriesCatalog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m metricSeriesCatalogDo) First() (*model.MetricSeriesCatalog, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MetricSeriesCatalog), nil
	}
}

func (m metricSeriesCatalogDo) Take() (*model.MetricSeriesCatalog, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MetricSeriesCatalog), nil
	}
}

func (m metricSeriesCatalogDo) Last() (*model.MetricSeriesCatalog, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MetricSeriesCatalog), nil
	}
}

func (m metricSeriesCatalogDo) Find() ([]*model.MetricSeriesCatalog, error) {
	result, err := m.DO.Find()
	return result.([]*model.MetricSeriesCatalog), err
}

func (m metricSeriesCatalogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MetricSeriesCatalog, err error) {
	buf := make([]*model.MetricSeriesCatalog, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m metricSeriesCatalogDo) FindInBatches(result *[]*model.MetricSeriesCatalog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m metricSeriesCatalogDo) Attrs(attrs ...field.AssignExpr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m metricSeriesCatalogDo) Assign(attrs ...field.AssignExpr) IMetricSeriesCatalogDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m metricSeriesCatalogDo) Joins(fields ...field.RelationField) IMetricSeriesCatalogDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m metricSeriesCatalogDo) Preload(fields ...field.RelationField) IMetricSeriesCatalogDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m metricSeriesCatalogDo) FirstOrInit() (*model.MetricSeriesCatalog, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MetricSeriesCatalog), nil
	}
}

func (m metricSeriesCatalogDo) FirstOrCreate() (*model.MetricSeriesCatalog, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MetricSeriesCatalog), nil
	}
}

func (m metricSeriesCatalogDo) FindByPage(offset int, limit int) (result []*model.MetricSeriesCatalog, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m metricSeriesCatalogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m metricSeriesCatalogDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m metricSeriesCatalogDo) Delete(models ...*model.MetricSeriesCatalog) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *metricSeriesCatalogDo) withDO(do gen.Dao) *metricSeriesCatalogDo {
	m.DO = *do.(*gen.DO)
	return m
}
