// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newMetric(db *gorm.DB, opts ...gen.DOOption) metric {
	_metric := metric{}

	_metric.metricDo.UseDB(db, opts...)
	_metric.metricDo.UseModel(&model.Metric{})

	tableName := _metric.metricDo.TableName()
	_metric.ALL = field.NewAsterisk(tableName)
	_metric.Name = field.NewString(tableName, "name")
	_metric.Description = field.NewString(tableName, "description")
	_metric.Unit = field.NewString(tableName, "unit")
	_metric.Type = field.NewString(tableName, "type")
	_metric.AggregationTemporality = field.NewString(tableName, "aggregation_temporality")
	_metric.IsMonotonic = field.NewBool(tableName, "is_monotonic")
	_metric.StartTimestampNs = field.NewInt64(tableName, "start_timestamp_ns")
	_metric.TimestampNs = field.NewInt64(tableName, "timestamp_ns")
	_metric.Flags = field.NewUint32(tableName, "flags")
	_metric.Value = field.NewFloat64(tableName, "value")
	_metric.HistogramCount = field.NewUint64(tableName, "histogram_count")
	_metric.HistogramSum = field.NewFloat64(tableName, "histogram_sum")
	_metric.HistogramMin = field.NewFloat64(tableName, "histogram_min")
	_metric.HistogramMax = field.NewFloat64(tableName, "histogram_max")
	_metric.ExplicitBounds = field.NewString(tableName, "explicit_bounds")
	_metric.BucketCounts = field.NewString(tableName, "bucket_counts")
	_metric.ExpScale = field.NewInt32(tableName, "exp_scale")
	_metric.ExpZeroCount = field.NewUint64(tableName, "exp_zero_count")
	_metric.ExpZeroThreshold = field.NewFloat64(tableName, "exp_zero_threshold")
	_metric.ExpPositiveOffset = field.NewInt32(tableName, "exp_positive_offset")
	_metric.ExpPositiveCounts = field.NewString(tableName, "exp_positive_counts")
	_metric.ExpNegativeOffset = field.NewInt32(tableName, "exp_negative_offset")
	_metric.ExpNegativeCounts = field.NewString(tableName, "exp_negative_counts")
	_metric.SummaryCount = field.NewUint64(tableName, "summary_count")
	_metric.SummarySum = field.NewFloat64(tableName, "summary_sum")
	_metric.SummaryQuantiles = field.NewString(tableName, "summary_quantiles")
	_metric.Attributes = field.NewString(tableName, "attributes")
	_metric.Resource = field.NewString(tableName, "resource")
	_metric.SeriesAttributes = field.NewString(tableName, "series_attributes")
	_metric.SeriesKey = field.NewString(tableName, "series_key")
	_metric.ScopeName = field.NewString(tableName, "scope_name")
	_metric.ScopeVersion = field.NewString(tableName, "scope_version")
	_metric.ScopeSchemaURL = field.NewString(tableName, "scope_schema_url")
	_metric.ScopeAttributes = field.NewString(tableName, "scope_attributes")
	_metric.Exemplars = field.NewString(tableName, "exemplars")
	_metric.ServiceName = field.NewString(tableName, "service_name")
	_metric.SessionID = field.NewString(tableName, "session_id")

	_metric.fillFieldMap()

	return _metric
}

type metric struct {
	metricDo

	ALL                    field.Asterisk
	Name                   field.String
	Description            field.String
	Unit                   field.String
	Type                   field.String
	AggregationTemporality field.String
	IsMonotonic            field.Bool
	StartTimestampNs       field.Int64
	TimestampNs            field.Int64
	Flags                  field.Uint32
	Value                  field.Float64
	HistogramCount         field.Uint64
	HistogramSum           field.Float64
	HistogramMin           field.Float64
	HistogramMax           field.Float64
	ExplicitBounds         field.String
	BucketCounts           field.String
	ExpScale               field.Int32
	ExpZeroCount           field.Uint64
	ExpZeroThreshold       field.Float64
	ExpPositiveOffset      field.Int32
	ExpPositiveCounts      field.String
	ExpNegativeOffset      field.Int32
	ExpNegativeCounts      field.String
	SummaryCount           field.Uint64
	SummarySum             field.Float64
	SummaryQuantiles       field.String
	Attributes             field.String
	Resource               field.String
	SeriesAttributes       field.String
	SeriesKey              field.String
	ScopeName              field.String
	ScopeVersion           field.String
	ScopeSchemaURL         field.String
	ScopeAttributes        field.String
	Exemplars              field.String
	ServiceName            field.String
	SessionID              field.String

	fieldMap map[string]field.Expr
}

func (m metric) Table(newTableName string) *metric {
	m.metricDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m metric) As(alias string) *metric {
	m.metricDo.DO = *(m.metricDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *metric) updateTableName(table string) *metric {
	m.ALL = field.NewAsterisk(table)
	m.Name = field.NewString(table, "name")
	m.Description = field.NewString(table, "description")
	m.Unit = field.NewString(table, "unit")
	m.Type = field.NewString(table, "type")
	m.AggregationTemporality = field.NewString(table, "aggregation_temporality")
	m.IsMonotonic = field.NewBool(table, "is_monotonic")
	m.StartTimestampNs = field.NewInt64(table, "start_timestamp_ns")
	m.TimestampNs = field.NewInt64(table, "timestamp_ns")
	m.Flags = field.NewUint32(table, "flags")
	m.Value = field.NewFloat64(table, "value")
	m.HistogramCount = field.NewUint64(table, "histogram_count")
	m.HistogramSum = field.NewFloat64(table, "histogram_sum")
	m.HistogramMin = field.NewFloat64(table, "histogram_min")
	m.HistogramMax = field.NewFloat64(table, "histogram_max")
	m.ExplicitBounds = field.NewString(table, "explicit_bounds")
	m.BucketCounts = field.NewString(table, "bucket_counts")
	m.ExpScale = field.NewInt32(table, "exp_scale")
	m.ExpZeroCount = field.NewUint64(table, "exp_zero_count")
	m.ExpZeroThreshold = field.NewFloat64(table, "exp_zero_threshold")
	m.ExpPositiveOffset = field.NewInt32(table, "exp_positive_offset")
	m.ExpPositiveCounts = field.NewString(table, "exp_positive_counts")
	m.ExpNegativeOffset = field.NewInt32(table, "exp_negative_offset")
	m.ExpNegativeCounts = field.NewString(table, "exp_negative_counts")
	m.SummaryCount = field.NewUint64(table, "summary_count")
	m.SummarySum = field.NewFloat64(table, "summary_sum")
	m.SummaryQuantiles = field.NewString(table, "summary_quantiles")
	m.Attributes = field.NewString(table, "attributes")
	m.Resource = field.NewString(table, "resource")
	m.SeriesAttributes = field.NewString(table, "series_attributes")
	m.SeriesKey = field.NewString(table, "series_key")
	m.ScopeName = field.NewString(table, "scope_name")
	m.ScopeVersion = field.NewString(table, "scope_version")
	m.ScopeSchemaURL = field.NewString(table, "scope_schema_url")
	m.ScopeAttributes = field.NewString(table, "scope_attributes")
	m.Exemplars = field.NewString(table, "exemplars")
	m.ServiceName = field.NewString(table, "service_name")
	m.SessionID = field.NewString(table, "session_id")

	m.fillFieldMap()

	return m
}

func (m *metric) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *metric) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 37)
	m.fieldMap["name"] = m.Name
	m.fieldMap["description"] = m.Description
	m.fieldMap["unit"] = m.Unit
	m.fieldMap["type"] = m.Type
	m.fieldMap["aggregation_temporality"] = m.AggregationTemporality
	m.fieldMap["is_monotonic"] = m.IsMonotonic
	m.fieldMap["start_timestamp_ns"] = m.StartTimestampNs
	m.fieldMap["timestamp_ns"] = m.TimestampNs
	m.fieldMap["flags"] = m.Flags
	m.fieldMap["value"] = m.Value
	m.fieldMap["histogram_count"] = m.HistogramCount
	m.fieldMap["histogram_sum"] = m.HistogramSum
	m.fieldMap["histogram_min"] = m.HistogramMin
	m.fieldMap["histogram_max"] = m.HistogramMax
	m.fieldMap["explicit_bounds"] = m.ExplicitBounds
	m.fieldMap["bucket_counts"] = m.BucketCounts
	m.fieldMap["exp_scale"] = m.ExpScale
	m.fieldMap["exp_zero_count"] = m.ExpZeroCount
	m.fieldMap["exp_zero_threshold"] = m.ExpZeroThreshold
	m.fieldMap["exp_positive_offset"] = m.ExpPositiveOffset
	m.fieldMap["exp_positive_counts"] = m.ExpPositiveCounts
	m.fieldMap["exp_negative_offset"] = m.ExpNegativeOffset
	m.fieldMap["exp_negative_counts"] = m.ExpNegativeCounts
	m.fieldMap["summary_count"] = m.SummaryCount
	m.fieldMap["summary_sum"] = m.SummarySum
	m.fieldMap["summary_quantiles"] = m.SummaryQuantiles
	m.fieldMap["attributes"] = m.Attributes
	m.fieldMap["resource"] = m.Resource
	m.fieldMap["series_attributes"] = m.SeriesAttributes
	m.fieldMap["series_key"] = m.SeriesKey
	m.fieldMap["scope_name"] = m.ScopeName
	m.fieldMap["scope_version"] = m.ScopeVersion
	m.fieldMap["scope_schema_url"] = m.ScopeSchemaURL
	m.fieldMap["scope_attributes"] = m.ScopeAttributes
	m.fieldMap["exemplars"] = m.Exemplars
	m.fieldMap["service_name"] = m.ServiceName
	m.fieldMap["session_id"] = m.SessionID
}

func (m metric) clone(db *gorm.DB) metric {
	m.metricDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m metric) replaceDB(db *gorm.DB) metric {
	m.metricDo.ReplaceDB(db)
	return m
}

type metricDo struct{ gen.DO }

type IMetricDo interface {
	gen.SubQuery
	Debug() IMetricDo
	WithContext(ctx context.Context) IMetricDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMetricDo
	WriteDB() IMetricDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMetricDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMetricDo
	Not(conds ...gen.Condition) IMetricDo
	Or(conds ...gen.Condition) IMetricDo
	Select(conds ...field.Expr) IMetricDo
	Where(conds ...gen.Condition) IMetricDo
	Order(conds ...field.Expr) IMetricDo
	Distinct(cols ...field.Expr) IMetricDo
	Omit(cols ...field.Expr) IMetricDo
	Join(table schema.Tabler, on ...field.Expr) IMetricDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMetricDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMetricDo
	Group(cols ...field.Expr) IMetricDo
	Having(conds ...gen.Condition) IMetricDo
	Limit(limit int) IMetricDo
	Offset(offset int) IMetricDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMetricDo
	Unscoped() IMetricDo
	Create(values ...*model.Metric) error
	CreateInBatches(values []*model.Metric, batchSize int) error
	Save(values ...*model.Metric) error
	First() (*model.Metric, error)
	Take() (*model.Metric, error)
	Last() (*model.Metric, error)
	Find() ([]*model.Metric, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Metric, err error)
	FindInBatches(result *[]*model.Metric, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Metric) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMetricDo
	Assign(attrs ...field.AssignExpr) IMetricDo
	Joins(fields ...field.RelationField) IMetricDo
	Preload(fields ...field.RelationField) IMetricDo
	FirstOrInit() (*model.Metric, error)
	FirstOrCreate() (*model.Metric, error)
	FindByPage(offset int, limit int) (result []*model.Metric, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMetricDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ListCatalog(sessionID string) (result []model.MetricCatalogEntry, err error)
	GetStreamMetadata(name string, service string, sessionID string) (result []model.Metric, err error)
}

// ListCatalog
//
// SELECT name, service_name, type, unit, description, any_value(aggregation_temporality) AS aggregation_temporality, any_value(is_monotonic) AS is_monotonic, COUNT(*) AS sample_count FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) GROUP BY name, service_name, type, unit, description ORDER BY service_name, name
func (m metricDo) ListCatalog(sessionID string) (result []model.MetricCatalogEntry, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT name, service_name, type, unit, description, any_value(aggregation_temporality) AS aggregation_temporality, any_value(is_monotonic) AS is_monotonic, COUNT(*) AS sample_count FROM metrics WHERE (? = '' OR session_id = ?) GROUP BY name, service_name, type, unit, description ORDER BY service_name, name ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetStreamMetadata
//
// SELECT name, description, unit, type, aggregation_temporality, is_monotonic, service_name FROM @@table WHERE (@name = ” OR name = @name) AND (@service = ” OR service_name = @service) AND (@sessionID = ” OR session_id = @sessionID) ORDER BY timestamp_ns DESC LIMIT 1
func (m metricDo) GetStreamMetadata(name string, service string, sessionID string) (result []model.Metric, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, name)
	params = append(params, service)
	params = append(params, service)
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT name, description, unit, type, aggregation_temporality, is_monotonic, service_name FROM metrics WHERE (? = '' OR name = ?) AND (? = '' OR service_name = ?) AND (? = '' OR session_id = ?) ORDER BY timestamp_ns DESC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (m metricDo) Debug() IMetricDo {
	return m.withDO(m.DO.Debug())
}

func (m metricDo) WithContext(ctx context.Context) IMetricDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m metricDo) ReadDB() IMetricDo {
	return m.Clauses(dbresolver.Read)
}

func (m metricDo) WriteDB() IMetricDo {
	return m.Clauses(dbresolver.Write)
}

func (m metricDo) Session(config *gorm.Session) IMetricDo {
	return m.withDO(m.DO.Session(config))
}

func (m metricDo) Clauses(conds ...clause.Expression) IMetricDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m metricDo) Returning(value interface{}, columns ...string) IMetricDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m metricDo) Not(conds ...gen.Condition) IMetricDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m metricDo) Or(conds ...gen.Condition) IMetricDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m metricDo) Select(conds ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m metricDo) Where(conds ...gen.Condition) IMetricDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m metricDo) Order(conds ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m metricDo) Distinct(cols ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m metricDo) Omit(cols ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m metricDo) Join(table schema.Tabler, on ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m metricDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMetricDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m metricDo) RightJoin(table schema.Tabler, on ...field.Expr) IMetricDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m metricDo) Group(cols ...field.Expr) IMetricDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m metricDo) Having(conds ...gen.Condition) IMetricDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m metricDo) Limit(limit int) IMetricDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m metricDo) Offset(offset int) IMetricDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m metricDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMetricDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m metricDo) Unscoped() IMetricDo {
	return m.withDO(m.DO.Unscoped())
}

func (m metricDo) Create(values ...*model.Metric) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m metricDo) CreateInBatches(values []*model.Metric, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m metricDo) Save(values ...*model.Metric) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m metricDo) First() (*model.Metric, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metric), nil
	}
}

func (m metricDo) Take() (*model.Metric, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metric), nil
	}
}

func (m metricDo) Last() (*model.Metric, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metric), nil
	}
}

func (m metricDo) Find() ([]*model.Metric, error) {
	result, err := m.DO.Find()
	return result.([]*model.Metric), err
}

func (m metricDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Metric, err error) {
	buf := make([]*model.Metric, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m metricDo) FindInBatches(result *[]*model.Metric, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m metricDo) Attrs(attrs ...field.AssignExpr) IMetricDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m metricDo) Assign(attrs ...field.AssignExpr) IMetricDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m metricDo) Joins(fields ...field.RelationField) IMetricDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m metricDo) Preload(fields ...field.RelationField) IMetricDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m metricDo) FirstOrInit() (*model.Metric, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metric), nil
	}
}

func (m metricDo) FirstOrCreate() (*model.Metric, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Metric), nil
	}
}

func (m metricDo) FindByPage(offset int, limit int) (result []*model.Metric, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m metricDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m metricDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m metricDo) Delete(models ...*model.Metric) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *metricDo) withDO(do gen.Dao) *metricDo {
	m.DO = *do.(*gen.DO)
	return m
}
