// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newNotificationRecord(db *gorm.DB, opts ...gen.DOOption) notificationRecord {
	_notificationRecord := notificationRecord{}

	_notificationRecord.notificationRecordDo.UseDB(db, opts...)
	_notificationRecord.notificationRecordDo.UseModel(&model.NotificationRecord{})

	tableName := _notificationRecord.notificationRecordDo.TableName()
	_notificationRecord.ALL = field.NewAsterisk(tableName)
	_notificationRecord.ID = field.NewString(tableName, "id")
	_notificationRecord.Source = field.NewString(tableName, "source")
	_notificationRecord.SourceID = field.NewString(tableName, "source_id")
	_notificationRecord.Severity = field.NewString(tableName, "severity")
	_notificationRecord.Title = field.NewString(tableName, "title")
	_notificationRecord.Body = field.NewString(tableName, "body")
	_notificationRecord.Link = field.NewString(tableName, "link")
	_notificationRecord.DedupeKey = field.NewString(tableName, "dedupe_key")
	_notificationRecord.CreatedAt = field.NewInt64(tableName, "created_at")
	_notificationRecord.ReadAt = field.NewInt64(tableName, "read_at")
	_notificationRecord.AcknowledgedAt = field.NewInt64(tableName, "acknowledged_at")

	_notificationRecord.fillFieldMap()

	return _notificationRecord
}

type notificationRecord struct {
	notificationRecordDo

	ALL            field.Asterisk
	ID             field.String
	Source         field.String
	SourceID       field.String
	Severity       field.String
	Title          field.String
	Body           field.String
	Link           field.String
	DedupeKey      field.String
	CreatedAt      field.Int64
	ReadAt         field.Int64
	AcknowledgedAt field.Int64

	fieldMap map[string]field.Expr
}

func (n notificationRecord) Table(newTableName string) *notificationRecord {
	n.notificationRecordDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationRecord) As(alias string) *notificationRecord {
	n.notificationRecordDo.DO = *(n.notificationRecordDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationRecord) updateTableName(table string) *notificationRecord {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewString(table, "id")
	n.Source = field.NewString(table, "source")
	n.SourceID = field.NewString(table, "source_id")
	n.Severity = field.NewString(table, "severity")
	n.Title = field.NewString(table, "title")
	n.Body = field.NewString(table, "body")
	n.Link = field.NewString(table, "link")
	n.DedupeKey = field.NewString(table, "dedupe_key")
	n.CreatedAt = field.NewInt64(table, "created_at")
	n.ReadAt = field.NewInt64(table, "read_at")
	n.AcknowledgedAt = field.NewInt64(table, "acknowledged_at")

	n.fillFieldMap()

	return n
}

func (n *notificationRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationRecord) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 11)
	n.fieldMap["id"] = n.ID
	n.fieldMap["source"] = n.Source
	n.fieldMap["source_id"] = n.SourceID
	n.fieldMap["severity"] = n.Severity
	n.fieldMap["title"] = n.Title
	n.fieldMap["body"] = n.Body
	n.fieldMap["link"] = n.Link
	n.fieldMap["dedupe_key"] = n.DedupeKey
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["read_at"] = n.ReadAt
	n.fieldMap["acknowledged_at"] = n.AcknowledgedAt
}

func (n notificationRecord) clone(db *gorm.DB) notificationRecord {
	n.notificationRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationRecord) replaceDB(db *gorm.DB) notificationRecord {
	n.notificationRecordDo.ReplaceDB(db)
	return n
}

type notificationRecordDo struct{ gen.DO }

type INotificationRecordDo interface {
	gen.SubQuery
	Debug() INotificationRecordDo
	WithContext(ctx context.Context) INotificationRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationRecordDo
	WriteDB() INotificationRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationRecordDo
	Not(conds ...gen.Condition) INotificationRecordDo
	Or(conds ...gen.Condition) INotificationRecordDo
	Select(conds ...field.Expr) INotificationRecordDo
	Where(conds ...gen.Condition) INotificationRecordDo
	Order(conds ...field.Expr) INotificationRecordDo
	Distinct(cols ...field.Expr) INotificationRecordDo
	Omit(cols ...field.Expr) INotificationRecordDo
	Join(table schema.Tabler, on ...field.Expr) INotificationRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationRecordDo
	Group(cols ...field.Expr) INotificationRecordDo
	Having(conds ...gen.Condition) INotificationRecordDo
	Limit(limit int) INotificationRecordDo
	Offset(offset int) INotificationRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationRecordDo
	Unscoped() INotificationRecordDo
	Create(values ...*model.NotificationRecord) error
	CreateInBatches(values []*model.NotificationRecord, batchSize int) error
	Save(values ...*model.NotificationRecord) error
	First() (*model.NotificationRecord, error)
	Take() (*model.NotificationRecord, error)
	Last() (*model.NotificationRecord, error)
	Find() ([]*model.NotificationRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationRecord, err error)
	FindInBatches(result *[]*model.NotificationRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotificationRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationRecordDo
	Assign(attrs ...field.AssignExpr) INotificationRecordDo
	Joins(fields ...field.RelationField) INotificationRecordDo
	Preload(fields ...field.RelationField) INotificationRecordDo
	FirstOrInit() (*model.NotificationRecord, error)
	FirstOrCreate() (*model.NotificationRecord, error)
	FindByPage(offset int, limit int) (result []*model.NotificationRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notificationRecordDo) Debug() INotificationRecordDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationRecordDo) WithContext(ctx context.Context) INotificationRecordDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationRecordDo) ReadDB() INotificationRecordDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationRecordDo) WriteDB() INotificationRecordDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationRecordDo) Session(config *gorm.Session) INotificationRecordDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationRecordDo) Clauses(conds ...clause.Expression) INotificationRecordDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationRecordDo) Returning(value interface{}, columns ...string) INotificationRecordDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationRecordDo) Not(conds ...gen.Condition) INotificationRecordDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationRecordDo) Or(conds ...gen.Condition) INotificationRecordDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationRecordDo) Select(conds ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationRecordDo) Where(conds ...gen.Condition) INotificationRecordDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationRecordDo) Order(conds ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationRecordDo) Distinct(cols ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationRecordDo) Omit(cols ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationRecordDo) Join(table schema.Tabler, on ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationRecordDo) Group(cols ...field.Expr) INotificationRecordDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationRecordDo) Having(conds ...gen.Condition) INotificationRecordDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationRecordDo) Limit(limit int) INotificationRecordDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationRecordDo) Offset(offset int) INotificationRecordDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationRecordDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationRecordDo) Unscoped() INotificationRecordDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationRecordDo) Create(values ...*model.NotificationRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationRecordDo) CreateInBatches(values []*model.NotificationRecord, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationRecordDo) Save(values ...*model.NotificationRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationRecordDo) First() (*model.NotificationRecord, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationRecord), nil
	}
}

func (n notificationRecordDo) Take() (*model.NotificationRecord, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationRecord), nil
	}
}

func (n notificationRecordDo) Last() (*model.NotificationRecord, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationRecord), nil
	}
}

func (n notificationRecordDo) Find() ([]*model.NotificationRecord, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationRecord), err
}

func (n notificationRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationRecord, err error) {
	buf := make([]*model.NotificationRecord, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationRecordDo) FindInBatches(result *[]*model.NotificationRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationRecordDo) Attrs(attrs ...field.AssignExpr) INotificationRecordDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationRecordDo) Assign(attrs ...field.AssignExpr) INotificationRecordDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationRecordDo) Joins(fields ...field.RelationField) INotificationRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationRecordDo) Preload(fields ...field.RelationField) INotificationRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationRecordDo) FirstOrInit() (*model.NotificationRecord, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationRecord), nil
	}
}

func (n notificationRecordDo) FirstOrCreate() (*model.NotificationRecord, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationRecord), nil
	}
}

func (n notificationRecordDo) FindByPage(offset int, limit int) (result []*model.NotificationRecord, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationRecordDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationRecordDo) Delete(models ...*model.NotificationRecord) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationRecordDo) withDO(do gen.Dao) *notificationRecordDo {
	n.DO = *do.(*gen.DO)
	return n
}
