// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newSession(db *gorm.DB, opts ...gen.DOOption) session {
	_session := session{}

	_session.sessionDo.UseDB(db, opts...)
	_session.sessionDo.UseModel(&model.Session{})

	tableName := _session.sessionDo.TableName()
	_session.ALL = field.NewAsterisk(tableName)
	_session.ID = field.NewString(tableName, "id")
	_session.Label = field.NewString(tableName, "label")
	_session.CreatedAt = field.NewInt64(tableName, "created_at")
	_session.IsBaseline = field.NewBool(tableName, "is_baseline")
	_session.IsImported = field.NewBool(tableName, "is_imported")
	_session.SpanCount = field.NewInt(tableName, "span_count")
	_session.Services = field.NewString(tableName, "services")
	_session.Note = field.NewString(tableName, "note")
	_session.LastActivityNs = field.NewInt64(tableName, "last_activity_ns")

	_session.fillFieldMap()

	return _session
}

type session struct {
	sessionDo

	ALL            field.Asterisk
	ID             field.String
	Label          field.String
	CreatedAt      field.Int64
	IsBaseline     field.Bool
	IsImported     field.Bool
	SpanCount      field.Int
	Services       field.String
	Note           field.String
	LastActivityNs field.Int64

	fieldMap map[string]field.Expr
}

func (s session) Table(newTableName string) *session {
	s.sessionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s session) As(alias string) *session {
	s.sessionDo.DO = *(s.sessionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *session) updateTableName(table string) *session {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Label = field.NewString(table, "label")
	s.CreatedAt = field.NewInt64(table, "created_at")
	s.IsBaseline = field.NewBool(table, "is_baseline")
	s.IsImported = field.NewBool(table, "is_imported")
	s.SpanCount = field.NewInt(table, "span_count")
	s.Services = field.NewString(table, "services")
	s.Note = field.NewString(table, "note")
	s.LastActivityNs = field.NewInt64(table, "last_activity_ns")

	s.fillFieldMap()

	return s
}

func (s *session) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *session) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["label"] = s.Label
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["is_baseline"] = s.IsBaseline
	s.fieldMap["is_imported"] = s.IsImported
	s.fieldMap["span_count"] = s.SpanCount
	s.fieldMap["services"] = s.Services
	s.fieldMap["note"] = s.Note
	s.fieldMap["last_activity_ns"] = s.LastActivityNs
}

func (s session) clone(db *gorm.DB) session {
	s.sessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s session) replaceDB(db *gorm.DB) session {
	s.sessionDo.ReplaceDB(db)
	return s
}

type sessionDo struct{ gen.DO }

type ISessionDo interface {
	gen.SubQuery
	Debug() ISessionDo
	WithContext(ctx context.Context) ISessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionDo
	WriteDB() ISessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionDo
	Not(conds ...gen.Condition) ISessionDo
	Or(conds ...gen.Condition) ISessionDo
	Select(conds ...field.Expr) ISessionDo
	Where(conds ...gen.Condition) ISessionDo
	Order(conds ...field.Expr) ISessionDo
	Distinct(cols ...field.Expr) ISessionDo
	Omit(cols ...field.Expr) ISessionDo
	Join(table schema.Tabler, on ...field.Expr) ISessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionDo
	Group(cols ...field.Expr) ISessionDo
	Having(conds ...gen.Condition) ISessionDo
	Limit(limit int) ISessionDo
	Offset(offset int) ISessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDo
	Unscoped() ISessionDo
	Create(values ...*model.Session) error
	CreateInBatches(values []*model.Session, batchSize int) error
	Save(values ...*model.Session) error
	First() (*model.Session, error)
	Take() (*model.Session, error)
	Last() (*model.Session, error)
	Find() ([]*model.Session, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Session, err error)
	FindInBatches(result *[]*model.Session, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Session) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionDo
	Assign(attrs ...field.AssignExpr) ISessionDo
	Joins(fields ...field.RelationField) ISessionDo
	Preload(fields ...field.RelationField) ISessionDo
	FirstOrInit() (*model.Session, error)
	FirstOrCreate() (*model.Session, error)
	FindByPage(offset int, limit int) (result []*model.Session, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	SearchByLabel(pattern string, limit int) (result []model.SearchResult, err error)
	GetByID(id string) (result []model.Session, err error)
	ListWithStats() (result []model.SessionSummary, err error)
}

// SearchByLabel
//
// SELECT 'session' AS kind, ” AS trace_id, ” AS span_id, label AS title, CASE WHEN is_baseline THEN 'baseline' ELSE 'session' END AS subtitle, id AS session_id FROM @@table WHERE label ILIKE @pattern ORDER BY created_at DESC LIMIT @limit
func (s sessionDo) SearchByLabel(pattern string, limit int) (result []model.SearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, pattern)
	params = append(params, limit)
	generateSQL.WriteString("SELECT 'session' AS kind, '' AS trace_id, '' AS span_id, label AS title, CASE WHEN is_baseline THEN 'baseline' ELSE 'session' END AS subtitle, id AS session_id FROM sessions WHERE label ILIKE ? ORDER BY created_at DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByID
//
// SELECT id, label, created_at, is_baseline, is_imported, span_count, services::VARCHAR AS services, COALESCE(note, ”) AS note, COALESCE(last_activity_ns, 0) AS last_activity_ns FROM @@table WHERE id = @id LIMIT 1
func (s sessionDo) GetByID(id string) (result []model.Session, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT id, label, created_at, is_baseline, is_imported, span_count, services::VARCHAR AS services, COALESCE(note, '') AS note, COALESCE(last_activity_ns, 0) AS last_activity_ns FROM sessions WHERE id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListWithStats
//
// SELECT s.id, s.label, s.created_at, s.is_baseline, s.is_imported, s.span_count, s.services::VARCHAR AS services, COALESCE(s.note, ”) AS note, COALESCE(s.last_activity_ns, 0) AS last_activity_ns, COUNT(DISTINCT sp.trace_id) AS trace_count, CAST(COALESCE(QUANTILE_CONT(sp.duration_ns, 0.95), 0) AS BIGINT) AS p95_ns, COALESCE(SUM(LENGTH(sp.attributes::VARCHAR) + LENGTH(sp.resource::VARCHAR)), 0) AS size_bytes, COALESCE(ni.n1_count, 0) AS n1_count, COUNT(*) FILTER (WHERE sp.status_code = 2) AS error_count FROM @@table s LEFT JOIN spans sp ON sp.session_id = s.id LEFT JOIN (SELECT session_id, COUNT(*) AS n1_count FROM trace_issues WHERE kind = 'n_plus_one' GROUP BY session_id) ni ON ni.session_id = s.id GROUP BY s.id, s.label, s.created_at, s.is_baseline, s.is_imported, s.span_count, s.services, s.note, s.last_activity_ns, ni.n1_count ORDER BY s.created_at DESC
func (s sessionDo) ListWithStats() (result []model.SessionSummary, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT s.id, s.label, s.created_at, s.is_baseline, s.is_imported, s.span_count, s.services::VARCHAR AS services, COALESCE(s.note, '') AS note, COALESCE(s.last_activity_ns, 0) AS last_activity_ns, COUNT(DISTINCT sp.trace_id) AS trace_count, CAST(COALESCE(QUANTILE_CONT(sp.duration_ns, 0.95), 0) AS BIGINT) AS p95_ns, COALESCE(SUM(LENGTH(sp.attributes::VARCHAR) + LENGTH(sp.resource::VARCHAR)), 0) AS size_bytes, COALESCE(ni.n1_count, 0) AS n1_count, COUNT(*) FILTER (WHERE sp.status_code = 2) AS error_count FROM sessions s LEFT JOIN spans sp ON sp.session_id = s.id LEFT JOIN (SELECT session_id, COUNT(*) AS n1_count FROM trace_issues WHERE kind = 'n_plus_one' GROUP BY session_id) ni ON ni.session_id = s.id GROUP BY s.id, s.label, s.created_at, s.is_baseline, s.is_imported, s.span_count, s.services, s.note, s.last_activity_ns, ni.n1_count ORDER BY s.created_at DESC ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s sessionDo) Debug() ISessionDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionDo) WithContext(ctx context.Context) ISessionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionDo) ReadDB() ISessionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionDo) WriteDB() ISessionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionDo) Session(config *gorm.Session) ISessionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionDo) Clauses(conds ...clause.Expression) ISessionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionDo) Returning(value interface{}, columns ...string) ISessionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionDo) Not(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionDo) Or(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionDo) Select(conds ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionDo) Where(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionDo) Order(conds ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionDo) Distinct(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionDo) Omit(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionDo) Join(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionDo) Group(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionDo) Having(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionDo) Limit(limit int) ISessionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionDo) Offset(offset int) ISessionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionDo) Unscoped() ISessionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionDo) Create(values ...*model.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionDo) CreateInBatches(values []*model.Session, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionDo) Save(values ...*model.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionDo) First() (*model.Session, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Take() (*model.Session, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Last() (*model.Session, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Find() ([]*model.Session, error) {
	result, err := s.DO.Find()
	return result.([]*model.Session), err
}

func (s sessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Session, err error) {
	buf := make([]*model.Session, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionDo) FindInBatches(result *[]*model.Session, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionDo) Attrs(attrs ...field.AssignExpr) ISessionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionDo) Assign(attrs ...field.AssignExpr) ISessionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionDo) Joins(fields ...field.RelationField) ISessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionDo) Preload(fields ...field.RelationField) ISessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionDo) FirstOrInit() (*model.Session, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) FirstOrCreate() (*model.Session, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) FindByPage(offset int, limit int) (result []*model.Session, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionDo) Delete(models ...*model.Session) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionDo) withDO(do gen.Dao) *sessionDo {
	s.DO = *do.(*gen.DO)
	return s
}
