// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newSpanEvent(db *gorm.DB, opts ...gen.DOOption) spanEvent {
	_spanEvent := spanEvent{}

	_spanEvent.spanEventDo.UseDB(db, opts...)
	_spanEvent.spanEventDo.UseModel(&model.SpanEvent{})

	tableName := _spanEvent.spanEventDo.TableName()
	_spanEvent.ALL = field.NewAsterisk(tableName)
	_spanEvent.SpanID = field.NewString(tableName, "span_id")
	_spanEvent.TraceID = field.NewString(tableName, "trace_id")
	_spanEvent.SessionID = field.NewString(tableName, "session_id")
	_spanEvent.TimeNs = field.NewInt64(tableName, "time_ns")
	_spanEvent.Name = field.NewString(tableName, "name")
	_spanEvent.Attributes = field.NewString(tableName, "attributes")

	_spanEvent.fillFieldMap()

	return _spanEvent
}

type spanEvent struct {
	spanEventDo

	ALL        field.Asterisk
	SpanID     field.String
	TraceID    field.String
	SessionID  field.String
	TimeNs     field.Int64
	Name       field.String
	Attributes field.String

	fieldMap map[string]field.Expr
}

func (s spanEvent) Table(newTableName string) *spanEvent {
	s.spanEventDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s spanEvent) As(alias string) *spanEvent {
	s.spanEventDo.DO = *(s.spanEventDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *spanEvent) updateTableName(table string) *spanEvent {
	s.ALL = field.NewAsterisk(table)
	s.SpanID = field.NewString(table, "span_id")
	s.TraceID = field.NewString(table, "trace_id")
	s.SessionID = field.NewString(table, "session_id")
	s.TimeNs = field.NewInt64(table, "time_ns")
	s.Name = field.NewString(table, "name")
	s.Attributes = field.NewString(table, "attributes")

	s.fillFieldMap()

	return s
}

func (s *spanEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *spanEvent) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["span_id"] = s.SpanID
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["time_ns"] = s.TimeNs
	s.fieldMap["name"] = s.Name
	s.fieldMap["attributes"] = s.Attributes
}

func (s spanEvent) clone(db *gorm.DB) spanEvent {
	s.spanEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s spanEvent) replaceDB(db *gorm.DB) spanEvent {
	s.spanEventDo.ReplaceDB(db)
	return s
}

type spanEventDo struct{ gen.DO }

type ISpanEventDo interface {
	gen.SubQuery
	Debug() ISpanEventDo
	WithContext(ctx context.Context) ISpanEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpanEventDo
	WriteDB() ISpanEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpanEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpanEventDo
	Not(conds ...gen.Condition) ISpanEventDo
	Or(conds ...gen.Condition) ISpanEventDo
	Select(conds ...field.Expr) ISpanEventDo
	Where(conds ...gen.Condition) ISpanEventDo
	Order(conds ...field.Expr) ISpanEventDo
	Distinct(cols ...field.Expr) ISpanEventDo
	Omit(cols ...field.Expr) ISpanEventDo
	Join(table schema.Tabler, on ...field.Expr) ISpanEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpanEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpanEventDo
	Group(cols ...field.Expr) ISpanEventDo
	Having(conds ...gen.Condition) ISpanEventDo
	Limit(limit int) ISpanEventDo
	Offset(offset int) ISpanEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanEventDo
	Unscoped() ISpanEventDo
	Create(values ...*model.SpanEvent) error
	CreateInBatches(values []*model.SpanEvent, batchSize int) error
	Save(values ...*model.SpanEvent) error
	First() (*model.SpanEvent, error)
	Take() (*model.SpanEvent, error)
	Last() (*model.SpanEvent, error)
	Find() ([]*model.SpanEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpanEvent, err error)
	FindInBatches(result *[]*model.SpanEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SpanEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpanEventDo
	Assign(attrs ...field.AssignExpr) ISpanEventDo
	Joins(fields ...field.RelationField) ISpanEventDo
	Preload(fields ...field.RelationField) ISpanEventDo
	FirstOrInit() (*model.SpanEvent, error)
	FirstOrCreate() (*model.SpanEvent, error)
	FindByPage(offset int, limit int) (result []*model.SpanEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpanEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ListBySpan(spanID string) (result []model.SpanEvent, err error)
}

// ListBySpan
//
// SELECT span_id, trace_id, session_id, time_ns, name, attributes::VARCHAR AS attributes FROM @@table WHERE span_id = @spanID ORDER BY time_ns ASC
func (s spanEventDo) ListBySpan(spanID string) (result []model.SpanEvent, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, spanID)
	generateSQL.WriteString("SELECT span_id, trace_id, session_id, time_ns, name, attributes::VARCHAR AS attributes FROM span_events WHERE span_id = ? ORDER BY time_ns ASC ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s spanEventDo) Debug() ISpanEventDo {
	return s.withDO(s.DO.Debug())
}

func (s spanEventDo) WithContext(ctx context.Context) ISpanEventDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spanEventDo) ReadDB() ISpanEventDo {
	return s.Clauses(dbresolver.Read)
}

func (s spanEventDo) WriteDB() ISpanEventDo {
	return s.Clauses(dbresolver.Write)
}

func (s spanEventDo) Session(config *gorm.Session) ISpanEventDo {
	return s.withDO(s.DO.Session(config))
}

func (s spanEventDo) Clauses(conds ...clause.Expression) ISpanEventDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spanEventDo) Returning(value interface{}, columns ...string) ISpanEventDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spanEventDo) Not(conds ...gen.Condition) ISpanEventDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spanEventDo) Or(conds ...gen.Condition) ISpanEventDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spanEventDo) Select(conds ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spanEventDo) Where(conds ...gen.Condition) ISpanEventDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spanEventDo) Order(conds ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spanEventDo) Distinct(cols ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spanEventDo) Omit(cols ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spanEventDo) Join(table schema.Tabler, on ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spanEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spanEventDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spanEventDo) Group(cols ...field.Expr) ISpanEventDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spanEventDo) Having(conds ...gen.Condition) ISpanEventDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spanEventDo) Limit(limit int) ISpanEventDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spanEventDo) Offset(offset int) ISpanEventDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spanEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanEventDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spanEventDo) Unscoped() ISpanEventDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spanEventDo) Create(values ...*model.SpanEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spanEventDo) CreateInBatches(values []*model.SpanEvent, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spanEventDo) Save(values ...*model.SpanEvent) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spanEventDo) First() (*model.SpanEvent, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanEvent), nil
	}
}

func (s spanEventDo) Take() (*model.SpanEvent, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanEvent), nil
	}
}

func (s spanEventDo) Last() (*model.SpanEvent, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanEvent), nil
	}
}

func (s spanEventDo) Find() ([]*model.SpanEvent, error) {
	result, err := s.DO.Find()
	return result.([]*model.SpanEvent), err
}

func (s spanEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpanEvent, err error) {
	buf := make([]*model.SpanEvent, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spanEventDo) FindInBatches(result *[]*model.SpanEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spanEventDo) Attrs(attrs ...field.AssignExpr) ISpanEventDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spanEventDo) Assign(attrs ...field.AssignExpr) ISpanEventDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spanEventDo) Joins(fields ...field.RelationField) ISpanEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spanEventDo) Preload(fields ...field.RelationField) ISpanEventDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spanEventDo) FirstOrInit() (*model.SpanEvent, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanEvent), nil
	}
}

func (s spanEventDo) FirstOrCreate() (*model.SpanEvent, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanEvent), nil
	}
}

func (s spanEventDo) FindByPage(offset int, limit int) (result []*model.SpanEvent, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spanEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spanEventDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spanEventDo) Delete(models ...*model.SpanEvent) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spanEventDo) withDO(do gen.Dao) *spanEventDo {
	s.DO = *do.(*gen.DO)
	return s
}
