// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newSpan(db *gorm.DB, opts ...gen.DOOption) span {
	_span := span{}

	_span.spanDo.UseDB(db, opts...)
	_span.spanDo.UseModel(&model.Span{})

	tableName := _span.spanDo.TableName()
	_span.ALL = field.NewAsterisk(tableName)
	_span.TraceID = field.NewString(tableName, "trace_id")
	_span.SpanID = field.NewString(tableName, "span_id")
	_span.ParentSpanID = field.NewString(tableName, "parent_span_id")
	_span.ServiceName = field.NewString(tableName, "service_name")
	_span.Name = field.NewString(tableName, "name")
	_span.Kind = field.NewInt(tableName, "kind")
	_span.StartNs = field.NewInt64(tableName, "start_ns")
	_span.EndNs = field.NewInt64(tableName, "end_ns")
	_span.DurationNs = field.NewInt64(tableName, "duration_ns")
	_span.StatusCode = field.NewInt(tableName, "status_code")
	_span.StatusMessage = field.NewString(tableName, "status_message")
	_span.Attributes = field.NewString(tableName, "attributes")
	_span.Resource = field.NewString(tableName, "resource")
	_span.SessionID = field.NewString(tableName, "session_id")
	_span.SessionLabel = field.NewString(tableName, "session_label")
	_span.ReceivedAt = field.NewInt64(tableName, "received_at")
	_span.Sampled = field.NewBool(tableName, "sampled")

	_span.fillFieldMap()

	return _span
}

type span struct {
	spanDo

	ALL           field.Asterisk
	TraceID       field.String
	SpanID        field.String
	ParentSpanID  field.String
	ServiceName   field.String
	Name          field.String
	Kind          field.Int
	StartNs       field.Int64
	EndNs         field.Int64
	DurationNs    field.Int64
	StatusCode    field.Int
	StatusMessage field.String
	Attributes    field.String
	Resource      field.String
	SessionID     field.String
	SessionLabel  field.String
	ReceivedAt    field.Int64
	Sampled       field.Bool

	fieldMap map[string]field.Expr
}

func (s span) Table(newTableName string) *span {
	s.spanDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s span) As(alias string) *span {
	s.spanDo.DO = *(s.spanDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *span) updateTableName(table string) *span {
	s.ALL = field.NewAsterisk(table)
	s.TraceID = field.NewString(table, "trace_id")
	s.SpanID = field.NewString(table, "span_id")
	s.ParentSpanID = field.NewString(table, "parent_span_id")
	s.ServiceName = field.NewString(table, "service_name")
	s.Name = field.NewString(table, "name")
	s.Kind = field.NewInt(table, "kind")
	s.StartNs = field.NewInt64(table, "start_ns")
	s.EndNs = field.NewInt64(table, "end_ns")
	s.DurationNs = field.NewInt64(table, "duration_ns")
	s.StatusCode = field.NewInt(table, "status_code")
	s.StatusMessage = field.NewString(table, "status_message")
	s.Attributes = field.NewString(table, "attributes")
	s.Resource = field.NewString(table, "resource")
	s.SessionID = field.NewString(table, "session_id")
	s.SessionLabel = field.NewString(table, "session_label")
	s.ReceivedAt = field.NewInt64(table, "received_at")
	s.Sampled = field.NewBool(table, "sampled")

	s.fillFieldMap()

	return s
}

func (s *span) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *span) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["span_id"] = s.SpanID
	s.fieldMap["parent_span_id"] = s.ParentSpanID
	s.fieldMap["service_name"] = s.ServiceName
	s.fieldMap["name"] = s.Name
	s.fieldMap["kind"] = s.Kind
	s.fieldMap["start_ns"] = s.StartNs
	s.fieldMap["end_ns"] = s.EndNs
	s.fieldMap["duration_ns"] = s.DurationNs
	s.fieldMap["status_code"] = s.StatusCode
	s.fieldMap["status_message"] = s.StatusMessage
	s.fieldMap["attributes"] = s.Attributes
	s.fieldMap["resource"] = s.Resource
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["session_label"] = s.SessionLabel
	s.fieldMap["received_at"] = s.ReceivedAt
	s.fieldMap["sampled"] = s.Sampled
}

func (s span) clone(db *gorm.DB) span {
	s.spanDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s span) replaceDB(db *gorm.DB) span {
	s.spanDo.ReplaceDB(db)
	return s
}

type spanDo struct{ gen.DO }

type ISpanDo interface {
	gen.SubQuery
	Debug() ISpanDo
	WithContext(ctx context.Context) ISpanDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpanDo
	WriteDB() ISpanDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpanDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpanDo
	Not(conds ...gen.Condition) ISpanDo
	Or(conds ...gen.Condition) ISpanDo
	Select(conds ...field.Expr) ISpanDo
	Where(conds ...gen.Condition) ISpanDo
	Order(conds ...field.Expr) ISpanDo
	Distinct(cols ...field.Expr) ISpanDo
	Omit(cols ...field.Expr) ISpanDo
	Join(table schema.Tabler, on ...field.Expr) ISpanDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpanDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpanDo
	Group(cols ...field.Expr) ISpanDo
	Having(conds ...gen.Condition) ISpanDo
	Limit(limit int) ISpanDo
	Offset(offset int) ISpanDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanDo
	Unscoped() ISpanDo
	Create(values ...*model.Span) error
	CreateInBatches(values []*model.Span, batchSize int) error
	Save(values ...*model.Span) error
	First() (*model.Span, error)
	Take() (*model.Span, error)
	Last() (*model.Span, error)
	Find() ([]*model.Span, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Span, err error)
	FindInBatches(result *[]*model.Span, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Span) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpanDo
	Assign(attrs ...field.AssignExpr) ISpanDo
	Joins(fields ...field.RelationField) ISpanDo
	Preload(fields ...field.RelationField) ISpanDo
	FirstOrInit() (*model.Span, error)
	FirstOrCreate() (*model.Span, error)
	FindByPage(offset int, limit int) (result []*model.Span, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpanDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	SearchTraces(sessionID string, pattern string, tracePrefix string, limit int) (result []model.SearchResult, err error)
	SearchChildSpans(sessionID string, pattern string, limit int) (result []model.SearchResult, err error)
	SearchServices(sessionID string, pattern string, limit int) (result []model.SearchResult, err error)
	ListTraceOverlays(service string, sessionID string, fromNs int64, toNs int64, limit int) (result []model.TraceOverlay, err error)
	ListCoverageOperations(sessionID string) (result []model.CoverageOperation, err error)
	GetCoverageQuality(sessionID string) (result []model.CoverageQuality, err error)
	ListTagged(sessionID string, service string, name string, hasKind bool, kind int, sort string, limit int, offset int) (result []model.SpanRow, err error)
	ListGroups(sessionID string, limit int, offset int) (result []model.SpanGroup, err error)
	ListTraces(sessionID string, service string, limit int, offset int) (result []model.TraceListRow, err error)
	CountGroups(sessionID string) (result []model.CountValue, err error)
	CountTraces(sessionID string, service string) (result []model.CountValue, err error)
	ListSourceStats(sessionID string) (result []model.SourceStatsRow, err error)
	ServiceP95(serviceName string) (result []model.P95Value, err error)
	ListServiceMapNodes(sessionID string) (result []model.ServiceMapNode, err error)
	ListServiceMapEdges(sessionID string) (result []model.ServiceMapEdge, err error)
	ListTopOperations(service string, sessionID string, limit int) (result []model.ServiceMapOpStat, err error)
	GetStats(sessionID string) (result []model.StatsRow, err error)
	StorageTableSizes() (result []model.TableSizeRow, err error)
	TopSessionSizes() (result []model.SessionSize, err error)
}

// SearchTraces
//
// SELECT 'trace' AS kind, trace_id, ” AS span_id, MIN(name) AS title, MIN(service_name) AS subtitle, MIN(session_id) AS session_id FROM spans WHERE (@sessionID = ” OR session_id = @sessionID) AND (name ILIKE @pattern OR service_name ILIKE @pattern OR trace_id ILIKE @tracePrefix OR attributes::VARCHAR ILIKE @pattern) GROUP BY trace_id ORDER BY MAX(start_ns) DESC LIMIT @limit
func (s spanDo) SearchTraces(sessionID string, pattern string, tracePrefix string, limit int) (result []model.SearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, pattern)
	params = append(params, pattern)
	params = append(params, tracePrefix)
	params = append(params, pattern)
	params = append(params, limit)
	generateSQL.WriteString("SELECT 'trace' AS kind, trace_id, '' AS span_id, MIN(name) AS title, MIN(service_name) AS subtitle, MIN(session_id) AS session_id FROM spans WHERE (? = '' OR session_id = ?) AND (name ILIKE ? OR service_name ILIKE ? OR trace_id ILIKE ? OR attributes::VARCHAR ILIKE ?) GROUP BY trace_id ORDER BY MAX(start_ns) DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SearchChildSpans
//
// SELECT 'span' AS kind, trace_id, span_id, name AS title, service_name AS subtitle, session_id FROM spans WHERE (@sessionID = ” OR session_id = @sessionID) AND parent_span_id IS NOT NULL AND parent_span_id != ” AND (name ILIKE @pattern OR attributes::VARCHAR ILIKE @pattern) ORDER BY start_ns DESC LIMIT @limit
func (s spanDo) SearchChildSpans(sessionID string, pattern string, limit int) (result []model.SearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, pattern)
	params = append(params, pattern)
	params = append(params, limit)
	generateSQL.WriteString("SELECT 'span' AS kind, trace_id, span_id, name AS title, service_name AS subtitle, session_id FROM spans WHERE (? = '' OR session_id = ?) AND parent_span_id IS NOT NULL AND parent_span_id != '' AND (name ILIKE ? OR attributes::VARCHAR ILIKE ?) ORDER BY start_ns DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// SearchServices
//
// SELECT 'service' AS kind, ” AS trace_id, ” AS span_id, service_name AS title, CONCAT(CAST(COUNT(*) AS VARCHAR), ' spans') AS subtitle, COALESCE(MIN(session_id), ”) AS session_id FROM spans WHERE service_name ILIKE @pattern AND (@sessionID = ” OR session_id = @sessionID) GROUP BY service_name ORDER BY COUNT(*) DESC LIMIT @limit
func (s spanDo) SearchServices(sessionID string, pattern string, limit int) (result []model.SearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, pattern)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, limit)
	generateSQL.WriteString("SELECT 'service' AS kind, '' AS trace_id, '' AS span_id, service_name AS title, CONCAT(CAST(COUNT(*) AS VARCHAR), ' spans') AS subtitle, COALESCE(MIN(session_id), '') AS session_id FROM spans WHERE service_name ILIKE ? AND (? = '' OR session_id = ?) GROUP BY service_name ORDER BY COUNT(*) DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTraceOverlays
//
// SELECT trace_id, name AS op, service_name AS service, status_code, start_ns, end_ns, duration_ns FROM @@table WHERE (parent_span_id = ” OR parent_span_id IS NULL) AND (@service = ” OR service_name = @service) AND (@sessionID = ” OR session_id = @sessionID) AND (@fromNs = 0 OR start_ns >= @fromNs) AND (@toNs = 0 OR start_ns <= @toNs) ORDER BY start_ns ASC LIMIT @limit
func (s spanDo) ListTraceOverlays(service string, sessionID string, fromNs int64, toNs int64, limit int) (result []model.TraceOverlay, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, service)
	params = append(params, service)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, fromNs)
	params = append(params, fromNs)
	params = append(params, toNs)
	params = append(params, toNs)
	params = append(params, limit)
	generateSQL.WriteString("SELECT trace_id, name AS op, service_name AS service, status_code, start_ns, end_ns, duration_ns FROM spans WHERE (parent_span_id = '' OR parent_span_id IS NULL) AND (? = '' OR service_name = ?) AND (? = '' OR session_id = ?) AND (? = 0 OR start_ns >= ?) AND (? = 0 OR start_ns <= ?) ORDER BY start_ns ASC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListCoverageOperations
//
// WITH operations AS (SELECT service_name, CASE WHEN json_extract_string(attributes, '$."http.route"') != ” THEN COALESCE(NULLIF(json_extract_string(attributes, '$."http.request.method"'), ”), NULLIF(json_extract_string(attributes, '$."http.method"'), ”), 'GET') WHEN json_extract_string(attributes, '$."rpc.method"') != ” THEN 'RPC' WHEN kind = 2 AND name != ” THEN ” END AS method, CASE WHEN json_extract_string(attributes, '$."http.route"') != ” THEN json_extract_string(attributes, '$."http.route"') WHEN json_extract_string(attributes, '$."rpc.method"') != ” THEN CASE WHEN json_extract_string(attributes, '$."rpc.service"') != ” THEN json_extract_string(attributes, '$."rpc.service"') || '.' || json_extract_string(attributes, '$."rpc.method"') ELSE json_extract_string(attributes, '$."rpc.method"') END WHEN kind = 2 AND name != ” THEN name END AS path, duration_ns, start_ns FROM @@table WHERE session_id = @sessionID) SELECT service_name, method, path, COUNT(*) AS hits, CAST(quantile_disc(duration_ns, 0.95) AS BIGINT) AS p95_ns, MAX(start_ns) AS last_seen_ns FROM operations WHERE path IS NOT NULL AND path != ” GROUP BY service_name, method, path
func (s spanDo) ListCoverageOperations(sessionID string) (result []model.CoverageOperation, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	generateSQL.WriteString("WITH operations AS (SELECT service_name, CASE WHEN json_extract_string(attributes, '$.\"http.route\"') != '' THEN COALESCE(NULLIF(json_extract_string(attributes, '$.\"http.request.method\"'), ''), NULLIF(json_extract_string(attributes, '$.\"http.method\"'), ''), 'GET') WHEN json_extract_string(attributes, '$.\"rpc.method\"') != '' THEN 'RPC' WHEN kind = 2 AND name != '' THEN '' END AS method, CASE WHEN json_extract_string(attributes, '$.\"http.route\"') != '' THEN json_extract_string(attributes, '$.\"http.route\"') WHEN json_extract_string(attributes, '$.\"rpc.method\"') != '' THEN CASE WHEN json_extract_string(attributes, '$.\"rpc.service\"') != '' THEN json_extract_string(attributes, '$.\"rpc.service\"') || '.' || json_extract_string(attributes, '$.\"rpc.method\"') ELSE json_extract_string(attributes, '$.\"rpc.method\"') END WHEN kind = 2 AND name != '' THEN name END AS path, duration_ns, start_ns FROM spans WHERE session_id = ?) SELECT service_name, method, path, COUNT(*) AS hits, CAST(quantile_disc(duration_ns, 0.95) AS BIGINT) AS p95_ns, MAX(start_ns) AS last_seen_ns FROM operations WHERE path IS NOT NULL AND path != '' GROUP BY service_name, method, path ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetCoverageQuality
//
// SELECT COUNT(*) FILTER (WHERE kind = 2 AND COALESCE(json_extract_string(attributes, '$."http.route"'), ”) = ”) AS missing_route_spans, COUNT(*) FILTER (WHERE json_extract_string(attributes, '$."http.route"') IN ('/', '/api/')) AS generic_route_spans, COUNT(*) FILTER (WHERE regexp_matches(COALESCE(json_extract_string(attributes, '$."http.route"'), ”), '/[0-9]+($|/)') OR regexp_matches(COALESCE(json_extract_string(attributes, '$."http.route"'), ”), '[0-9a-f]{8}-[0-9a-f-]{27,}')) AS dynamic_route_spans FROM @@table WHERE session_id = @sessionID
func (s spanDo) GetCoverageQuality(sessionID string) (result []model.CoverageQuality, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT COUNT(*) FILTER (WHERE kind = 2 AND COALESCE(json_extract_string(attributes, '$.\"http.route\"'), '') = '') AS missing_route_spans, COUNT(*) FILTER (WHERE json_extract_string(attributes, '$.\"http.route\"') IN ('/', '/api/')) AS generic_route_spans, COUNT(*) FILTER (WHERE regexp_matches(COALESCE(json_extract_string(attributes, '$.\"http.route\"'), ''), '/[0-9]+($|/)') OR regexp_matches(COALESCE(json_extract_string(attributes, '$.\"http.route\"'), ''), '[0-9a-f]{8}-[0-9a-f-]{27,}')) AS dynamic_route_spans FROM spans WHERE session_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTagged
//
// WITH page_spans AS (SELECT trace_id, span_id, parent_span_id, service_name, name, kind, start_ns, end_ns, duration_ns, status_code, status_message, attributes, resource, session_id, session_label, received_at FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) AND (@service = ” OR service_name = @service) AND (@name = ” OR name = @name) AND (@hasKind = FALSE OR kind = @kind) ORDER BY CASE WHEN @sort = 'name' THEN name END ASC, CASE WHEN @sort = 'dur' THEN duration_ns END DESC, CASE WHEN @sort NOT IN ('name', 'dur') THEN start_ns END DESC LIMIT @limit OFFSET @offset) SELECT s.trace_id, s.span_id, s.parent_span_id, s.service_name, s.name, s.kind, s.start_ns, s.end_ns, s.duration_ns, s.status_code, s.status_message, s.attributes::VARCHAR AS attributes, s.resource::VARCHAR AS resource, s.session_id, s.session_label, s.received_at, CASE WHEN ni.trace_id IS NOT NULL THEN 'n+1' WHEN s.status_code = 2 THEN 'error' WHEN s.duration_ns > 250000000 THEN 'slow' WHEN lw.span_id IS NOT NULL THEN 'lint' ELSE ” END AS tag FROM page_spans s LEFT JOIN (SELECT DISTINCT trace_id FROM trace_issues WHERE kind = 'n_plus_one') ni ON s.trace_id = ni.trace_id LEFT JOIN (SELECT DISTINCT span_id FROM lint_warnings) lw ON s.span_id = lw.span_id ORDER BY CASE WHEN @sort = 'name' THEN s.name END ASC, CASE WHEN @sort = 'dur' THEN s.duration_ns END DESC, CASE WHEN @sort NOT IN ('name', 'dur') THEN s.start_ns END DESC
func (s spanDo) ListTagged(sessionID string, service string, name string, hasKind bool, kind int, sort string, limit int, offset int) (result []model.SpanRow, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, service)
	params = append(params, service)
	params = append(params, name)
	params = append(params, name)
	params = append(params, hasKind)
	params = append(params, kind)
	params = append(params, sort)
	params = append(params, sort)
	params = append(params, sort)
	params = append(params, limit)
	params = append(params, offset)
	params = append(params, sort)
	params = append(params, sort)
	params = append(params, sort)
	generateSQL.WriteString("WITH page_spans AS (SELECT trace_id, span_id, parent_span_id, service_name, name, kind, start_ns, end_ns, duration_ns, status_code, status_message, attributes, resource, session_id, session_label, received_at FROM spans WHERE (? = '' OR session_id = ?) AND (? = '' OR service_name = ?) AND (? = '' OR name = ?) AND (? = FALSE OR kind = ?) ORDER BY CASE WHEN ? = 'name' THEN name END ASC, CASE WHEN ? = 'dur' THEN duration_ns END DESC, CASE WHEN ? NOT IN ('name', 'dur') THEN start_ns END DESC LIMIT ? OFFSET ?) SELECT s.trace_id, s.span_id, s.parent_span_id, s.service_name, s.name, s.kind, s.start_ns, s.end_ns, s.duration_ns, s.status_code, s.status_message, s.attributes::VARCHAR AS attributes, s.resource::VARCHAR AS resource, s.session_id, s.session_label, s.received_at, CASE WHEN ni.trace_id IS NOT NULL THEN 'n+1' WHEN s.status_code = 2 THEN 'error' WHEN s.duration_ns > 250000000 THEN 'slow' WHEN lw.span_id IS NOT NULL THEN 'lint' ELSE '' END AS tag FROM page_spans s LEFT JOIN (SELECT DISTINCT trace_id FROM trace_issues WHERE kind = 'n_plus_one') ni ON s.trace_id = ni.trace_id LEFT JOIN (SELECT DISTINCT span_id FROM lint_warnings) lw ON s.span_id = lw.span_id ORDER BY CASE WHEN ? = 'name' THEN s.name END ASC, CASE WHEN ? = 'dur' THEN s.duration_ns END DESC, CASE WHEN ? NOT IN ('name', 'dur') THEN s.start_ns END DESC ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListGroups
//
// SELECT service_name, name, kind, COUNT(*) AS count, MAX(start_ns) AS latest_start_ns, SUM(CASE WHEN status_code = 2 THEN 1 ELSE 0 END) AS error_count, CAST(quantile_cont(duration_ns, 0.5) AS BIGINT) AS p50_duration_ns, CAST(quantile_cont(duration_ns, 0.95) AS BIGINT) AS p95_duration_ns, MAX(duration_ns) AS max_duration_ns, COUNT(DISTINCT attributes) AS attribute_variants FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) GROUP BY service_name, name, kind ORDER BY latest_start_ns DESC, service_name, name LIMIT @limit OFFSET @offset
func (s spanDo) ListGroups(sessionID string, limit int, offset int) (result []model.SpanGroup, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("SELECT service_name, name, kind, COUNT(*) AS count, MAX(start_ns) AS latest_start_ns, SUM(CASE WHEN status_code = 2 THEN 1 ELSE 0 END) AS error_count, CAST(quantile_cont(duration_ns, 0.5) AS BIGINT) AS p50_duration_ns, CAST(quantile_cont(duration_ns, 0.95) AS BIGINT) AS p95_duration_ns, MAX(duration_ns) AS max_duration_ns, COUNT(DISTINCT attributes) AS attribute_variants FROM spans WHERE (? = '' OR session_id = ?) GROUP BY service_name, name, kind ORDER BY latest_start_ns DESC, service_name, name LIMIT ? OFFSET ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTraces
//
// WITH root_spans AS (SELECT trace_id, service_name, name, attributes::VARCHAR AS attributes, status_code, start_ns, end_ns, duration_ns, session_id, session_label FROM @@table WHERE (parent_span_id = ” OR parent_span_id IS NULL) AND (@sessionID = ” OR session_id = @sessionID) AND (@service = ” OR service_name = @service) ORDER BY start_ns DESC LIMIT @limit OFFSET @offset) SELECT rs.*, COALESCE(ti.has_n1, FALSE) AS has_n1, COALESCE(ti.issue_kinds_raw, ”) AS issue_kinds_raw, COALESCE(sc.span_count, 1) AS span_count FROM root_spans rs LEFT JOIN (SELECT trace_id, BOOL_OR(kind = 'n_plus_one') AS has_n1, string_agg(DISTINCT kind, ',') AS issue_kinds_raw FROM trace_issues WHERE trace_id IN (SELECT trace_id FROM root_spans) GROUP BY trace_id) ti ON rs.trace_id = ti.trace_id LEFT JOIN (SELECT trace_id, COUNT(*) AS span_count FROM spans WHERE trace_id IN (SELECT trace_id FROM root_spans) GROUP BY trace_id) sc ON rs.trace_id = sc.trace_id ORDER BY rs.start_ns DESC
func (s spanDo) ListTraces(sessionID string, service string, limit int, offset int) (result []model.TraceListRow, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, service)
	params = append(params, service)
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("WITH root_spans AS (SELECT trace_id, service_name, name, attributes::VARCHAR AS attributes, status_code, start_ns, end_ns, duration_ns, session_id, session_label FROM spans WHERE (parent_span_id = '' OR parent_span_id IS NULL) AND (? = '' OR session_id = ?) AND (? = '' OR service_name = ?) ORDER BY start_ns DESC LIMIT ? OFFSET ?) SELECT rs.*, COALESCE(ti.has_n1, FALSE) AS has_n1, COALESCE(ti.issue_kinds_raw, '') AS issue_kinds_raw, COALESCE(sc.span_count, 1) AS span_count FROM root_spans rs LEFT JOIN (SELECT trace_id, BOOL_OR(kind = 'n_plus_one') AS has_n1, string_agg(DISTINCT kind, ',') AS issue_kinds_raw FROM trace_issues WHERE trace_id IN (SELECT trace_id FROM root_spans) GROUP BY trace_id) ti ON rs.trace_id = ti.trace_id LEFT JOIN (SELECT trace_id, COUNT(*) AS span_count FROM spans WHERE trace_id IN (SELECT trace_id FROM root_spans) GROUP BY trace_id) sc ON rs.trace_id = sc.trace_id ORDER BY rs.start_ns DESC ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountGroups
//
// SELECT COUNT(*) AS count FROM (SELECT 1 FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) GROUP BY service_name, name, kind) groups
func (s spanDo) CountGroups(sessionID string) (result []model.CountValue, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT COUNT(*) AS count FROM (SELECT 1 FROM spans WHERE (? = '' OR session_id = ?) GROUP BY service_name, name, kind) groups ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountTraces
//
// SELECT COUNT(*) AS count FROM @@table WHERE (parent_span_id = ” OR parent_span_id IS NULL) AND (@sessionID = ” OR session_id = @sessionID) AND (@service = ” OR service_name = @service)
func (s spanDo) CountTraces(sessionID string, service string) (result []model.CountValue, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, service)
	params = append(params, service)
	generateSQL.WriteString("SELECT COUNT(*) AS count FROM spans WHERE (parent_span_id = '' OR parent_span_id IS NULL) AND (? = '' OR session_id = ?) AND (? = '' OR service_name = ?) ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListSourceStats
//
// SELECT service_name, COUNT(*) AS span_count, COUNT(*) FILTER (WHERE status_code = 2) AS error_count, SUM(LENGTH(attributes) + LENGTH(resource)) AS bytes_total, MIN(received_at) AS first_seen, MAX(received_at) AS last_seen FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) GROUP BY service_name ORDER BY span_count DESC
func (s spanDo) ListSourceStats(sessionID string) (result []model.SourceStatsRow, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT service_name, COUNT(*) AS span_count, COUNT(*) FILTER (WHERE status_code = 2) AS error_count, SUM(LENGTH(attributes) + LENGTH(resource)) AS bytes_total, MIN(received_at) AS first_seen, MAX(received_at) AS last_seen FROM spans WHERE (? = '' OR session_id = ?) GROUP BY service_name ORDER BY span_count DESC ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ServiceP95
//
// SELECT CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM @@table WHERE service_name = @serviceName
func (s spanDo) ServiceP95(serviceName string) (result []model.P95Value, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, serviceName)
	generateSQL.WriteString("SELECT CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM spans WHERE service_name = ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListServiceMapNodes
//
// SELECT service_name AS id, COUNT(*) AS span_count, COUNT(*) FILTER (WHERE status_code = 2) AS error_count, CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID) GROUP BY service_name ORDER BY service_name
func (s spanDo) ListServiceMapNodes(sessionID string) (result []model.ServiceMapNode, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT service_name AS id, COUNT(*) AS span_count, COUNT(*) FILTER (WHERE status_code = 2) AS error_count, CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM spans WHERE (? = '' OR session_id = ?) GROUP BY service_name ORDER BY service_name ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListServiceMapEdges
//
// SELECT p.service_name AS "from", c.service_name AS "to", COUNT(*) AS call_count, CAST(AVG(c.duration_ns) AS BIGINT) AS avg_duration_ns, COUNT(*) FILTER (WHERE c.status_code = 2) AS error_count FROM @@table c INNER JOIN spans p ON c.parent_span_id = p.span_id WHERE c.service_name != p.service_name AND (@sessionID = ” OR c.session_id = @sessionID) GROUP BY p.service_name, c.service_name
func (s spanDo) ListServiceMapEdges(sessionID string) (result []model.ServiceMapEdge, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT p.service_name AS \"from\", c.service_name AS \"to\", COUNT(*) AS call_count, CAST(AVG(c.duration_ns) AS BIGINT) AS avg_duration_ns, COUNT(*) FILTER (WHERE c.status_code = 2) AS error_count FROM spans c INNER JOIN spans p ON c.parent_span_id = p.span_id WHERE c.service_name != p.service_name AND (? = '' OR c.session_id = ?) GROUP BY p.service_name, c.service_name ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTopOperations
//
// SELECT name, COUNT(*) AS count, CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM @@table WHERE service_name = @service AND (@sessionID = ” OR session_id = @sessionID) GROUP BY name ORDER BY count DESC LIMIT @limit
func (s spanDo) ListTopOperations(service string, sessionID string, limit int) (result []model.ServiceMapOpStat, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, service)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, limit)
	generateSQL.WriteString("SELECT name, COUNT(*) AS count, CAST(COALESCE(QUANTILE_CONT(duration_ns, 0.95), 0) AS BIGINT) AS p95_ns FROM spans WHERE service_name = ? AND (? = '' OR session_id = ?) GROUP BY name ORDER BY count DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetStats
//
// SELECT COUNT(*) AS span_count, COUNT(*) FILTER (WHERE parent_span_id = ” OR parent_span_id IS NULL) AS trace_count, (SELECT COUNT(*) FROM logs WHERE (@sessionID = ” OR session_id = @sessionID)) AS log_count, (SELECT COUNT(*) FROM sessions) AS session_count, COALESCE((SELECT MIN(created_at) FROM sessions), 0) AS oldest_session_at FROM @@table WHERE (@sessionID = ” OR session_id = @sessionID)
func (s spanDo) GetStats(sessionID string) (result []model.StatsRow, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, sessionID)
	generateSQL.WriteString("SELECT COUNT(*) AS span_count, COUNT(*) FILTER (WHERE parent_span_id = '' OR parent_span_id IS NULL) AS trace_count, (SELECT COUNT(*) FROM logs WHERE (? = '' OR session_id = ?)) AS log_count, (SELECT COUNT(*) FROM sessions) AS session_count, COALESCE((SELECT MIN(created_at) FROM sessions), 0) AS oldest_session_at FROM spans WHERE (? = '' OR session_id = ?) ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// StorageTableSizes
//
// SELECT 'spans' AS name, COUNT(*) AS row_count, CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(resource::VARCHAR) + LENGTH(name) + 300), 0) AS BIGINT) AS payload_bytes FROM @@table UNION ALL SELECT 'logs', COUNT(*), CAST(COALESCE(SUM(LENGTH(body) + LENGTH(attributes::VARCHAR) + 100), 0) AS BIGINT) FROM logs UNION ALL SELECT 'metrics', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(name) + 80), 0) AS BIGINT) FROM metrics UNION ALL SELECT 'span_events', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(name) + 80), 0) AS BIGINT) FROM span_events UNION ALL SELECT 'span_links', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + 120), 0) AS BIGINT) FROM span_links UNION ALL SELECT 'sessions', COUNT(*), CAST(COUNT(*) * 200 AS BIGINT) FROM sessions UNION ALL SELECT 'trace_issues', COUNT(*), CAST(COALESCE(SUM(LENGTH(fingerprint) + 150), 0) AS BIGINT) FROM trace_issues UNION ALL SELECT 'lint_warnings', COUNT(*), CAST(COALESCE(SUM(LENGTH(message) + 100), 0) AS BIGINT) FROM lint_warnings
func (s spanDo) StorageTableSizes() (result []model.TableSizeRow, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT 'spans' AS name, COUNT(*) AS row_count, CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(resource::VARCHAR) + LENGTH(name) + 300), 0) AS BIGINT) AS payload_bytes FROM spans UNION ALL SELECT 'logs', COUNT(*), CAST(COALESCE(SUM(LENGTH(body) + LENGTH(attributes::VARCHAR) + 100), 0) AS BIGINT) FROM logs UNION ALL SELECT 'metrics', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(name) + 80), 0) AS BIGINT) FROM metrics UNION ALL SELECT 'span_events', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + LENGTH(name) + 80), 0) AS BIGINT) FROM span_events UNION ALL SELECT 'span_links', COUNT(*), CAST(COALESCE(SUM(LENGTH(attributes::VARCHAR) + 120), 0) AS BIGINT) FROM span_links UNION ALL SELECT 'sessions', COUNT(*), CAST(COUNT(*) * 200 AS BIGINT) FROM sessions UNION ALL SELECT 'trace_issues', COUNT(*), CAST(COALESCE(SUM(LENGTH(fingerprint) + 150), 0) AS BIGINT) FROM trace_issues UNION ALL SELECT 'lint_warnings', COUNT(*), CAST(COALESCE(SUM(LENGTH(message) + 100), 0) AS BIGINT) FROM lint_warnings ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TopSessionSizes
//
// SELECT s.session_id AS id, COALESCE(se.label, ”) AS label, COUNT(*) AS span_count, SUM(LENGTH(s.attributes::VARCHAR) + LENGTH(s.resource::VARCHAR)) AS approx_bytes FROM @@table s LEFT JOIN sessions se ON se.id = s.session_id GROUP BY s.session_id, se.label ORDER BY approx_bytes DESC LIMIT 10
func (s spanDo) TopSessionSizes() (result []model.SessionSize, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT s.session_id AS id, COALESCE(se.label, '') AS label, COUNT(*) AS span_count, SUM(LENGTH(s.attributes::VARCHAR) + LENGTH(s.resource::VARCHAR)) AS approx_bytes FROM spans s LEFT JOIN sessions se ON se.id = s.session_id GROUP BY s.session_id, se.label ORDER BY approx_bytes DESC LIMIT 10 ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s spanDo) Debug() ISpanDo {
	return s.withDO(s.DO.Debug())
}

func (s spanDo) WithContext(ctx context.Context) ISpanDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spanDo) ReadDB() ISpanDo {
	return s.Clauses(dbresolver.Read)
}

func (s spanDo) WriteDB() ISpanDo {
	return s.Clauses(dbresolver.Write)
}

func (s spanDo) Session(config *gorm.Session) ISpanDo {
	return s.withDO(s.DO.Session(config))
}

func (s spanDo) Clauses(conds ...clause.Expression) ISpanDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spanDo) Returning(value interface{}, columns ...string) ISpanDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spanDo) Not(conds ...gen.Condition) ISpanDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spanDo) Or(conds ...gen.Condition) ISpanDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spanDo) Select(conds ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spanDo) Where(conds ...gen.Condition) ISpanDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spanDo) Order(conds ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spanDo) Distinct(cols ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spanDo) Omit(cols ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spanDo) Join(table schema.Tabler, on ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spanDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpanDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spanDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpanDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spanDo) Group(cols ...field.Expr) ISpanDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spanDo) Having(conds ...gen.Condition) ISpanDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spanDo) Limit(limit int) ISpanDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spanDo) Offset(offset int) ISpanDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spanDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spanDo) Unscoped() ISpanDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spanDo) Create(values ...*model.Span) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spanDo) CreateInBatches(values []*model.Span, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spanDo) Save(values ...*model.Span) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spanDo) First() (*model.Span, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Span), nil
	}
}

func (s spanDo) Take() (*model.Span, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Span), nil
	}
}

func (s spanDo) Last() (*model.Span, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Span), nil
	}
}

func (s spanDo) Find() ([]*model.Span, error) {
	result, err := s.DO.Find()
	return result.([]*model.Span), err
}

func (s spanDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Span, err error) {
	buf := make([]*model.Span, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spanDo) FindInBatches(result *[]*model.Span, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spanDo) Attrs(attrs ...field.AssignExpr) ISpanDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spanDo) Assign(attrs ...field.AssignExpr) ISpanDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spanDo) Joins(fields ...field.RelationField) ISpanDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spanDo) Preload(fields ...field.RelationField) ISpanDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spanDo) FirstOrInit() (*model.Span, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Span), nil
	}
}

func (s spanDo) FirstOrCreate() (*model.Span, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Span), nil
	}
}

func (s spanDo) FindByPage(offset int, limit int) (result []*model.Span, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spanDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spanDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spanDo) Delete(models ...*model.Span) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spanDo) withDO(do gen.Dao) *spanDo {
	s.DO = *do.(*gen.DO)
	return s
}
