// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newSpanLink(db *gorm.DB, opts ...gen.DOOption) spanLink {
	_spanLink := spanLink{}

	_spanLink.spanLinkDo.UseDB(db, opts...)
	_spanLink.spanLinkDo.UseModel(&model.SpanLink{})

	tableName := _spanLink.spanLinkDo.TableName()
	_spanLink.ALL = field.NewAsterisk(tableName)
	_spanLink.SpanID = field.NewString(tableName, "span_id")
	_spanLink.TraceID = field.NewString(tableName, "trace_id")
	_spanLink.SessionID = field.NewString(tableName, "session_id")
	_spanLink.LinkedTraceID = field.NewString(tableName, "linked_trace_id")
	_spanLink.LinkedSpanID = field.NewString(tableName, "linked_span_id")
	_spanLink.TraceState = field.NewString(tableName, "trace_state")
	_spanLink.Attributes = field.NewString(tableName, "attributes")

	_spanLink.fillFieldMap()

	return _spanLink
}

type spanLink struct {
	spanLinkDo

	ALL           field.Asterisk
	SpanID        field.String
	TraceID       field.String
	SessionID     field.String
	LinkedTraceID field.String
	LinkedSpanID  field.String
	TraceState    field.String
	Attributes    field.String

	fieldMap map[string]field.Expr
}

func (s spanLink) Table(newTableName string) *spanLink {
	s.spanLinkDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s spanLink) As(alias string) *spanLink {
	s.spanLinkDo.DO = *(s.spanLinkDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *spanLink) updateTableName(table string) *spanLink {
	s.ALL = field.NewAsterisk(table)
	s.SpanID = field.NewString(table, "span_id")
	s.TraceID = field.NewString(table, "trace_id")
	s.SessionID = field.NewString(table, "session_id")
	s.LinkedTraceID = field.NewString(table, "linked_trace_id")
	s.LinkedSpanID = field.NewString(table, "linked_span_id")
	s.TraceState = field.NewString(table, "trace_state")
	s.Attributes = field.NewString(table, "attributes")

	s.fillFieldMap()

	return s
}

func (s *spanLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *spanLink) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["span_id"] = s.SpanID
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["session_id"] = s.SessionID
	s.fieldMap["linked_trace_id"] = s.LinkedTraceID
	s.fieldMap["linked_span_id"] = s.LinkedSpanID
	s.fieldMap["trace_state"] = s.TraceState
	s.fieldMap["attributes"] = s.Attributes
}

func (s spanLink) clone(db *gorm.DB) spanLink {
	s.spanLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s spanLink) replaceDB(db *gorm.DB) spanLink {
	s.spanLinkDo.ReplaceDB(db)
	return s
}

type spanLinkDo struct{ gen.DO }

type ISpanLinkDo interface {
	gen.SubQuery
	Debug() ISpanLinkDo
	WithContext(ctx context.Context) ISpanLinkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISpanLinkDo
	WriteDB() ISpanLinkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISpanLinkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISpanLinkDo
	Not(conds ...gen.Condition) ISpanLinkDo
	Or(conds ...gen.Condition) ISpanLinkDo
	Select(conds ...field.Expr) ISpanLinkDo
	Where(conds ...gen.Condition) ISpanLinkDo
	Order(conds ...field.Expr) ISpanLinkDo
	Distinct(cols ...field.Expr) ISpanLinkDo
	Omit(cols ...field.Expr) ISpanLinkDo
	Join(table schema.Tabler, on ...field.Expr) ISpanLinkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISpanLinkDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISpanLinkDo
	Group(cols ...field.Expr) ISpanLinkDo
	Having(conds ...gen.Condition) ISpanLinkDo
	Limit(limit int) ISpanLinkDo
	Offset(offset int) ISpanLinkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanLinkDo
	Unscoped() ISpanLinkDo
	Create(values ...*model.SpanLink) error
	CreateInBatches(values []*model.SpanLink, batchSize int) error
	Save(values ...*model.SpanLink) error
	First() (*model.SpanLink, error)
	Take() (*model.SpanLink, error)
	Last() (*model.SpanLink, error)
	Find() ([]*model.SpanLink, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpanLink, err error)
	FindInBatches(result *[]*model.SpanLink, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SpanLink) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISpanLinkDo
	Assign(attrs ...field.AssignExpr) ISpanLinkDo
	Joins(fields ...field.RelationField) ISpanLinkDo
	Preload(fields ...field.RelationField) ISpanLinkDo
	FirstOrInit() (*model.SpanLink, error)
	FirstOrCreate() (*model.SpanLink, error)
	FindByPage(offset int, limit int) (result []*model.SpanLink, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISpanLinkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ListBySpan(spanID string) (result []model.SpanLink, err error)
	ListIncomingByTrace(traceID string) (result []model.SpanLink, err error)
	ListByTrace(traceID string) (result []model.SpanLink, err error)
}

// ListBySpan
//
// SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM @@table WHERE span_id = @spanID
func (s spanLinkDo) ListBySpan(spanID string) (result []model.SpanLink, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, spanID)
	generateSQL.WriteString("SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM span_links WHERE span_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListIncomingByTrace
//
// SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM @@table WHERE linked_trace_id = @traceID
func (s spanLinkDo) ListIncomingByTrace(traceID string) (result []model.SpanLink, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, traceID)
	generateSQL.WriteString("SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM span_links WHERE linked_trace_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByTrace
//
// SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM @@table WHERE trace_id = @traceID
func (s spanLinkDo) ListByTrace(traceID string) (result []model.SpanLink, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, traceID)
	generateSQL.WriteString("SELECT span_id, trace_id, session_id, linked_trace_id, linked_span_id, trace_state, attributes::VARCHAR AS attributes FROM span_links WHERE trace_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s spanLinkDo) Debug() ISpanLinkDo {
	return s.withDO(s.DO.Debug())
}

func (s spanLinkDo) WithContext(ctx context.Context) ISpanLinkDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s spanLinkDo) ReadDB() ISpanLinkDo {
	return s.Clauses(dbresolver.Read)
}

func (s spanLinkDo) WriteDB() ISpanLinkDo {
	return s.Clauses(dbresolver.Write)
}

func (s spanLinkDo) Session(config *gorm.Session) ISpanLinkDo {
	return s.withDO(s.DO.Session(config))
}

func (s spanLinkDo) Clauses(conds ...clause.Expression) ISpanLinkDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s spanLinkDo) Returning(value interface{}, columns ...string) ISpanLinkDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s spanLinkDo) Not(conds ...gen.Condition) ISpanLinkDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s spanLinkDo) Or(conds ...gen.Condition) ISpanLinkDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s spanLinkDo) Select(conds ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s spanLinkDo) Where(conds ...gen.Condition) ISpanLinkDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s spanLinkDo) Order(conds ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s spanLinkDo) Distinct(cols ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s spanLinkDo) Omit(cols ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s spanLinkDo) Join(table schema.Tabler, on ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s spanLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s spanLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s spanLinkDo) Group(cols ...field.Expr) ISpanLinkDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s spanLinkDo) Having(conds ...gen.Condition) ISpanLinkDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s spanLinkDo) Limit(limit int) ISpanLinkDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s spanLinkDo) Offset(offset int) ISpanLinkDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s spanLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISpanLinkDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s spanLinkDo) Unscoped() ISpanLinkDo {
	return s.withDO(s.DO.Unscoped())
}

func (s spanLinkDo) Create(values ...*model.SpanLink) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s spanLinkDo) CreateInBatches(values []*model.SpanLink, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s spanLinkDo) Save(values ...*model.SpanLink) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s spanLinkDo) First() (*model.SpanLink, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanLink), nil
	}
}

func (s spanLinkDo) Take() (*model.SpanLink, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanLink), nil
	}
}

func (s spanLinkDo) Last() (*model.SpanLink, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanLink), nil
	}
}

func (s spanLinkDo) Find() ([]*model.SpanLink, error) {
	result, err := s.DO.Find()
	return result.([]*model.SpanLink), err
}

func (s spanLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SpanLink, err error) {
	buf := make([]*model.SpanLink, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s spanLinkDo) FindInBatches(result *[]*model.SpanLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s spanLinkDo) Attrs(attrs ...field.AssignExpr) ISpanLinkDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s spanLinkDo) Assign(attrs ...field.AssignExpr) ISpanLinkDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s spanLinkDo) Joins(fields ...field.RelationField) ISpanLinkDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s spanLinkDo) Preload(fields ...field.RelationField) ISpanLinkDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s spanLinkDo) FirstOrInit() (*model.SpanLink, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanLink), nil
	}
}

func (s spanLinkDo) FirstOrCreate() (*model.SpanLink, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SpanLink), nil
	}
}

func (s spanLinkDo) FindByPage(offset int, limit int) (result []*model.SpanLink, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s spanLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s spanLinkDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s spanLinkDo) Delete(models ...*model.SpanLink) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *spanLinkDo) withDO(do gen.Dao) *spanLinkDo {
	s.DO = *do.(*gen.DO)
	return s
}
