// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package querygen

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zfogg/spaniel/internal/model"
)

func newTraceIssue(db *gorm.DB, opts ...gen.DOOption) traceIssue {
	_traceIssue := traceIssue{}

	_traceIssue.traceIssueDo.UseDB(db, opts...)
	_traceIssue.traceIssueDo.UseModel(&model.TraceIssue{})

	tableName := _traceIssue.traceIssueDo.TableName()
	_traceIssue.ALL = field.NewAsterisk(tableName)
	_traceIssue.ID = field.NewString(tableName, "id")
	_traceIssue.TraceID = field.NewString(tableName, "trace_id")
	_traceIssue.SessionID = field.NewString(tableName, "session_id")
	_traceIssue.Kind = field.NewString(tableName, "kind")
	_traceIssue.Fingerprint = field.NewString(tableName, "fingerprint")
	_traceIssue.Count_ = field.NewInt(tableName, "count")
	_traceIssue.WastedNs = field.NewInt64(tableName, "wasted_ns")
	_traceIssue.ParentSpanID = field.NewString(tableName, "parent_span_id")
	_traceIssue.ExampleSpanID = field.NewString(tableName, "example_span_id")
	_traceIssue.CreatedAt = field.NewInt64(tableName, "created_at")

	_traceIssue.fillFieldMap()

	return _traceIssue
}

type traceIssue struct {
	traceIssueDo

	ALL           field.Asterisk
	ID            field.String
	TraceID       field.String
	SessionID     field.String
	Kind          field.String
	Fingerprint   field.String
	Count_        field.Int
	WastedNs      field.Int64
	ParentSpanID  field.String
	ExampleSpanID field.String
	CreatedAt     field.Int64

	fieldMap map[string]field.Expr
}

func (t traceIssue) Table(newTableName string) *traceIssue {
	t.traceIssueDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t traceIssue) As(alias string) *traceIssue {
	t.traceIssueDo.DO = *(t.traceIssueDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *traceIssue) updateTableName(table string) *traceIssue {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TraceID = field.NewString(table, "trace_id")
	t.SessionID = field.NewString(table, "session_id")
	t.Kind = field.NewString(table, "kind")
	t.Fingerprint = field.NewString(table, "fingerprint")
	t.Count_ = field.NewInt(table, "count")
	t.WastedNs = field.NewInt64(table, "wasted_ns")
	t.ParentSpanID = field.NewString(table, "parent_span_id")
	t.ExampleSpanID = field.NewString(table, "example_span_id")
	t.CreatedAt = field.NewInt64(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *traceIssue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *traceIssue) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["trace_id"] = t.TraceID
	t.fieldMap["session_id"] = t.SessionID
	t.fieldMap["kind"] = t.Kind
	t.fieldMap["fingerprint"] = t.Fingerprint
	t.fieldMap["count"] = t.Count_
	t.fieldMap["wasted_ns"] = t.WastedNs
	t.fieldMap["parent_span_id"] = t.ParentSpanID
	t.fieldMap["example_span_id"] = t.ExampleSpanID
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t traceIssue) clone(db *gorm.DB) traceIssue {
	t.traceIssueDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t traceIssue) replaceDB(db *gorm.DB) traceIssue {
	t.traceIssueDo.ReplaceDB(db)
	return t
}

type traceIssueDo struct{ gen.DO }

type ITraceIssueDo interface {
	gen.SubQuery
	Debug() ITraceIssueDo
	WithContext(ctx context.Context) ITraceIssueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITraceIssueDo
	WriteDB() ITraceIssueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITraceIssueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITraceIssueDo
	Not(conds ...gen.Condition) ITraceIssueDo
	Or(conds ...gen.Condition) ITraceIssueDo
	Select(conds ...field.Expr) ITraceIssueDo
	Where(conds ...gen.Condition) ITraceIssueDo
	Order(conds ...field.Expr) ITraceIssueDo
	Distinct(cols ...field.Expr) ITraceIssueDo
	Omit(cols ...field.Expr) ITraceIssueDo
	Join(table schema.Tabler, on ...field.Expr) ITraceIssueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITraceIssueDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITraceIssueDo
	Group(cols ...field.Expr) ITraceIssueDo
	Having(conds ...gen.Condition) ITraceIssueDo
	Limit(limit int) ITraceIssueDo
	Offset(offset int) ITraceIssueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITraceIssueDo
	Unscoped() ITraceIssueDo
	Create(values ...*model.TraceIssue) error
	CreateInBatches(values []*model.TraceIssue, batchSize int) error
	Save(values ...*model.TraceIssue) error
	First() (*model.TraceIssue, error)
	Take() (*model.TraceIssue, error)
	Last() (*model.TraceIssue, error)
	Find() ([]*model.TraceIssue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TraceIssue, err error)
	FindInBatches(result *[]*model.TraceIssue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TraceIssue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITraceIssueDo
	Assign(attrs ...field.AssignExpr) ITraceIssueDo
	Joins(fields ...field.RelationField) ITraceIssueDo
	Preload(fields ...field.RelationField) ITraceIssueDo
	FirstOrInit() (*model.TraceIssue, error)
	FirstOrCreate() (*model.TraceIssue, error)
	FindByPage(offset int, limit int) (result []*model.TraceIssue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITraceIssueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	SearchNPlusOne(sessionID string, limit int) (result []model.NPlusOneSearchResult, err error)
}

// SearchNPlusOne
//
// SELECT ti.trace_id, COALESCE(s.name, '(trace)') AS title, ti.count, ti.session_id FROM @@table ti LEFT JOIN spans s ON s.span_id = ti.example_span_id WHERE ti.kind = 'n_plus_one' AND (@sessionID = ” OR ti.session_id = @sessionID) ORDER BY ti.wasted_ns DESC LIMIT @limit
func (t traceIssueDo) SearchNPlusOne(sessionID string, limit int) (result []model.NPlusOneSearchResult, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, sessionID)
	params = append(params, sessionID)
	params = append(params, limit)
	generateSQL.WriteString("SELECT ti.trace_id, COALESCE(s.name, '(trace)') AS title, ti.count, ti.session_id FROM trace_issues ti LEFT JOIN spans s ON s.span_id = ti.example_span_id WHERE ti.kind = 'n_plus_one' AND (? = '' OR ti.session_id = ?) ORDER BY ti.wasted_ns DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = t.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (t traceIssueDo) Debug() ITraceIssueDo {
	return t.withDO(t.DO.Debug())
}

func (t traceIssueDo) WithContext(ctx context.Context) ITraceIssueDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t traceIssueDo) ReadDB() ITraceIssueDo {
	return t.Clauses(dbresolver.Read)
}

func (t traceIssueDo) WriteDB() ITraceIssueDo {
	return t.Clauses(dbresolver.Write)
}

func (t traceIssueDo) Session(config *gorm.Session) ITraceIssueDo {
	return t.withDO(t.DO.Session(config))
}

func (t traceIssueDo) Clauses(conds ...clause.Expression) ITraceIssueDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t traceIssueDo) Returning(value interface{}, columns ...string) ITraceIssueDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t traceIssueDo) Not(conds ...gen.Condition) ITraceIssueDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t traceIssueDo) Or(conds ...gen.Condition) ITraceIssueDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t traceIssueDo) Select(conds ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t traceIssueDo) Where(conds ...gen.Condition) ITraceIssueDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t traceIssueDo) Order(conds ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t traceIssueDo) Distinct(cols ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t traceIssueDo) Omit(cols ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t traceIssueDo) Join(table schema.Tabler, on ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t traceIssueDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t traceIssueDo) RightJoin(table schema.Tabler, on ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t traceIssueDo) Group(cols ...field.Expr) ITraceIssueDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t traceIssueDo) Having(conds ...gen.Condition) ITraceIssueDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t traceIssueDo) Limit(limit int) ITraceIssueDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t traceIssueDo) Offset(offset int) ITraceIssueDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t traceIssueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITraceIssueDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t traceIssueDo) Unscoped() ITraceIssueDo {
	return t.withDO(t.DO.Unscoped())
}

func (t traceIssueDo) Create(values ...*model.TraceIssue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t traceIssueDo) CreateInBatches(values []*model.TraceIssue, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t traceIssueDo) Save(values ...*model.TraceIssue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t traceIssueDo) First() (*model.TraceIssue, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TraceIssue), nil
	}
}

func (t traceIssueDo) Take() (*model.TraceIssue, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TraceIssue), nil
	}
}

func (t traceIssueDo) Last() (*model.TraceIssue, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TraceIssue), nil
	}
}

func (t traceIssueDo) Find() ([]*model.TraceIssue, error) {
	result, err := t.DO.Find()
	return result.([]*model.TraceIssue), err
}

func (t traceIssueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TraceIssue, err error) {
	buf := make([]*model.TraceIssue, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t traceIssueDo) FindInBatches(result *[]*model.TraceIssue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t traceIssueDo) Attrs(attrs ...field.AssignExpr) ITraceIssueDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t traceIssueDo) Assign(attrs ...field.AssignExpr) ITraceIssueDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t traceIssueDo) Joins(fields ...field.RelationField) ITraceIssueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t traceIssueDo) Preload(fields ...field.RelationField) ITraceIssueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t traceIssueDo) FirstOrInit() (*model.TraceIssue, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TraceIssue), nil
	}
}

func (t traceIssueDo) FirstOrCreate() (*model.TraceIssue, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TraceIssue), nil
	}
}

func (t traceIssueDo) FindByPage(offset int, limit int) (result []*model.TraceIssue, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t traceIssueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t traceIssueDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t traceIssueDo) Delete(models ...*model.TraceIssue) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *traceIssueDo) withDO(do gen.Dao) *traceIssueDo {
	t.DO = *do.(*gen.DO)
	return t
}
