// Code generated by cmd/genopenapi; DO NOT EDIT.
package api

import (
	"net/http"

	"github.com/zfogg/spaniel/internal/api/apigen"
)

var _ apigen.ServerInterface = (*Router)(nil)

func (r *Router) DeleteAlert(w http.ResponseWriter, req *http.Request, id string) {
	r.deleteAlert(w, req)
}

func (r *Router) DeleteAlertSilence(w http.ResponseWriter, req *http.Request, id string, silenceID string) {
	r.deleteAlertSilence(w, req)
}

func (r *Router) DeleteCoverageSpec(w http.ResponseWriter, req *http.Request, id string) {
	r.deleteCoverageSpec(w, req)
}

func (r *Router) DeleteDashboard(w http.ResponseWriter, req *http.Request, id string) {
	r.deleteDashboard(w, req)
}

func (r *Router) DeleteDashboardPanel(w http.ResponseWriter, req *http.Request, id string, panelId string) {
	r.deletePanel(w, req)
}

func (r *Router) DeleteDashboardVariable(w http.ResponseWriter, req *http.Request, id string, name string) {
	r.deleteVariable(w, req)
}

func (r *Router) DeleteSession(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.deleteSession(w, req)
}

func (r *Router) DropAllData(w http.ResponseWriter, req *http.Request) { r.dropAllData(w, req) }

func (r *Router) ListAlerts(w http.ResponseWriter, req *http.Request, _ apigen.ListAlertsParams) {
	r.listAlerts(w, req)
}

func (r *Router) ListAlertHistory(w http.ResponseWriter, req *http.Request, _ apigen.ListAlertHistoryParams) {
	r.listAlertHistory(w, req)
}

func (r *Router) GetAlert(w http.ResponseWriter, req *http.Request, id string) { r.getAlert(w, req) }

func (r *Router) ExportAlertConfig(w http.ResponseWriter, req *http.Request, id string) {
	r.exportAlertConfig(w, req)
}

func (r *Router) ListAlertEvents(w http.ResponseWriter, req *http.Request, id string, _ apigen.ListAlertEventsParams) {
	r.listAlertEvents(w, req)
}

func (r *Router) ListAlertSilences(w http.ResponseWriter, req *http.Request, id string) {
	r.listAlertSilences(w, req)
}

func (r *Router) GetCoverage(w http.ResponseWriter, req *http.Request, _ apigen.GetCoverageParams) {
	r.getCoverage(w, req)
}

func (r *Router) ListCoverageSpecs(w http.ResponseWriter, req *http.Request) {
	r.listCoverageSpecs(w, req)
}

func (r *Router) GetCoverageSpec(w http.ResponseWriter, req *http.Request, id string) {
	r.getCoverageSpec(w, req)
}

func (r *Router) ListDashboards(w http.ResponseWriter, req *http.Request) { r.listDashboards(w, req) }

func (r *Router) GetDashboard(w http.ResponseWriter, req *http.Request, id string) {
	r.getDashboard(w, req)
}

func (r *Router) ExportDashboardConfig(w http.ResponseWriter, req *http.Request, id string) {
	r.exportDashboardConfig(w, req)
}

func (r *Router) GetDatabaseSchema(w http.ResponseWriter, req *http.Request) {
	r.databaseSchema(w, req)
}

func (r *Router) GetDiff(w http.ResponseWriter, req *http.Request, _ apigen.GetDiffParams) {
	r.getDiff(w, req)
}

func (r *Router) ListForwarders(w http.ResponseWriter, req *http.Request) { r.listForwarders(w, req) }

func (r *Router) GetHealth(w http.ResponseWriter, req *http.Request) { r.health(w, req) }

func (r *Router) ListIssues(w http.ResponseWriter, req *http.Request, _ apigen.ListIssuesParams) {
	r.getIssues(w, req)
}

func (r *Router) ListLint(w http.ResponseWriter, req *http.Request, _ apigen.ListLintParams) {
	r.listLint(w, req)
}

func (r *Router) ListLogs(w http.ResponseWriter, req *http.Request, _ apigen.ListLogsParams) {
	r.listLogs(w, req)
}

func (r *Router) ListMetrics(w http.ResponseWriter, req *http.Request, _ apigen.ListMetricsParams) {
	r.listMetrics(w, req)
}

func (r *Router) GetMetricCardinality(w http.ResponseWriter, req *http.Request, _ apigen.GetMetricCardinalityParams) {
	r.getMetricCardinality(w, req)
}

func (r *Router) GetMetricSeries(w http.ResponseWriter, req *http.Request, _ apigen.GetMetricSeriesParams) {
	r.getMetricSeries(w, req)
}

func (r *Router) ListNotifications(w http.ResponseWriter, req *http.Request, _ apigen.ListNotificationsParams) {
	r.listNotifications(w, req)
}

func (r *Router) GetOpenAPISpec(w http.ResponseWriter, req *http.Request) { r.openAPI(w, req) }

func (r *Router) GetOpenAPIYAML(w http.ResponseWriter, req *http.Request) { r.openAPIYAML(w, req) }

func (r *Router) ListQueryCatalog(w http.ResponseWriter, req *http.Request, _ apigen.ListQueryCatalogParams) {
	r.queryCatalog(w, req)
}

func (r *Router) SearchTelemetry(w http.ResponseWriter, req *http.Request, _ apigen.SearchTelemetryParams) {
	r.search(w, req)
}

func (r *Router) GetServiceMap(w http.ResponseWriter, req *http.Request, _ apigen.GetServiceMapParams) {
	r.getServiceMap(w, req)
}

func (r *Router) ListServices(w http.ResponseWriter, req *http.Request) { r.listServices(w, req) }

func (r *Router) ListSessions(w http.ResponseWriter, req *http.Request) { r.listSessions(w, req) }

func (r *Router) GetActiveSession(w http.ResponseWriter, req *http.Request) {
	r.getActiveSession(w, req)
}

func (r *Router) GetSession(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.getSession(w, req)
}

func (r *Router) ExportSessionBaseline(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.exportBaseline(w, req)
}

func (r *Router) GetSettings(w http.ResponseWriter, req *http.Request) { r.getSettings(w, req) }

func (r *Router) ListSources(w http.ResponseWriter, req *http.Request, _ apigen.ListSourcesParams) {
	r.listSources(w, req)
}

func (r *Router) ListSpans(w http.ResponseWriter, req *http.Request, _ apigen.ListSpansParams) {
	r.listSpans(w, req)
}

func (r *Router) GetSpan(w http.ResponseWriter, req *http.Request, spanId string) { r.getSpan(w, req) }

func (r *Router) GetStats(w http.ResponseWriter, req *http.Request, _ apigen.GetStatsParams) {
	r.getStats(w, req)
}

func (r *Router) GetStorageBreakdown(w http.ResponseWriter, req *http.Request) {
	r.getStorageBreakdown(w, req)
}

func (r *Router) ListTraces(w http.ResponseWriter, req *http.Request, _ apigen.ListTracesParams) {
	r.listTraces(w, req)
}

func (r *Router) GetTrace(w http.ResponseWriter, req *http.Request, traceId string) {
	r.getTrace(w, req)
}

func (r *Router) ExportTrace(w http.ResponseWriter, req *http.Request, traceId string) {
	r.exportTrace(w, req)
}

func (r *Router) ListIncomingLinks(w http.ResponseWriter, req *http.Request, traceId string) {
	r.listIncomingLinks(w, req)
}

func (r *Router) PatchAlert(w http.ResponseWriter, req *http.Request, id string) {
	r.patchAlert(w, req)
}

func (r *Router) PatchAlertSilence(w http.ResponseWriter, req *http.Request, id string, silenceID string) {
	r.updateAlertSilence(w, req)
}

func (r *Router) PatchDashboard(w http.ResponseWriter, req *http.Request, id string) {
	r.patchDashboard(w, req)
}

func (r *Router) PatchDashboardPanel(w http.ResponseWriter, req *http.Request, id string, panelId string) {
	r.savePanel(w, req, true)
}

func (r *Router) PatchSession(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.patchSession(w, req)
}

func (r *Router) CreateAlert(w http.ResponseWriter, req *http.Request) { r.createAlert(w, req) }

func (r *Router) ImportAlertConfig(w http.ResponseWriter, req *http.Request) {
	r.importAlertConfig(w, req)
}

func (r *Router) PreviewAlertDraft(w http.ResponseWriter, req *http.Request) {
	r.previewAlertDraft(w, req)
}

func (r *Router) ReloadAlertDefinitions(w http.ResponseWriter, req *http.Request) {
	r.reloadAlertDefinitions(w, req)
}

func (r *Router) AcknowledgeAlert(w http.ResponseWriter, req *http.Request, id string) {
	r.acknowledgeAlert(w, req)
}

func (r *Router) DuplicateAlert(w http.ResponseWriter, req *http.Request, id string) {
	r.duplicateAlert(w, req)
}

func (r *Router) AcknowledgeAlertInstance(w http.ResponseWriter, req *http.Request, id string) {
	r.acknowledgeAlertInstance(w, req)
}

func (r *Router) UnacknowledgeAlertInstance(w http.ResponseWriter, req *http.Request, id string) {
	r.unacknowledgeAlertInstance(w, req)
}

func (r *Router) PreviewAlert(w http.ResponseWriter, req *http.Request, id string) {
	r.previewAlert(w, req)
}

func (r *Router) CreateAlertSilence(w http.ResponseWriter, req *http.Request, id string) {
	r.createAlertSilence(w, req)
}

func (r *Router) TestAlertNotification(w http.ResponseWriter, req *http.Request, id string) {
	r.testAlertNotification(w, req)
}

func (r *Router) CreateCoverageSpec(w http.ResponseWriter, req *http.Request) {
	r.createCoverageSpec(w, req)
}

func (r *Router) CreateDashboard(w http.ResponseWriter, req *http.Request) { r.createDashboard(w, req) }

func (r *Router) ImportDashboardConfig(w http.ResponseWriter, req *http.Request) {
	r.importDashboardConfig(w, req)
}

func (r *Router) ReorderDashboards(w http.ResponseWriter, req *http.Request) {
	r.reorderDashboards(w, req)
}

func (r *Router) CreateDashboardPanel(w http.ResponseWriter, req *http.Request, id string) {
	r.savePanel(w, req, false)
}

func (r *Router) MoveDashboardPanel(w http.ResponseWriter, req *http.Request, id string, panelId string) {
	r.movePanel(w, req)
}

func (r *Router) PreviewDashboardQuery(w http.ResponseWriter, req *http.Request, id string) {
	r.previewDashboardQuery(w, req)
}

func (r *Router) CreateDashboardVariable(w http.ResponseWriter, req *http.Request, id string) {
	r.saveVariable(w, req)
}

func (r *Router) AcknowledgeNotification(w http.ResponseWriter, req *http.Request, id string) {
	r.acknowledgeNotification(w, req)
}

func (r *Router) ReadNotification(w http.ResponseWriter, req *http.Request, id string) {
	r.readNotification(w, req)
}

func (r *Router) CreateSession(w http.ResponseWriter, req *http.Request) { r.createSession(w, req) }

func (r *Router) ImportSession(w http.ResponseWriter, req *http.Request, _ apigen.ImportSessionParams) {
	r.importSession(w, req)
}

func (r *Router) ActivateSession(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.activateSession(w, req)
}

func (r *Router) SetSessionBaseline(w http.ResponseWriter, req *http.Request, sessionId string) {
	r.baselineSession(w, req)
}

func (r *Router) CheckUpdates(w http.ResponseWriter, req *http.Request) { r.checkUpdates(w, req) }

func (r *Router) CompactStorage(w http.ResponseWriter, req *http.Request) { r.compact(w, req) }

func (r *Router) PruneStorage(w http.ResponseWriter, req *http.Request) { r.prune(w, req) }

func (r *Router) ReplaceCoverageSpec(w http.ResponseWriter, req *http.Request, id string) {
	r.replaceCoverageSpec(w, req)
}

func (r *Router) PutSettings(w http.ResponseWriter, req *http.Request) { r.putSettings(w, req) }
