ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS repeat_interval_ns BIGINT DEFAULT 0;
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS owner TEXT DEFAULT '';
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS team TEXT DEFAULT '';
