import { writeFileSync } from 'node:fs'

import { z } from 'zod'

import {
  AlertEventSchema,
  AlertInstanceSchema,
  AlertListSchema,
  AlertRuleSchema,
  AlertSilenceSchema,
  CompactResultSchema,
  CoverageReportSchema,
  CoverageRouteSchema,
  DashboardPanelSchema,
  DashboardSchema,
  DashboardVariableSchema,
  DatabaseSchemaCatalogSchema,
  ForwarderStatusSchema,
  ImportResultSchema,
  LintWarningSchema,
  LogSchema,
  MetricCardinalityStreamSchema,
  MetricCatalogEntrySchema,
  MetricSeriesExemplarSchema,
  MetricSeriesPointSchema,
  MetricSeriesSchema,
  PruneResultSchema,
  QueryCatalogEntrySchema,
  QueryPreviewSchema,
  SearchResultSchema,
  ServiceCoverageSchema,
  ServiceMapDataSchema,
  ServiceMapEdgeSchema,
  ServiceMapNodeSchema,
  ServiceMapOpStatSchema,
  SessionSchema,
  SessionSizeSchema,
  SettingsResponseSchema,
  SettingsRuntimeSchema,
  SettingsSchema,
  SourceStatsSchema,
  SpanEventSchema,
  SpanGroupSchema,
  SpanLinkSchema,
  SpanRowSchema,
  SpanSchema,
  StatsSchema,
  StorageBreakdownSchema,
  TableStatSchema,
  TraceIssueSchema,
  TraceOverlaySchema,
  TraceRowSchema,
  UpdateCheckResultSchema,
} from '../src/lib/api'

const schemas = {
  AlertEvent: AlertEventSchema,
  AlertInstance: AlertInstanceSchema,
  AlertList: AlertListSchema,
  AlertRule: AlertRuleSchema,
  AlertSilence: AlertSilenceSchema,
  CompactResult: CompactResultSchema,
  CoverageReport: CoverageReportSchema,
  CoverageRoute: CoverageRouteSchema,
  Dashboard: DashboardSchema,
  DashboardPanel: DashboardPanelSchema,
  DashboardVariable: DashboardVariableSchema,
  DatabaseSchemaCatalog: DatabaseSchemaCatalogSchema,
  ForwarderStatus: ForwarderStatusSchema,
  ImportResult: ImportResultSchema,
  LintWarning: LintWarningSchema,
  Log: LogSchema,
  MetricCardinalityStream: MetricCardinalityStreamSchema,
  MetricCatalogEntry: MetricCatalogEntrySchema,
  MetricSeries: MetricSeriesSchema,
  MetricSeriesExemplar: MetricSeriesExemplarSchema,
  MetricSeriesPoint: MetricSeriesPointSchema,
  PruneResult: PruneResultSchema,
  QueryCatalogEntry: QueryCatalogEntrySchema,
  QueryPreview: QueryPreviewSchema,
  SearchResult: SearchResultSchema,
  ServiceCoverage: ServiceCoverageSchema,
  ServiceMapData: ServiceMapDataSchema,
  ServiceMapEdge: ServiceMapEdgeSchema,
  ServiceMapNode: ServiceMapNodeSchema,
  ServiceMapOpStat: ServiceMapOpStatSchema,
  Session: SessionSchema,
  SessionSize: SessionSizeSchema,
  Settings: SettingsSchema,
  SettingsResponse: SettingsResponseSchema,
  SettingsRuntime: SettingsRuntimeSchema,
  SourceStats: SourceStatsSchema,
  Span: SpanSchema,
  SpanEvent: SpanEventSchema,
  SpanGroup: SpanGroupSchema,
  SpanLink: SpanLinkSchema,
  SpanRow: SpanRowSchema,
  Stats: StatsSchema,
  StorageBreakdown: StorageBreakdownSchema,
  TableStat: TableStatSchema,
  TraceIssue: TraceIssueSchema,
  TraceOverlay: TraceOverlaySchema,
  TraceRow: TraceRowSchema,
  UpdateCheckResult: UpdateCheckResultSchema,
} satisfies Record<string, z.ZodType>

const jsonSchemas = Object.fromEntries(
  Object.entries(schemas).map(([name, schema]) => [
    name,
    z.toJSONSchema(schema, { unrepresentable: 'any' }),
  ]),
)

writeFileSync('../api/frontend-schemas.json', `${JSON.stringify(jsonSchemas, null, 2)}\n`)
