// Command genopenapi keeps the generated HTTP boundary in sync with api/openapi.json.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

type operation struct {
	OperationID string      `json:"operationId"`
	Parameters  []parameter `json:"parameters"`
}

type parameter struct {
	In string `json:"in"`
}

type document struct {
	Paths map[string]map[string]operation `json:"paths"`
}

var routeRE = regexp.MustCompile(`mux\.(Get|Post|Put|Patch|Delete)\("([^"]+)", r\.([A-Za-z0-9_]+)\)`)

func main() {
	spec, err := os.ReadFile("api/openapi.json")
	must(err)
	var doc document
	must(json.Unmarshal(spec, &doc))
	handlers := map[string]string{}
	// These two routes deliberately adapt a shared implementation with a fixed mode.
	handlers["POST /api/dashboards/{id}/panels"] = "r.savePanel(w, req, false)"
	handlers["PATCH /api/dashboards/{id}/panels/{panelId}"] = "r.savePanel(w, req, true)"

	var keys []string
	for path, methods := range doc.Paths {
		for method := range methods {
			keys = append(keys, strings.ToUpper(method)+" "+path)
		}
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("// Code generated by cmd/genopenapi; DO NOT EDIT.\npackage api\n\n")
	b.WriteString("import (\n\t\"net/http\"\n\n\t\"github.com/zfogg/spaniel/internal/api/apigen\"\n)\n\n")
	b.WriteString("var _ apigen.ServerInterface = (*Router)(nil)\n\n")
	for _, key := range keys {
		parts := strings.SplitN(key, " ", 2)
		op := doc.Paths[parts[1]][strings.ToLower(parts[0])]
		if op.OperationID == "" {
			must(fmt.Errorf("%s has no operationId", key))
		}
		handler, ok := handlers[key]
		if !ok {
			handler = "r." + strings.ToLower(op.OperationID[:1]) + op.OperationID[1:] + "(w, req)"
		}
		// The few public operation names that intentionally differ from their
		// long-standing Router implementation remain explicit here.
		switch op.OperationID {
		case "getHealth":
			handler = "r.health(w, req)"
		case "getOpenAPISpec":
			handler = "r.openAPI(w, req)"
		case "getDatabaseSchema":
			handler = "r.databaseSchema(w, req)"
		case "setSessionBaseline":
			handler = "r.baselineSession(w, req)"
		case "exportSessionBaseline":
			handler = "r.exportBaseline(w, req)"
		case "searchTelemetry":
			handler = "r.search(w, req)"
		case "compactStorage":
			handler = "r.compact(w, req)"
		case "pruneStorage":
			handler = "r.prune(w, req)"
		case "listIssues":
			handler = "r.getIssues(w, req)"
		case "listQueryCatalog":
			handler = "r.queryCatalog(w, req)"
		case "deleteDashboardPanel":
			handler = "r.deletePanel(w, req)"
		case "deleteDashboardVariable":
			handler = "r.deleteVariable(w, req)"
		case "patchAlertSilence":
			handler = "r.updateAlertSilence(w, req)"
		case "moveDashboardPanel":
			handler = "r.movePanel(w, req)"
		case "createDashboardVariable":
			handler = "r.saveVariable(w, req)"
		case "listNotifications":
			handler = "r.listNotifications(w, req)"
		case "readNotification":
			handler = "r.readNotification(w, req)"
		case "acknowledgeNotification":
			handler = "r.acknowledgeNotification(w, req)"
		}
		name := strings.ToUpper(op.OperationID[:1]) + op.OperationID[1:]
		params := ""
		for _, parameter := range regexp.MustCompile(`\{([^}]+)\}`).FindAllStringSubmatch(parts[1], -1) {
			params += ", " + parameter[1] + " string"
		}
		for _, parameter := range op.Parameters {
			if parameter.In == "query" {
				params += ", _ apigen." + name + "Params"
				break
			}
		}
		fmt.Fprintf(&b, "func (r *Router) %s(w http.ResponseWriter, req *http.Request%s) { %s }\n\n", name, params, handler)
	}
	formatted, err := format.Source([]byte(b.String()))
	must(err)
	must(os.WriteFile("internal/api/openapi_adapter.gen.go", formatted, 0o644))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
