// Command genschema verifies the migrated DuckDB public views and writes the
// portable schema artifacts consumed by the API and frontend.
package main

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"

	"github.com/zfogg/spaniel/internal/storage"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}
func main() {
	dir, err := os.MkdirTemp("", "spaniel-schema-")
	must(err)
	defer os.RemoveAll(dir)
	c, err := storage.GenerateSchemaCatalog(filepath.Join(dir, "schema.duckdb"))
	must(err)
	b, err := json.MarshalIndent(c, "", "  ")
	must(err)
	b = append(b, '\n')
	must(os.MkdirAll("internal/generated", 0755))
	must(os.WriteFile("internal/generated/schema_catalog.json", b, 0644))
	must(os.MkdirAll("docs", 0755))
	var md strings.Builder
	fmt.Fprintf(&md, "# Spaniel database schema\n\nCatalog version `%s`; schema fingerprint `%s`.\n\n", c.Version, c.Fingerprint)
	for _, v := range c.Views {
		fmt.Fprintf(&md, "## `%s`\n\n%s\n\n| Column | DuckDB type | Use it for |\n|---|---|---|\n", v.Name, v.Purpose)
		for _, col := range v.Columns {
			fmt.Fprintf(&md, "| `%s` | `%s` | %s |\n", col.Name, col.Type, col.UseItFor)
		}
		for _, s := range v.Samples {
			fmt.Fprintf(&md, "\n### %s\n\n```sql\n%s\n```\n", s.Title, s.SQL)
		}
	}
	must(os.WriteFile("docs/database-schema.md", []byte(md.String()), 0644))
	must(os.WriteFile("docs/database-schema.html", []byte("<!doctype html><meta charset=utf-8><title>Spaniel database schema</title><pre>"+html.EscapeString(md.String())+"</pre>\n"), 0644))
	must(os.MkdirAll("frontend/src/generated", 0755))
	must(os.WriteFile("frontend/src/generated/schemaCatalog.ts", []byte("// Generated by cmd/genschema.\nexport const schemaCatalog = ("+string(b)+") as const\n"), 0644))
}
